function nameGen(type){
	var nm1 = ["Álvaro","Ângelo","Émerson","Érico","Adriano","Agildo","Alberto","Alceu","Alessandro","Alexandre","Alfredo","André","Antônio","Antenor","Antonio","Armando","Arnaldo","Arnoldo","Arthur","Artur","Augusto","Aurélio","Benício","Benedito","Bernardo","Breno","Bruno","Cássio","César","Cícero","Caio","Carlos","Cauã","Cauê","Cláudio","Cleiton","Conrado","Cristiano","Daniel","Danilo","Davi","Diego","Diogo","Douglas","Edgar","Edson","Eduardo","Elísio","Emanuel","Enrico","Erasmo","Eric","Escobar","Estevão","Evandro","Fábio","Fabiano","Fabrício","Felipe","Fernando","Flávio","Francisco","Frederico","Gabriel","Geraldo","Gilberto","Gilmar","Gilson","Giovane","Guilherme","Gustavo","Heitor","Henrique","Hugo","Iago","Igor","Isaías","Ivanildo","Ivo","Júnior","João","Joaquim","Jonas","Jorge","José","Juliano","Julio","Jurandir","Kléber","Lúcio","Leandro","Leonardo","Lorenzo","Lucas","Luciano","Luiz","Márcio","Mário","Manoel","Manuel","Marcelo","Marcos","Mateus","Maurício","Mauro","Michel","Miguel","Milton","Moacir","Murilo","Nelson","Neto","Nicolas","Nilton","Norberto","Oscar","Osmar","Osvaldo","Otávio","Pablo","Paulo","Pedro","Rafael","Raul","Reginaldo","Reinaldo","Renan","Renato","Ricardo","Roberto","Rodolfo","Rodrigo","Rogério","Romeu","Ronaldo","Sérgio","Sílvio","Samuel","Sandro","Saulo","Sebastião","Sidnei","Túlio","Tadeu","Teodoro","Thiago","Tiago","Tomás","Vítor","Valdomiro","Vicente","Vinícius","Vinicius","Vitor"];
	﻿var  nm2 = ["Ágata","Áurea","Ângela","Érica","Adelaide","Adriana","Alícia","Alana","Alcione","Alessandra","Alice","Aline","Amélia","Amanda","Ana","Andréia","Andressa","Angélica","Anita","Antonieta","Ariane","Arlene","Bárbara","Beatriz","Benedita","Berenice","Betina","Bianca","Bruna","Cássia","Cíntia","Camila","Carina","Carla","Carolina","Caroline","Catarina","Cecília","Cláudia","Clara","Clarice","Clarissa","Cristiane","Cristina","Débora","Daiana","Daniela","Danila","Darcy","Denise","Diana","Edna","Eduarda","Elaine","Eliana","Elis","Elisa","Elisandra","Elizabete","Eloá","Eloísa","Elza","Emília","Estefânia","Estela","Ester","Esther","Evelyn","Fátima","Fabíola","Fabiana","Fabiane","Fernanda","Flávia","Franciane","Francine","Gabriela","Giovana","Gisele","Gislaine","Helena","Heloísa","Heloisa","Hilda","Iara","Inês","Iolanda","Isabel","Isabela","Isadora","Ivete","Ivone","Izabel","Jéssica","Júlia","Janaína","Janice","Jaqueline","Joana","Judite","Julia","Juliana","Julieta","Kelly","Lívia","Lúcia","Laís","Larissa","Laura","Lavínia","Leila","Letícia","Liana","Lorena","Luísa","Luíza","Luana","Luciana","Lucielle","Luiza","Márcia","Mônica","Magali","Maiara","Maitê","Manoela","Manuela","Marília","Marcela","Marcia","Maria","Mariana","Mariane","Marilsa","Marina","Marisa","Marlene","Marli","Marta","Matilde","Melissa","Michele","Milena","Mirela","Miriam","Nívea","Natália","Neusa","Nicole","Nina","Odete","Olívia","Olga","Paloma","Paola","Patrícia","Paula","Poliana","Poliane","Priscila","Rafaela","Raquel","Rebeca","Regina","Renata","Rita","Roberta","Rosângela","Rosa","Rosana","Sílvia","Sônia","Sabrina","Samanta","Sandra","Sara","Sheila","Shirlei","Silvana","Simone","Sofia","Solange","Soraia","Suzana","Tânia","Taís","Talita","Tatiana","Teresa","Tereza","Thaís","Vânia","Valéria","Valentina","Valquíria","Vanda","Vanessa","Vanuza","Verônica","Vera","Virgínia","Vitória","Vivian","Wanda","Yasmin","Yolanda","Zélia","Zilda"];
	var nmf = ["Álvarez","Álves","Ávila","Aguiar","Albuquerque","Alencar","Almeida","Alvarez","Alves","Amaral","Ambrósio","Amorim","Andrade","Antunes","Araújo","Arruda","Assis","Assunção","Azevedo","Barbosa","Barreto","Barros","Barroso","Bastos","Batista","Belchior","Belluci","Bernardes","Bezerra","Bitencourt","Boaventura","Bonfim","Borba","Borges","Bosco","Braga","Branco","Brandão","Braz","Brito","Bueno","Câmara","Cabral","Caetano","Camargo","Campos","Canto","Cardoso","Carmo","Carvalho","Castilho","Castro","Cavalcanti","Cerqueira","Chagas","Chaves","Clemente","Coelho","Conceição","Cordeiro","Corrêa","Correia","Costa","Couto","Cruz","Cunha","Damasceno","Delchiaro","Delgado","Dias","Duarte","Dutra","Espíndola","Esteves","Fagundes","Falcão","Farias","Fernandes","Ferraz","Ferreira","Figueiredo","Flores","Fonseca","Fontana","Fontes","Fraga","Freitas","Furtado","Garcia","Gimenes","Gomes","Gonçalves","Guedes","Guerra","Guimarães","Hamada","Hamamura","Hashimoto","Henriques","Higashi","Ito","Jardim","Jesus","Justino","Justo","Kanashiro","Kimura","Lópes","Lacerda","Leal","Leitão","Leite","Lemos","Lima","Linhares","Lobo","Lopes","Lourenço","Luz","Macedo","Machado","Maciel","Madruga","Magalhães","Maia","Maldonado","Mantovani","Marques","Martins","Matos","Medeiras","Medeiros","Medina","Meireles","Melo","Mendes","Menezes","Miranda","Monteiro","Moraes","Morais","Moreira","Moura","Nakamura","Nakata","Nascimento","Nazário","Neves","Nogueira","Nunes","Oliveira","Pacheco","Padilha","Paim","Paiva","Paschoal","Passos","Paz","Pedroso","Pereira","Peres","Pessoa","Pimentel","Pinheiro","Pinho","Pinto","Pires","Prado","Prestes","Quadros","Queiroz","Quintana","Ramos","Reis","Rezende","Ribeiro","Rios","Rocha","Rodrigues","Rosário","Rosa","Ruiz","Sá","Salgado","Salles","Sanches","Santana","Santos","Saraiva","Sato","Serra","Serrano","Shinoda","Silva","Silveira","Simões","Siqueira","Soares","Souza","Takeda","Tavares","Teixeira","Vale","Vargas","Vasconcelos","Vaz","Velho","Ventura","Vidal","Vieira","Vila","Watanabe","Ximenes","Yamada","Yoshimura","Zanetti"];
	var nmf2 = ["Álvarez","Álves","de Ávila","Aguiar","de Albuquerque","Alencar","de Almeida","Alvarez","Alves","do Amaral","Ambrósio","Amorim","de Andrade","Antunes","Araújo","Arruda","de Assis","de Assunção","de Azevedo","Barbosa","Barreto","Barros","Barroso","Bastos","Batista","Belchior","Belluci","Bernardes","Bezerra","Bitencourt","Boaventura","Bonfim","Borba","Borges","Bosco","Braga","Branco","Brandão","Braz","Brito","Bueno","Câmara","Cabral","Caetano","Camargo","de Campos","Canto","Cardoso","Carmo","Carvalho","Castilho","de Castro","Cavalcanti","Cerqueira","Chagas","Chaves","Clemente","Coelho","da Conceição","Cordeiro","Corrêa","Correia","da Costa","Couto","da Cruz","da Cunha","Damasceno","Delchiaro","Delgado","Dias","Duarte","Dutra","Espíndola","Esteves","Fagundes","Falcão","Farias","Fernandes","Ferraz","Ferreira","Figueiredo","Flores","da Fonseca","Fontana","Fontes","Fraga","de Freitas","Furtado","Garcia","Gimenes","Gomes","Gonçalves","Guedes","Guerra","Guimarães","Hamada","Hamamura","Hashimoto","Henriques","Higashi","Ito","Jardim","de Jesus","Justino","Justo","Kanashiro","Kimura","Lópes","Lacerda","Leal","Leitão","Leite","Lemos","de Lima","Linhares","Lobo","Lopes","Lourenço","Luz","Macedo","Machado","Maciel","Madruga","Magalhães","Maia","Maldonado","Mantovani","Marques","Martins","de Matos","Medeiras","Medeiros","Medina","Meireles","Melo","Mendes","Menezes","Miranda","Monteiro","Moraes","Morais","Moreira","Moura","Nakamura","Nakata","do Nascimento","Nazário","Neves","Nogueira","Nunes","de Oliveira","Pacheco","Padilha","Paim","Paiva","Paschoal","Passos","Paz","Pedroso","Pereira","Peres","Pessoa","Pimentel","Pinheiro","Pinho","Pinto","Pires","Prado","Prestes","Quadros","Queiroz","Quintana","Ramos","dos Reis","Rezende","Ribeiro","Rios","Rocha","Rodrigues","Rosário","Rosa","Ruiz","Sá","Salgado","de Salles","Sanches","Santana","dos Santos","Saraiva","Sato","Serra","Serrano","Shinoda","da Silva","Silveira","Simões","da Siqueira","Soares","de Souza","Takeda","Tavares","Teixeira","do Vale","Vargas","Vasconcelos","Vaz","Velho","Ventura","Vidal","Vieira","Vila","Watanabe","Ximenes","Yamada","Yoshimura","Zanetti"];

	var tp = type;
	var br = "";
	var element = document.createElement("div");
	element.setAttribute("id", "result");
	
	for(i = 0; i < 10; i++){
		rnd2 = Math.random() * nmf.length | 0;
		rnd3 = Math.random() * nmf2.length | 0;
		while(rnd2 === rnd3){
			rnd3 = Math.random() * nmf2.length | 0;
		}
		if(tp === 1){
			rnd = Math.random() * nm2.length | 0;
			names = nm2[rnd] + " " + nmf[rnd2] + " " + nmf2[rnd3];
			nm2.splice(rnd, 1);
		}else{
			rnd = Math.random() * nm1.length | 0;
			names = nm1[rnd] + " " + nmf[rnd2] + " " + nmf2[rnd3];
			nm1.splice(rnd, 1);
		}
		nmf.splice(rnd2, 1);
		nmf2.splice(rnd3, 1);
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}