function nameGen(type){
	var nm1 = ["Abraham","Adalberto","Adan","Adolfo","Afonso","Agostiño","Alberte","Aleixo","Alexandre","Alfonso","Amaro","Ambrosio","André","Andre","Anibal","Anselmo","Antón","Anton","Anxo","Artús","Artur","Arximiro","Atanasio","Augusto","Aurelio","Axel","Baltasar","Bartolomeu","Basil","Baudilio","Beltaine","Bento","Benvido","Benxamin","Bernabe","Bernaldo","Bieito","Boaventura","Brais","Bran","Brandán","Breixo","Breogán","Bruno","Caetano","Calisto","Calros","Camilo","Carlos","Cesar","Cibrán","Cibran","Cibrao","Cilistro","Ciriaco","Clemenzo","Clodio","Cosme","Cristobo","Davide","Denis","Diogo","Domingos","Duarte","Eloi","Ernesto","Estevo","Euloxio","Eutelo","Exidio","Fabian","Farruco","Fernan","Fidel","Filipe","Fiodor","Firmino","Fiz","Frederico","Froitoso","Gael","Galez","Gasparo","Goio","Gonzalo","Gracia","Gustavo","Hadrian","Heitor","Henrique","Hilario","Honorio","Hugo","Humberto","Iago","Ignacio","Isaac","Isidoro","Ivan","Leon","Leonardo","Leopoldo","Leuter","Lino","Llounguís","Lois","Lorenzo","Lucas","Manoel","Marcelo","Marcos","Mariño","Mariano","Mario","Martiño","Mateu","Matias","Mauricio","Maximo","Maxin","Melchor","Mendo","Micael","Millan","Moises","Moreno","Nícer","Narciso","Nicolau","Noa","Nocenci","Nuno","Octavio","Oliverio","Oscar","Outel","Paio","Pascoal","Paulo","Pedro","Pelaxio","Pio","Placido","Prudencio","Quentin","Rafael","Raimundo","Ramiro","Ramon","Raul","Remixio","Ricardo","Roberto","Rodolfo","Rodrigo","Roi","Roibén","Roman","Rosendo","Roxelio","Ruben","Sabino","Salomon","Sebastian","Segundo","Senin","Serxio","Sexismondo","Tadeu","Teodoro","Tomas","Tome","Torcado","Tristán","Urbano","Uxío","Uxio","Vítor","Valentin","Valerio","Ventura","Vicenzo","Victor","Vidal","Virxilio","Xabier","Xacinto","Xacob","Xacobe","Xaime","Xan","Xaquin","Xenaro","Xenxo","Xeremias","Xerman","Xerome","Xeronimo","Xesus","Xián","Xilgorio","Xoán","Xoan","Xoaquin","Xob","Xoel","Xonas","Xosé","Xose","Xosue","Xurxo","Xustino","Xusto","Zaquiel"];
	var nm2 = ["Ada","Adega","Adela","Adelaida","Adruína","Aida","Aine","Alba","Albina","Alborada","Alda","Alexandra","Alma","Alodia","Aloia","Amada","Amadora","Amalia","Ambar","Amelia","Amparo","Ana","Andreia","Anisia","Antía","Antela","Antia","Anuncia","Anxela","Araceli","Aranzazu","Armida","Artemisa","Asunta","Avelina","Azucena","Baia","Balbina","Baltasara","Barbara","Beatriz","Benvida","Berenice","Berta","Bieita","Bríxida","Branca","Braulia","Breixa","Brianda","Brixida","Caetana","Caridade","Carme","Carmela","Carola","Casilda","Casimira","Catarina","Catuxa","Cecia","Ceferina","Celsa","Celtia","Cibrá","Cibrán","Cipriana","Cira","Clorinda","Clotilde","Columba","Comba","Coralia","Cornelia","Cosima","Cosme","Crara","Daniela","Davinia","Delfina","Desideria","Dionisia","Dominga","Dores","Dorinda","Dorotea","Dositea","Edelmira","Edenia","Eduvixe","Eines","Eira","Elba","Elisabet","Elvira","Emiliana","Erea","Ester","Estrela","Etelvina","Eufemia","Euxea","Eva","Fabia","Faustina","Felicidade","Felicita","Filipa","Filomena","Francisca","Frida","Froila","Galicia","Gliceria","Graciela","Gregoria","Griselda","Guendolina","Hadriana","Heladia","Helena","Helia","Heloisa","Hilaria","Honorina","Icía","Icia","Ida","Imelda","Ines","Inmaculada","Iola","Iolanda","Iria","Irimia","Isabela","Isadora","Isaura","Isidra","Isolda","Isolina","Landelina","Leda","Ledicia","Leticia","Liboria","Lidia","Liduvina","Lilia","Liria","Lua","Lucia","Lucila","Luz","Madalena","Madanela","Mafalda","Mara","Marcelina","Margarida","Mariña","Marta","Martiña","Maruxa","Maxima","Maxina","Melania","Melba","Melchora","Merces","Minia","Mirta","Natalia","Natividade","Navia","Nelida","Nereida","Neves","Nicanora","Nicasia","Nicolasa","Nidia","Noela","Noelia","Noemia","Nuncia","Nuria","Octavia","Odelia","Ofelia","Olalla","Olegaria","Olimpia","Olivia","Onda","Oriana","Orosia","Otile","Otilia","Ovidia","Palmira","Pamela","Panfila","Pascuala","Paula","Paz","Pelaxia","Penelope","Peregrina","Piedade","Pilar","Polendiñe","Pomba","Porfiria","Prisca","Prospera","Purificacion","Quiteria","Rafaela","Rebeca","Regina","Remedios","Rexina","Roca","Rosa","Rosamunda","Rut","Sabela","Sabina","Salome","Salvia","Sara","Sebastiana","Serafina","Severa","Sibilina","Silvana","Silvina","Simona","Sira","Socorro","Sofia","Sol","Soledade","Tariexa","Tarsila","Tegra","Teodora","Teofila","Tereixa","Tita","Tomasa","Trindade","Urraca","Uxía","Uxío","Uxia","Venancia","Verisima","Vicenta","Violante","Violeta","Viridiana","Virxinia","Vitoria","Xacinta","Xaquina","Xela","Xema","Xenara","Xenia","Xenoveva","Xenxa","Xertrude","Xiana","Xiao","Xilda","Xisela","Xoana","Xosefa","Xusana","Xusta","Xustina","Zenobia","Zoraida","Zulena","Zulima"];
	var nm3 = ["Abráldez","Abréu","Aceija","Acevedo","Acuna","Aday","Adión","Agar","Agramonte","Agron","Agudelo","Aguiar","Aldana","Amorin","Andal","Andon","Andrada","Andrade","Aponte","Araújo","Arceo","Ares","Aris","Arra","Avellaneda","Avina","Bahamonde","Balboa","Barcia","Barela","Bares","Barra","Barreira","Barreiro","Barroso","Basquez","Bayona","Becerra","Bellón","Bello","Boan","Borrajo","Botello","Bouza","Bran","Brea","Bugarin","Caamano","Cadavid","Caira","Caldas","Caldeira","Cales","Calo","Camba","Cambra","Cancio","Candia","Canlas","Canosa","Canton","Cardosa","Carreiro","Castelan","Castro","Cea","Cervantes","Cervino","Chacón","Chan","Coello","Colan","Cora","Cota","Cueto","Curbelo","Dantes","Davila","Demato","Deras","Donis","Durán","Encinas","Fajardo","Farina","Ferreira","Ferreiro","Ferreyra","Fiallo","Figueredo","Figueroa","Fragoso","Fraijo","Garduno","Gironda","Godoy","Goris","Goy","Goya","Goyanes","Grana","Junco","Lamas","Lata","Laza","Lazo","Lema","Lemos","Lemus","Lence","Leyton","Lista","Lucio","Lugo","Macedo","Marcelin","Marin","Martis","Mato","Mazon","Meda","Medal","Medin","Melendrez","Mella","Melle","Mendez","Mera","Mero","Millan","Mira","Miramontes","Mones","Montecalvo","Montelongo","Monteverde","Morquecho","Muniz","Naron","Navia","Neira","Neyra","Noboa","Nogueira","Noia","Nova","Novoa","Noya","Ocampo","Ogas","Ovalle","Padin","Padron","Pallares","Parada","Parga","Patino","Pazos","Peredo","Perera","Pero","Perrino","Pineiro","Pino","Pinon","Pinta","Porras","Pose","Puga","Quiroga","Ramo","Rana","Ravelo","Raya","Razo","Reza","Rios","Rivadeneira","Rodas","Rodela","Rodis","Ron","Rosal","Rosales","Roybal","Rozas","Rua","Rumbo","Ruybal","Saavedra","Sabedra","Salgado","Sandino","Sanjurjo","Santiago","Santizo","Sarabia","Saravia","Sardinas","Savedra","Sedor","Seoane","Silveira","Silvestre","Sion","Siqueiros","Sisto","Solar","Somoza","Sotolongo","Souto","Taboada","Tapia","Tenorio","Testa","Toca","Toran","Torre","Torres","Troche","Troncoso","Ulloa","Vahamonde","Valdovinos","Vale","Vales","Valladares","Vallin","Vara","Varela","Varon","Vasquez","Vazquez","Verdugo","Vieira","Viera","Vigo","Vina","Vinal","Vinas","Viveiros","Zea","da Villa","de Andrade","de Brito","de Castro","de Pena","de Rego","de Soto","del Villar"];
	
	var br = "";
	var tp = type;
	var element = document.createElement("div");
	element.setAttribute("id", "result");

	for(i = 0; i < 10; i++){
		rnd2 = Math.floor(Math.random() * nm3.length);
		if(tp === 1){
			rnd = Math.floor(Math.random() * nm2.length);
			names = nm2[rnd] + " " + nm3[rnd2];
			nm2.splice(rnd, 1);
		}else{
			rnd = Math.floor(Math.random() * nm1.length);
			names = nm1[rnd] + " " + nm3[rnd2];
			nm1.splice(rnd, 1);
		}
		nm3.splice(rnd2, 1);
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}