function nameGen(type){
	var nm1 = ["Abramo","Adamo","Adovardo","Agnolino","Agnolo","Agostino","Alamanno","Alberto","Albizzo","Alessandro","Alessio","Alesso","Alfonso","Ambrogio","Amerigo","Amideo","Andrea","Anichino","Antonio","Apollonio","Arrigo","Attaviano","Averardo","Baldassarr","Baldo","Banco","Bandino","Bardo","Barone","Bartolo","Bartolomeo","Bastiano","Battista","Bencivenni","Benedetto","Benino","Benozzo","Benvenuto","Bernaba","Bernardo","Bertino","Berto","Bettino","Betto","Biagio","Bianco","Bindo","Boccaccio","Bonacorso","Bonaguida","Bonaiuto","Bonifazio","Bonino","Bono","Bonsi","Borso","Bruno","Buccio","Buono","Buto","Cambino","Cambio","Cardinale","Carlo","Castello","Cecco","Cenni","Chiaro","Chimenti","Chimento","Cino","Cione","Cipriano","Cola","Conte","Corrado","Corso","Cosimo","Cristofano","Cristoforo","Daddo","Daniele","Daniello","Dego","Deo","Diedi","Dino","Doffo","Domenico","Donato","Donnino","Duccio","Ercole","Fabiano","Fede","Federigo","Felice","Feo","Filippo","Fiorentino","Francesco","Franco","Frosino","Gabbriello","Galeazzo","Gasparo","Gentile","Geri","Gherardino","Gherardo","Ghirigoro","Gianfrancesco","Giannino","Giannozzo","Giano","Gino","Giorgio","Giotto","Giovacchin","Giovanni","Giovannozz","Giovenco","Girolamo","Giulio","Giunta","Giuseppe","Giusto","Goro","Grazia","Gualterott","Gualtieri","Guasparre","Guccio","Guelfo","Guglielmo","Guido","Guidobaldo","Iacomo","Iacopo","Jacopo","Lamberto","Lando","Lapaccio","Lapo","Lazzero","Leonardo","Leonello","Lippo","Lodovico","Lorenzo","Lotto","Luca","Ludovico","Luigi","Maccio","Maffeo","Mainardo","Manetto","Manno","Marchionne","Marco","Mariano","Marino","Mariotto","Marsilio","Martino","Maso","Matteo","Meo","Michele","Migliore","Miniato","Mino","Monte","Naldo","Nanni","Nannino","Nardo","Nello","Nencio","Neri","Niccola","Niccolaio","Niccolino","Niccolo","Nigi","Nofri","Nozzo","Nuccio","Nuto","Orlando","Ormanno","Ottavio","Pace","Pacino","Pagolo","Palla","Pandolfo","Paolo","Papi","Pasquino","Pierandrea","Piero","Pierozzo","Pietro","Pippo","Polito","Priore","Prospero","Puccino","Puccio","Ramondo","Riccardo","Ricco","Ridolfo","Rinaldo","Rinieri","Ristoro","Roberto","Romigi","Romolo","Rosso","Ruggieri","Salvadore","Salvestro","Salvi","Sandro","Santi","Scolaio","Sigismondo","Simone","Sinibaldo","Smeraldo","Spinello","Stagio","Stefano","Stoldo","Strozza","Taddeo","Tano","Tieri","Tingo","Tommaso","Tomme","Ubertino","Uberto","Ugo","Ugolino","Uguccione","Ulisse","Urbano","Vanni","Vannozzo","Ventura","Vettorio","Vico","Vieri","Vincenzo","Zaccheria","Zanobi"];
	var nm2 = ["Adriana","Adrianna","Agnella","Agnese","Agnesina","Agnola","Alessandra","Anastasia","Andrea","Andreuola","Andriana","Angela","Antonia","Anzola","Arcanzola","Aurelia","Bandecca","Bartola","Bartolomea","Battista","Bella","Belloza","Benedicta","Beneta","Bianca","Bice","Bona","Brisca","Brisscha","Buona","Catalina","Caterina","Cecilia","Chataruza","Chiara","Chola","Cicilia","Ciecherella","Ciosa","Ciuta","Clara","Cristina","Dea","Diana","Dianora","Dolce","Druda","Elena","Elisabetta","Elizabeth","Euphemia","Faustina","Fiametta","Filippa","Fiora","Flora","Foscarina","Foscharina","Francesca","Franceschina","Francheta","Franchetta","Gemma","Ghinga","Ghita","Gianetta","Gilia","Ginevra","Giovanna","Giuliana","Gostanza","Gradeniga","Grana","Helena","Ippolita","Isabella","Isabetta","Isotta","Jacobella","Jacopa","Joanna","Lagia","Lapa","Laura","Lauretta","Lavinia","Lena","Leonarda","Letta","Liona","Lippa","Lisa","Lisabetta","Loredana","Lorenza","Lucia","Lucretia","Lucrezia","Madaluza","Maddalena","Madelena","Magdalena","Margarita","Margherita","Maria","Marieta","Marietta","Marina","Marsilia","Martinella","Masina","Maurocena","Mea","Mella","Moderata","Moresina","Nanna","Nencia","Nezetta","Nicolosa","Nicolosia","Novella","Nucca","Olimpia","Olympia","Orsa","Pantasilea","Paola","Pasqua","Paula","Pellegrina","Pia","Piera","Pisana","Properzia","Quirina","Rigarda","Riguardatta","Salvaza","Sandra","Santa","Serena","Simona","Sofia","Sordamor","Stella","Taddea","Tessa","Tita","Tomasia","Tommasa","Tullia","Ursa","Veroncia","Veronica","Vittoria","Ysabeta","Zaneta","Zuana"];
	var nm3 = ["Abiate","Abrami","Acardolo","Acceptati","Acciaioli","Accialini","Accottanto","Accottato","Acerbi","Acharigi","Acolti","Acordolo","Alban","Albani","Albaregno","Albarenno","Albergati","Albergotti","Alberighi","Alberti","Albicio","Albirio","Albiso","Albizi","Alboresi","Arcimboldo","Avonal","Babbi","Babilonio","Badoer","Baldovinetti","Barbachollo","Barbacia","Barbadori","Barbalini","Barbamachollo","Barbani","Barbarigi","Barbarigo","Barbaro","Barbaroman","Barbato","Barbazini","Barberan","Barbeta","Barbi","Barbieri","Barbigia","Barbo","Barbolani","Barbolini","Barozzi","Bascio","Bassadoar","Bellegno","Bellini","Bembo","Benedetti","Bernardo","Boldu","Bon","Bondimier","Bonzi","Bragadin","Bronzino","Caladri","Calandri","Calandrini","Calbi","Calbo","Calcagnini","Caldarini","Calderara","Caldogne","Caliara","Callocci","Caloprara","Calvacanti","Calvane","Calza","Capello","Carafa","Cellini","Contarini","Corner","Crivelli","Dalle Boccole","Dandolo","Donado","Donato","Falier","Farnese","Fiamolin","Fiaschi","Fideli","Fiesi","Figa","Figiovanni","Filiarchi","Fiocarda","Fiolario","Fiolo","Fioranati","Fioravanti","Fiorensi","Fiorina","Firavanti","Fontana","Fonte","Foscari","Foscarini","Frescobaldi","Garzoni","Ghezzo","Giustiniani","Gonzaga","Gradenigo","Grimani","Gritti","Lego","Lignago","Lion","Longo","Loredan","Luppi","Malatesta","Malipiero","Marcello","Marin","Matelizi","Mauroceno","Memo","Michel","Michiel","Mocenigo","Morosini","Mudazo","Orsini","Palmio","Pisani","Priuli","Querini","Riccoboni","Rosso","Sanudo","Sforza","Spizega","Tiepolo","Trevisan","Valier","Vasari","Veneziano","Venier","Viari","Visconti","Vitelli","Zane","Zani","Ziani","Zorzi","Zustignan","d'Este","da Barberino","da Canal","da Chioza","da Filichaia","da Leze","da Molin","da Montefeltro","da Vigo","de Abagio","de Abbrixio","de Abondiolis","de Accora","de Albairate","de Albano","de Albarate","de Albe","de Alberinis","de Albertis","de Albertonibvs","de Albiate","de Albrixis","de Albvxiis","de Barbanario","de Calchano","de Calco","de Calis","de Calvenzano","de Calvio","de Calvis","de Fialis","de Fiandkonis","de Fidellis","de Fiedricis","de Fiescho","de Figino","de Filago","de Fino","de Fiorino","de Rossi","di Albrisis","di Fiorelli","di Prioli"];

	var br = "";
	var tp = type;
	var element = document.createElement("div");
	element.setAttribute("id", "result");

	for(i = 0; i < 10; i++){
		rnd2 = Math.floor(Math.random() * nm3.length);
		if(tp === 1){
			rnd = Math.floor(Math.random() * nm2.length);
			names = nm2[rnd] + " " + nm3[rnd2];
			nm2.splice(rnd, 1);
		}else{
			rnd = Math.floor(Math.random() * nm1.length);
			names = nm1[rnd] + " " + nm3[rnd2];
			nm1.splice(rnd, 1);
		}
		nm3.splice(rnd2, 1);
		br = document.createElement('br');	
		element.appendChild(document.createTextNode(names));
		element.appendChild(br);
	}
	if(document.getElementById("result")){
		document.getElementById("placeholder").removeChild(document.getElementById("result"));
	}		
	document.getElementById("placeholder").appendChild(element);
}