__all__ = ['animeAttacks']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nm1', 'nm4', 'nameGen', 'nm5', 'nm3', 'nm2', 'nm6'])
@Js
def PyJsHoisted_nameGen_(this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this}, var)
    var.registers(['result'])
    var.put('result', Js([]))
    #for JS loop
    var.put('i', Js(0.0))
    while (var.get('i')<Js(10.0)):
        try:
            if (var.get('i')<Js(2.0)):
                var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm2').get('length'))))
                var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length'))))
                var.put('names', ((var.get('nm2').get(var.get('rnd'))+Js(' '))+var.get('nm3').get(var.get('rnd2'))))
            else:
                if (var.get('i')<Js(4.0)):
                    var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm1').get('length'))))
                    var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm2').get('length'))))
                    var.put('rnd3', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length'))))
                    var.put('names', ((((var.get('nm1').get(var.get('rnd'))+Js(' '))+var.get('nm2').get(var.get('rnd2')))+Js(' '))+var.get('nm3').get(var.get('rnd3'))))
                else:
                    if (var.get('i')<Js(6.0)):
                        var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length'))))
                        var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length'))))
                        var.put('rnd3', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm6').get('length'))))
                        var.put('rnd4', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length'))))
                        var.put('names', ((((((var.get('nm4').get(var.get('rnd'))+Js(' '))+var.get('nm5').get(var.get('rnd2')))+Js(', '))+var.get('nm6').get(var.get('rnd3')))+Js(' '))+var.get('nm3').get(var.get('rnd4'))))
                    else:
                        if (var.get('i')<Js(8.0)):
                            var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length'))))
                            var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length'))))
                            var.put('rnd3', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm6').get('length'))))
                            var.put('rnd4', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length'))))
                            while PyJsStrictEq(var.get('rnd2'),var.get('rnd4')):
                                var.put('rnd4', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length'))))
                            var.put('names', ((((((var.get('nm4').get(var.get('rnd'))+Js(' '))+var.get('nm5').get(var.get('rnd2')))+Js(' '))+var.get('nm6').get(var.get('rnd3')))+Js(' '))+var.get('nm5').get(var.get('rnd4'))))
                        else:
                            var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm6').get('length'))))
                            var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length'))))
                            var.put('rnd3', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length'))))
                            var.put('rnd4', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length'))))
                            var.put('names', ((((((var.get('nm6').get(var.get('rnd'))+Js(' '))+var.get('nm3').get(var.get('rnd2')))+Js(' of '))+var.get('nm4').get(var.get('rnd3')))+Js(' '))+var.get('nm5').get(var.get('rnd4'))))
            var.get('result').callprop('push', var.get('names'))
        finally:
                (var.put('i',Js(var.get('i').to_number())+Js(1))-Js(1))
    pass
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
var.put('nm1', Js([Js('Abominable'), Js('Aching'), Js('Adamantine'), Js('Adept'), Js('Advanced'), Js('Aggressive'), Js('Agile'), Js('Agonizing'), Js('Amplified'), Js('Ancient'), Js('Angelic'), Js('Angry'), Js('Arch'), Js('Azure'), Js('Basic'), Js('Black'), Js('Blinding'), Js('Bright'), Js('Brilliant'), Js('Brutal'), Js('Burning'), Js('Careless'), Js('Chaotic'), Js('Chief'), Js('Classic'), Js('Clean'), Js('Colossal'), Js('Combination'), Js('Complete'), Js('Complex'), Js('Composed'), Js('Confusing'), Js('Corrupt'), Js('Counter'), Js('Courageous'), Js('Crazed'), Js('Crazy'), Js('Crimson'), Js('Cruel'), Js('Crushing'), Js('Dancing'), Js('Dark'), Js('Dead'), Js('Deadly'), Js('Defensive'), Js('Defiant'), Js('Definitive'), Js('Delayed'), Js('Delirious'), Js('Demonic'), Js('Devouring'), Js('Dieing'), Js('Diligent'), Js('Direct'), Js('Dirty'), Js('Double'), Js('Draconic'), Js('Drunken'), Js('Dual'), Js('Dynamic'), Js('Eager'), Js('Elegant'), Js('Elementary'), Js('Enchanted'), Js('Enchanting'), Js('Enlightened'), Js('Enraged'), Js('Executing'), Js('Expert'), Js('Extreme'), Js('Fading'), Js('Faint'), Js('Fake'), Js('Falling'), Js('False'), Js('Fatal'), Js('Fearless'), Js('Feral'), Js('Firm'), Js('First'), Js('Flawless'), Js('Flowing'), Js('Flying'), Js('Focused'), Js('Forbidden'), Js('Forsaken'), Js('Frozen'), Js('Furious'), Js('Giant'), Js('Gigantic'), Js('Gilded'), Js('Glaring'), Js('Golden'), Js('Graceful'), Js('Grand'), Js('Grave'), Js('Greater'), Js('Grim'), Js('Hallowed'), Js('Haunting'), Js('Hidden'), Js('High'), Js('Hollow'), Js('Holy'), Js('Honored'), Js('Humming'), Js('Hungry'), Js('Identical'), Js('Impending'), Js('Impossible'), Js('Impure'), Js('Infinite'), Js('Iron'), Js('Leaping'), Js('Light'), Js('Living'), Js('Lucky'), Js('Majestic'), Js('Major'), Js('Minor'), Js('Misty'), Js('Mithril'), Js('Mixed'), Js('Monstrous'), Js('Mortal'), Js('Mysterious'), Js('Nimble'), Js('Numbing'), Js('Obsidian'), Js('Parallel'), Js('Perfect'), Js('Powerful'), Js('Primal'), Js('Primary'), Js('Prime'), Js('Pristine'), Js('Puny'), Js('Pure'), Js('Quick'), Js('Quiet'), Js('Rabid'), Js('Ragged'), Js('Rapid'), Js('Raw'), Js('Reckless'), Js('Reflecting'), Js('Regal'), Js('Rotten'), Js('Rough'), Js('Royal'), Js('Sadistic'), Js('Savage'), Js('Scarlet'), Js('Scathing'), Js('Sealed'), Js('Secret'), Js('Serene'), Js('Severing'), Js('Shallow'), Js('Shameless'), Js('Shining'), Js('Shocking'), Js('Silent'), Js('Silver'), Js('Simple'), Js('Single'), Js('Skeletal'), Js('Slaying'), Js('Smooth'), Js('Sneaky'), Js('Staight'), Js('Steel'), Js('Stunning'), Js('Subtle'), Js('Super'), Js('Superior'), Js('Surging'), Js('Surprise'), Js('Swift'), Js('Thundering'), Js('Timeless'), Js('True'), Js('Twin'), Js('Unholy'), Js('Unleashed'), Js('Vacuum'), Js('Vengeful'), Js('Vicious'), Js('Vile'), Js('Violent'), Js('Violet'), Js('Warped'), Js('Weeping'), Js('Whispered'), Js('White'), Js('Wicked'), Js('Wild'), Js('Winding'), Js('Wise'), Js('Wretched')]))
var.put('nm2', Js([Js('Angel'), Js('Annihilation'), Js('Arachnid'), Js('Armageddon'), Js('Ash'), Js('Assassin'), Js('Aura'), Js('Autumn'), Js('Avalanche'), Js('Bane'), Js('Barrier'), Js('Bear'), Js('Beast'), Js('Behemoth'), Js('Bird'), Js('Blessing'), Js('Blizzard'), Js('Blood'), Js('Blossom'), Js('Body'), Js('Bomb'), Js('Bone'), Js('Boulder'), Js('Bubble'), Js('Bug'), Js('Butterfly'), Js('Camouflage'), Js('Canine'), Js('Chain'), Js('Chakra'), Js('Chaos'), Js('Claw'), Js('Clone'), Js('Cloud'), Js('Cocoon'), Js('Cold'), Js('Comet'), Js('Cosmos'), Js('Crab'), Js('Crane'), Js('Crescent'), Js('Cricket'), Js('Crystal'), Js('Darkness'), Js('Day'), Js('Daydream'), Js('Death'), Js('Deception'), Js('Delusion'), Js('Demon'), Js('Diamond'), Js('Dragon'), Js('Dragonfly'), Js('Dream'), Js('Droplet'), Js('Dust'), Js('Earth'), Js('Earthquake'), Js('Echo'), Js('Electric'), Js('Elemental'), Js('Elephant'), Js('Enigma'), Js('Execution'), Js('Exorcism'), Js('Explosion'), Js('Falcon'), Js('Fang'), Js('Feather'), Js('Feline'), Js('Fire'), Js('Flame'), Js('Frost'), Js('Frostfire'), Js('Fury'), Js('Ghost'), Js('Giant'), Js('God'), Js('Golem'), Js('Gravity'), Js('Hawk'), Js('Head'), Js('Heaven'), Js('Hell'), Js('Hellfire'), Js('Hornet'), Js('Horror'), Js('Hot'), Js('Hurricane'), Js('Ice'), Js('Illusion'), Js('Impact'), Js('Inferno'), Js('Infinity'), Js('Instant'), Js('Jaw'), Js('Judgment'), Js('Ki'), Js('Lava'), Js('Leaf'), Js('Leech'), Js('Legend'), Js('Light'), Js('Lightning'), Js('Lily'), Js('Limbo'), Js('Lion'), Js('Lotus'), Js('Magma'), Js('Mania'), Js('Maple'), Js('Melting'), Js('Meteor'), Js('Mime'), Js('Mind'), Js('Mirror'), Js('Mist'), Js('Monkey'), Js('Moon'), Js('Moonlight'), Js('Mountain'), Js('Needle'), Js('Night'), Js('Nightmare'), Js('Nova'), Js('Oak'), Js('Oracle'), Js('Palm'), Js('Panther'), Js('Paragon'), Js('Paralysis'), Js('Petal'), Js('Phantom'), Js('Phoenix'), Js('Poison'), Js('Prism'), Js('Prison'), Js('Propulsion'), Js('Puppet'), Js('Quick'), Js('Rage'), Js('Rain'), Js('Rainbow'), Js('Retribution'), Js('Reverse'), Js('River'), Js('Rock'), Js('Sand'), Js('Scorpion'), Js('Secret'), Js('Serpent'), Js('Shadow'), Js('Shark'), Js('Skeleton'), Js('Sky'), Js('Smoke'), Js('Snake'), Js('Snow'), Js('Soul'), Js('Spider'), Js('Spiral'), Js('Spirit'), Js('Spring'), Js('Starfall'), Js('Starlight'), Js('Stealth'), Js('Stone'), Js('Storm'), Js('Summer'), Js('Sun'), Js('Sunlight'), Js('Supreme'), Js('Talon'), Js('Teardrop'), Js('Terror'), Js('Thorn'), Js('Thunder'), Js('Tiger'), Js('Tornado'), Js('Toxin'), Js('Tree'), Js('Turtle'), Js('Twin'), Js('Typhoon'), Js('Vapor'), Js('Vengeance'), Js('Venom'), Js('Void'), Js('Vortex'), Js('Water'), Js('Waterfall'), Js('Whirlwind'), Js('Wild'), Js('Willow'), Js('Wind'), Js('Wing'), Js('Winter'), Js('Wolf'), Js('Yang'), Js('Yin')]))
var.put('nm3', Js([Js('Ambush'), Js('Assault'), Js('Attack'), Js('Barrage'), Js('Bash'), Js('Binding'), Js('Bite'), Js('Blade'), Js('Blast'), Js('Blitz'), Js('Blow'), Js('Bolt'), Js('Bullet'), Js('Burst'), Js('Bust'), Js('Cannon'), Js('Chain'), Js('Charge'), Js('Chop'), Js('Clap'), Js('Claw'), Js('Coil'), Js('Crack'), Js('Crush'), Js('Cut'), Js('Dance'), Js('Dive'), Js('Drain'), Js('Eruption'), Js('Fall'), Js('Fang'), Js('Fist'), Js('Fists'), Js('Flash'), Js('Flush'), Js('Force'), Js('Fracture'), Js('Hit'), Js('Hurl'), Js('Impact'), Js('Jolt'), Js('Kick'), Js('Kiss'), Js('Knock'), Js('Launch'), Js('Method'), Js('Pound'), Js('Punch'), Js('Push'), Js('Raze'), Js('Release'), Js('Rush'), Js('Seal'), Js('Shatter'), Js('Shock'), Js('Shot'), Js('Slam'), Js('Slash'), Js('Smash'), Js('Spear'), Js('Spell'), Js('Stab'), Js('Stomp'), Js('Strike'), Js('Surge'), Js('Technique'), Js('Thrust'), Js('Trap'), Js('Trash'), Js('Volley'), Js('Wave'), Js('Whip')]))
var.put('nm4', Js([Js('Admired'), Js('Adored'), Js('Advanced'), Js('Aether'), Js('Alert'), Js('Anchored'), Js('Ancient'), Js('Angelic'), Js('Arctic'), Js('Aromatic'), Js('Authentic'), Js('Autumn'), Js('Beautiful'), Js('Beloved'), Js('Bitter'), Js('Bleak'), Js('Blind'), Js('Blissful'), Js('Bold'), Js('Bright'), Js('Brilliant'), Js('Broken'), Js('Bronze'), Js('Calm'), Js('Careful'), Js('Careless'), Js('Clouded'), Js('Colossal'), Js('Common'), Js('Composed'), Js('Corrupt'), Js('Crescent'), Js('Cruel'), Js('Damaged'), Js('Dapper'), Js('Darling'), Js('Dearest'), Js('Defensive'), Js('Demise'), Js('Demonic'), Js('Dependable'), Js('Determined'), Js('Devoted'), Js('Diligent'), Js('Dual'), Js('Dutiful'), Js('Eager'), Js('Earnest'), Js('Echo'), Js('Eclipse'), Js('Elegant'), Js('Enchanted'), Js('Enigma'), Js('Esteemed'), Js('Everlasting'), Js('Evil'), Js('Exalted'), Js('False'), Js('Fatal'), Js('Fearless'), Js('Flawless'), Js('Focused'), Js('Forceful'), Js('Forsaken'), Js('Fortunate'), Js('Gentle'), Js('Giant'), Js('Gigantic'), Js('Glacier'), Js('Glorious'), Js('Golden'), Js('Graceful'), Js('Grand'), Js('Grave'), Js('Gravity'), Js('Grim'), Js('Hallowed'), Js('Harmonic'), Js('Harmonious'), Js('Haunting'), Js('Heaven'), Js('Heavenly'), Js('Hell'), Js('Hibernating'), Js('Hidden'), Js('Hollow'), Js('Honored'), Js('Horizon'), Js('Humble'), Js('Hungry'), Js('Illusion'), Js('Imitation'), Js('Immortal'), Js('Juvenile'), Js('Kings'), Js('Last'), Js('Legend'), Js('Light'), Js('Living'), Js('Lone'), Js('Lonely'), Js('Lost'), Js('Loyal'), Js('Lucky'), Js('Lunar'), Js('Majestic'), Js('Menacing'), Js('Mild'), Js('Mysterious'), Js('Nimble'), Js('Outlandish'), Js('Parallel'), Js('Parasitic'), Js('Peaceful'), Js('Perfect'), Js('Poison'), Js('Powerful'), Js('Prestigious'), Js('Prime'), Js('Prism'), Js('Prison'), Js('Proud'), Js('Quick'), Js('Quiet'), Js('Radiant'), Js('Rainbow'), Js('Regal'), Js('Royal'), Js('Secret'), Js('Serene'), Js('Shadow'), Js('Silent'), Js('Skeletal'), Js('Solar'), Js('Spiteful'), Js('Spring'), Js('Stark'), Js('Summer'), Js('Swift'), Js('Toxin'), Js('True'), Js('Twilight'), Js('Twin'), Js('Vengeful'), Js('Venom'), Js('Void'), Js('Vortex'), Js('Watchful'), Js('Weather'), Js('Wicked'), Js('Wild'), Js('Winter'), Js('Wise'), Js('Worthy'), Js('Wretched'), Js('Zealous')]))
var.put('nm5', Js([Js('Alligator'), Js('Anaconda'), Js('Angel'), Js('Ape'), Js('Armadillo'), Js('Assassin'), Js('Aura'), Js('Axe'), Js('Baboon'), Js('Badger'), Js('Bandicoot'), Js('Basilisk'), Js('Bear'), Js('Beast'), Js('Beaver'), Js('Bee'), Js('Beetle'), Js('Behemoth'), Js('Bird'), Js('Blade'), Js('Blood'), Js('Blossom'), Js('Boa'), Js('Boar'), Js('Body'), Js('Bolt'), Js('Branch'), Js('Brook'), Js('Buffalo'), Js('Bug'), Js('Butterfly'), Js('Cat'), Js('Chain'), Js('Chameleon'), Js('Chimp'), Js('Claw'), Js('Clone'), Js('Cloud'), Js('Cobra'), Js('Cocoon'), Js('Comet'), Js('Condor'), Js('Cougar'), Js('Crab'), Js('Crane'), Js('Cricket'), Js('Crocodile'), Js('Crow'), Js('Deer'), Js('Demon'), Js('Dove'), Js('Dragon'), Js('Dragonfly'), Js('Eagle'), Js('Edge'), Js('Elephant'), Js('Falcon'), Js('Fang'), Js('Feather'), Js('Firefly'), Js('Fish'), Js('Flame'), Js('Fog'), Js('Forrest'), Js('Fox'), Js('Frog'), Js('Ghost'), Js('Giant'), Js('Goat'), Js('God'), Js('Golem'), Js('Gorilla'), Js('Grass'), Js('Hare'), Js('Hawk'), Js('Head'), Js('Hippo'), Js('Hook'), Js('Hornet'), Js('Horse'), Js('Hyena'), Js('Ice'), Js('Jackal'), Js('Jaguar'), Js('Katana'), Js('Leaf'), Js('Leech'), Js('Lemur'), Js('Light'), Js('Lightning'), Js('Lily'), Js('Lizard'), Js('Locust'), Js('Lotus'), Js('Lynx'), Js('Macaw'), Js('Magpie'), Js('Mandrill'), Js('Mantis'), Js('Meteor'), Js('Mime'), Js('Mind'), Js('Mist'), Js('Monkey'), Js('Moon'), Js('Moose'), Js('Mountain'), Js('Mouse'), Js('Mushroom'), Js('Needle'), Js('Night'), Js('Nightingale'), Js('Octopus'), Js('Oracle'), Js('Panda'), Js('Panther'), Js('Paragon'), Js('Petal'), Js('Phantom'), Js('Phoenix'), Js('Puppet'), Js('Raccoon'), Js('Rain'), Js('Ram'), Js('Rat'), Js('Raven'), Js('Rhino'), Js('Rock'), Js('Root'), Js('Rose'), Js('Salamander'), Js('Scorpion'), Js('Shark'), Js('Shield'), Js('Smoke'), Js('Snake'), Js('Snow'), Js('Spear'), Js('Spider'), Js('Spirit'), Js('Star'), Js('Sun'), Js('Swallow'), Js('Swan'), Js('Sword'), Js('Tiger'), Js('Titan'), Js('Toad'), Js('Tortoise'), Js('Tree'), Js('Turtle'), Js('Viper'), Js('Vulture'), Js('Wasp'), Js('Water'), Js('Wolf'), Js('Wolverine'), Js('World')]))
var.put('nm6', Js([Js('Accelerating'), Js('Activating'), Js('Adapting'), Js('Alighting'), Js('Anticipating'), Js('Arising'), Js('Assembling'), Js('Attaching'), Js('Attacking'), Js('Balancing'), Js('Battling'), Js('Beating'), Js('Bending'), Js('Binding'), Js('Biting'), Js('Bleeding'), Js('Blessing'), Js('Blinding'), Js('Blowing'), Js('Boiling'), Js('Bolting'), Js('Bouncing'), Js('Breaking'), Js('Breathing'), Js('Burning'), Js('Bursting'), Js('Carving'), Js('Casting'), Js('Catching'), Js('Changing'), Js('Charging'), Js('Chasing'), Js('Cheating'), Js('Chopping'), Js('Clinging'), Js('Coiling'), Js('Coming'), Js('Commanding'), Js('Confusing'), Js('Constructing'), Js('Containing'), Js('Contracting'), Js('Controlling'), Js('Copying'), Js('Cracking'), Js('Crashing'), Js('Crawling'), Js('Crossing'), Js('Crushing'), Js('Crying'), Js('Curving'), Js('Cutting'), Js('Dancing'), Js('Deceiving'), Js('Destroying'), Js('Directing'), Js('Diverting'), Js('Dividing'), Js('Diving'), Js('Doubling'), Js('Draining'), Js('Dreaming'), Js('Drinking'), Js('Drowning'), Js('Drumming'), Js('Eating'), Js('Eliminating'), Js('Ending'), Js('Enduring'), Js('Enforcing'), Js('Enhancing'), Js('Escaping'), Js('Expanding'), Js('Exploding'), Js('Extending'), Js('Extracting'), Js('Fading'), Js('Fearing'), Js('Feeding'), Js('Fetching'), Js('Fighting'), Js('Firing'), Js('Flowing'), Js('Flying'), Js('Forcing'), Js('Freezing'), Js('Frightening'), Js('Frying'), Js('Glowing'), Js('Grabbing'), Js('Grinding'), Js('Gripping'), Js('Growing'), Js('Guarding'), Js('Harming'), Js('Hating'), Js('Hiding'), Js('Hovering'), Js('Hurting'), Js('Hypnotizing'), Js('Injecting'), Js('Injuring'), Js('Intensifying'), Js('Interrupting'), Js('Jesting'), Js('Judging'), Js('Kicking'), Js('Killing'), Js('Knocking'), Js('Laughing'), Js('Launching'), Js('Leaping'), Js('Living'), Js('Melting'), Js('Misleading'), Js('Mixing'), Js('Multiplying'), Js('Obeying'), Js('Overflowing'), Js('Perfecting'), Js('Pinching'), Js('Planting'), Js('Possessing'), Js('Praying'), Js('Pretending'), Js('Preying'), Js('Protecting'), Js('Punching'), Js('Puncturing'), Js('Punishing'), Js('Radiating'), Js('Raging'), Js('Raining'), Js('Reducing'), Js('Reflecting'), Js('Reigning'), Js('Releasing'), Js('Removing'), Js('Repeating'), Js('Revealing'), Js('Riding'), Js('Ruining'), Js('Ruling'), Js('Running'), Js('Rushing'), Js('Saving'), Js('Scattering'), Js('Scorching'), Js('Scratching'), Js('Screaming'), Js('Shining'), Js('Shocking'), Js('Shooting'), Js('Singing'), Js('Sinning'), Js('Slaying'), Js('Sleeping'), Js('Smashing'), Js('Smiting'), Js('Sneaking'), Js('Spinning'), Js('Splitting'), Js('Stinging'), Js('Striking'), Js('Suffering'), Js('Tearing'), Js('Thrusting'), Js('Transforming'), Js('Twisting'), Js('Vanishing'), Js('Wandering'), Js('Watching'), Js('Whirling'), Js('Whistling')]))
pass
pass


# Add lib to the module scope
animeAttacks = var.to_python()