__all__ = ['centralAfricanTowns']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nm1', 'nm11', 'nm12', 'nm4', 'nameGen', 'nm5', 'nm8', 'nm16', 'nm14', 'nm3', 'nm13', 'nm7', 'nm9', 'nm10', 'nm2', 'nm15', 'nm6'])
@Js
def PyJsHoisted_nameGen_(type, this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this, 'type':type}, var)
    var.registers(['tp', 'result', 'type'])
    var.put('tp', var.get('type'))
    var.put('result', Js([]))
    #for JS loop
    var.put('i', Js(0.0))
    while (var.get('i')<Js(16.0)):
        try:
            if (var.get('i')<Js(2.0)):
                var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm1').get('length'))))
                var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm2').get('length'))))
                var.put('names', (var.get('nm1').get(var.get('rnd'))+var.get('nm2').get(var.get('rnd2'))))
            else:
                if (var.get('i')<Js(4.0)):
                    var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length'))))
                    var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length'))))
                    var.put('names', (var.get('nm3').get(var.get('rnd'))+var.get('nm4').get(var.get('rnd2'))))
                else:
                    if (var.get('i')<Js(6.0)):
                        var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length'))))
                        var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm6').get('length'))))
                        var.put('names', (var.get('nm5').get(var.get('rnd'))+var.get('nm6').get(var.get('rnd2'))))
                    else:
                        if (var.get('i')<Js(8.0)):
                            var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm7').get('length'))))
                            var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8').get('length'))))
                            var.put('names', (var.get('nm7').get(var.get('rnd'))+var.get('nm8').get(var.get('rnd2'))))
                        else:
                            if (var.get('i')<Js(10.0)):
                                var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm9').get('length'))))
                                var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm10').get('length'))))
                                var.put('names', (var.get('nm9').get(var.get('rnd'))+var.get('nm10').get(var.get('rnd2'))))
                            else:
                                if (var.get('i')<Js(12.0)):
                                    var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm11').get('length'))))
                                    var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm12').get('length'))))
                                    var.put('names', (var.get('nm11').get(var.get('rnd'))+var.get('nm12').get(var.get('rnd2'))))
                                else:
                                    if (var.get('i')<Js(14.0)):
                                        var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm13').get('length'))))
                                        var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm14').get('length'))))
                                        var.put('names', (var.get('nm13').get(var.get('rnd'))+var.get('nm14').get(var.get('rnd2'))))
                                    else:
                                        var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm15').get('length'))))
                                        var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm16').get('length'))))
                                        var.put('names', (var.get('nm15').get(var.get('rnd'))+var.get('nm16').get(var.get('rnd2'))))
            var.get('result').callprop('push', var.get('names'))
        finally:
                (var.put('i',Js(var.get('i').to_number())+Js(1))-Js(1))
    pass
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
var.put('nm1', Js([Js('Am'), Js('An'), Js('Andu'), Js('Bai'), Js('Ba'), Js('Balo'), Js('Ben'), Js('Bi'), Js('Biba'), Js('Bim'), Js('Biu'), Js('Bun'), Js('Ca'), Js('Caba'), Js('Cabam'), Js('Cabin'), Js('Cabo'), Js('Cacon'), Js('Cacu'), Js('Cafun'), Js('Caha'), Js('Caien'), Js('Caim'), Js('Calan'), Js('Calen'), Js('Calon'), Js('Calu'), Js('Cama'), Js('Cam'), Js('Cambon'), Js('Cambun'), Js('Camis'), Js('Can'), Js('Cangam'), Js('Cangan'), Js('Cangum'), Js('Cape'), Js('Capen'), Js('Cas'), Js('Cassan'), Js('Casson'), Js('Ca'), Js('Cata'), Js('Cat'), Js('Catum'), Js('Caun'), Js('Caxi'), Js('Caza'), Js('Cazom'), Js('Ce'), Js('Chian'), Js('Chi'), Js('Chiban'), Js('Chibem'), Js('Chica'), Js('Chin'), Js('Chipin'), Js('Chis'), Js('Chitem'), Js('Coem'), Js('Co'), Js('Con'), Js('Cou'), Js('Couta'), Js('Cuan'), Js('Cua'), Js('Cu'), Js('Cui'), Js('Cuim'), Js('Cuve'), Js('Da'), Js('Dam'), Js('Didi'), Js('Di'), Js('Don'), Js('Dun'), Js('Ekun'), Js('Fol'), Js('Folga'), Js('Fun'), Js('Ga'), Js('Gabe'), Js('Gan'), Js('Golun'), Js('Gu'), Js('Huam'), Js('Hum'), Js('Jam'), Js('Kui'), Js('Lo'), Js('Lobi'), Js('Lom'), Js('Lon'), Js('Longon'), Js('Lua'), Js('Luaca'), Js('Luan'), Js('Luban'), Js('Luca'), Js('Lucus'), Js('Lue'), Js('Luia'), Js('Luim'), Js('Lum'), Js('Lu'), Js('Lumba'), Js('Lume'), Js('Lure'), Js('Luxi'), Js('Lan'), Js('Malen'), Js('Malem'), Js('Ma'), Js('Malu'), Js('Marim'), Js('Ma'), Js('Mas'), Js('Mata'), Js('Mavin'), Js('Mban'), Js('Menon'), Js('Mu'), Js('Mhcin'), Js('Mucon'), Js('Mucum'), Js('Mucu'), Js('Mugin'), Js('Mulon'), Js('Mun'), Js('Mus'), Js('Mussen'), Js('Na'), Js('Nama'), Js('Nami'), Js('Nega'), Js('Nha'), Js('No'), Js('Nza'), Js('On'), Js('Ondji'), Js('Pin'), Js('Que'), Js('Qui'), Js('Quiba'), Js('Quilen'), Js('Quima'), Js('Quiban'), Js('Quiri'), Js('Quima'), Js('Quim'), Js('Quir'), Js('Sa'), Js('Saco'), Js('Samu'), Js('Sauri'), Js('Sava'), Js('Savun'), Js('Son'), Js('So'), Js('Sum'), Js('Tchin'), Js('Tchi'), Js('Tchipe'), Js('Techa'), Js('Tenta'), Js('Tom'), Js('Tum'), Js('Uku'), Js('Via'), Js('Wa'), Js('Xangon'), Js('Xan')]))
var.put('nm2', Js([Js('ba'), Js('bal'), Js('bala'), Js('bale'), Js('bamba'), Js('bambe'), Js('bambo'), Js('banda'), Js('bango'), Js('batela'), Js('baxe'), Js('be'), Js('bela'), Js('bele'), Js('bemba'), Js('bia'), Js('binda'), Js('bito'), Js('bo'), Js('bola'), Js('boledo'), Js('bongue'), Js('briz'), Js('bua'), Js('bundi'), Js('cala'), Js('canha'), Js('cano'), Js('capa'), Js('chi'), Js('chinda'), Js('chiungo'), Js('cinga'), Js('colo'), Js('comar'), Js('combo'), Js('conda'), Js('culama'), Js('cumbo'), Js('cunda'), Js('cupa'), Js('cuso'), Js('cusse'), Js('cusso'), Js('da'), Js('dala'), Js('dimbo'), Js('do'), Js('dulo'), Js('funfo'), Js('ga'), Js('gage'), Js('gamba'), Js('gandala'), Js('gar'), Js('gares'), Js('gi'), Js('ginga'), Js('go'), Js('gongo'), Js('gonjo'), Js('gue'), Js('guela'), Js('guengo'), Js('gufo'), Js('guide'), Js('gula'), Js('gumbe'), Js('hango'), Js('heiro'), Js('je'), Js('jenje'), Js('jimbe'), Js('jiva'), Js('kuma'), Js('la'), Js('lai'), Js('lama'), Js('lanje'), Js('ledo'), Js('lembo'), Js('lengues'), Js('lo'), Js('lombo'), Js('londo'), Js('longo'), Js('ludi'), Js('lui'), Js('lulo'), Js('lundo'), Js('lungo'), Js('ma'), Js('mavongo'), Js('meje'), Js('mibe'), Js('munona'), Js('mutete'), Js('na'), Js('nongue'), Js('pata'), Js('penda'), Js('pindo'), Js('pulo'), Js('pungo'), Js('quembe'), Js('qui'), Js('rea'), Js('remo'), Js('ri'), Js('rima'), Js('rimba'), Js('rimo'), Js('riz'), Js('sa'), Js('samba'), Js('sango'), Js('sende'), Js('serra'), Js('sombo'), Js('songue'), Js('suco'), Js('sueje'), Js('ta'), Js('tada'), Js('tado'), Js('tala'), Js('tativa'), Js('teba'), Js('tela'), Js('tembo'), Js('tiva'), Js('to'), Js('vate'), Js('vinga'), Js('vongo'), Js('vungo'), Js('xilo'), Js('xita'), Js('xito'), Js('zaje'), Js('zombo')]))
var.put('nm3', Js([Js('Ako'), Js('Akono'), Js('Am'), Js('Ba'), Js('Bafa'), Js('Bafou'), Js('Bafia'), Js('Baga'), Js('Bagan'), Js('Bame'), Js('Bamen'), Js('Bami'), Js('Bamin'), Js('Ban'), Js('Bange'), Js('Batou'), Js('Be'), Js('Bela'), Js('Ber'), Js('Ca'), Js('Cam'), Js('Di'), Js('Dima'), Js('Diza'), Js('Dizan'), Js('Djou'), Js('Doua'), Js('Dscha'), Js('Ebo'), Js('Ebolo'), Js('Ede'), Js('Fou'), Js('Foum'), Js('Ga'), Js('Gou'), Js('Gui'), Js('Ide'), Js('Kae'), Js('Kou'), Js('Kous'), Js('Kousse'), Js('Kri'), Js('Kum'), Js('Ku'), Js('Li'), Js('Lim'), Js('Lo'), Js('Lom'), Js('Lou'), Js('Ma'), Js('Make'), Js('Mam'), Js('Mar'), Js('Mba'), Js('Mbal'), Js('Mban'), Js('Mbe'), Js('Mben'), Js('Mbou'), Js('Mei'), Js('Meiga'), Js('Meigan'), Js('Melo'), Js('Men'), Js('Mi'), Js('Mina'), Js('Mo'), Js('Moko'), Js('Mona'), Js('Mou'), Js('Moulou'), Js('Mu'), Js('Mute'), Js('Muten'), Js('Ndu'), Js('Ngaou'), Js('Ngaoun'), Js('Nka'), Js('Nkam'), Js('Nko'), Js('Nkong'), Js('Sang'), Js('Sa'), Js('Ti'), Js('Tiba'), Js('Wu'), Js('Yaou'), Js('Yaoun'), Js('Ya'), Js('Yo'), Js('Yoka')]))
var.put('nm4', Js([Js('ba'), Js('bam'), Js('ban'), Js('bang'), Js('bati'), Js('be'), Js('bi'), Js('bo'), Js('bong'), Js('bot'), Js('da'), Js('de'), Js('der'), Js('dere'), Js('djock'), Js('djoun'), Js('dou'), Js('douma'), Js('fe'), Js('fia'), Js('foussam'), Js('fut'), Js('ga'), Js('ganga'), Js('gangte'), Js('gem'), Js('gene'), Js('gie'), Js('goua'), Js('gwi'), Js('ji'), Js('kenene'), Js('ko'), Js('kolo'), Js('la'), Js('labo'), Js('le'), Js('li'), Js('lima'), Js('linga'), Js('lo'), Js('long'), Js('loudou'), Js('lowa'), Js('ma'), Js('mako'), Js('mayo'), Js('melima'), Js('menda'), Js('mie'), Js('mingie'), Js('nam'), Js('nau'), Js('nene'), Js('nolinga'), Js('po'), Js('ra'), Js('re'), Js('roa'), Js('roua'), Js('sam'), Js('samba'), Js('seri'), Js('tap'), Js('te'), Js('tele'), Js('ti'), Js('toua'), Js('touri'), Js('wa'), Js('yo'), Js('zangue')]))
var.put('nm5', Js([Js('Ali'), Js('Alin'), Js('Ba'), Js('Babo'), Js('Baha'), Js('Bam'), Js('Bamba'), Js('Ban'), Js('Bando'), Js('Banga'), Js('Bao'), Js('Bata'), Js('Batan'), Js('Be'), Js('Ber'), Js('Berbe'), Js('Bi'), Js('Bim'), Js('Bo'), Js('Boa'), Js('Boba'), Js('Boban'), Js('Bos'), Js('Bossan'), Js('Bossem'), Js('Bou'), Js('Boua'), Js('Bria'), Js('Ca'), Js('Car'), Js('Da'), Js('Dama'), Js('Ga'), Js('Gam'), Js('Gambou'), Js('Gue'), Js('Ip'), Js('Ka'), Js('Kaga'), Js('Ke'), Js('Kem'), Js('Koua'), Js('Kouan'), Js('Mba'), Js('Mbai'), Js('Mo'), Js('Moba'), Js('Mon'), Js('Mongou'), Js('Mongoum'), Js('Nde'), Js('No'), Js('Oua'), Js('Ouad'), Js('Ouan'), Js('Ra'), Js('Rafa'), Js('Si'), Js('Sibu'), Js('Ze'), Js('Zemi'), Js('Zi'), Js('Zin')]))
var.put('nm6', Js([Js('bangui'), Js('bari'), Js('baye'), Js('be'), Js('bele'), Js('berati'), Js('bo'), Js('boua'), Js('boula'), Js('but'), Js('ca'), Js('da'), Js('dao'), Js('doro'), Js('fai'), Js('gafo'), Js('gassou'), Js('go'), Js('goa'), Js('goumbe'), Js('gui'), Js('hamo'), Js('ki'), Js('la'), Js('le'), Js('li'), Js('lindao'), Js('mara'), Js('mio'), Js('mo'), Js('not'), Js('py'), Js('ra'), Js('rao'), Js('rati'), Js('ri'), Js('ro'), Js('sangoa'), Js('sembele'), Js('sou'), Js('tangafo'), Js('ti'), Js('ye'), Js('zoum')]))
var.put('nm7', Js([Js('Abé'), Js('Adé'), Js('Ao'), Js('Aou'), Js('Bé'), Js('Bébé'), Js('Bébo'), Js('Bén'), Js('Béno'), Js('Ba'), Js('Bar'), Js('Be'), Js('Bei'), Js('Beina'), Js('Beno'), Js('Bi'), Js('Bil'), Js('Bilti'), Js('Bit'), Js('Bo'), Js('Boko'), Js('Bon'), Js('Bou'), Js('Dja'), Js('Djeme'), Js('Do'), Js('Dour'), Js('Fa'), Js('Fia'), Js('Gaou'), Js('Gou'), Js('Goun'), Js('Gué'), Js('Guélen'), Js('Guéré'), Js('Iri'), Js('Ké'), Js('Ko'), Js('Kou'), Js('Koum'), Js('Kya'), Js('Lé'), Js('Li'), Js('Ma'), Js('Mao'), Js('Massa'), Js('Masse'), Js('Massen'), Js('Mbou'), Js('Mbour'), Js('Me'), Js('Mel'), Js('Mo'), Js('Mois'), Js('Moissa'), Js('Mon'), Js('Mou'), Js('Moun'), Js('Nga'), Js('Oua'), Js('Pa'), Js('Sa'), Js('Zoua')]))
var.put('nm8', Js([Js('bé'), Js('ba'), Js('bali'), Js('boto'), Js('ché'), Js('dé'), Js('da'), Js('dai'), Js('deng'), Js('di'), Js('dja'), Js('djer'), Js('djia'), Js('dou'), Js('fi'), Js('ga'), Js('go'), Js('gor'), Js('guet'), Js('kine'), Js('koro'), Js('kory'), Js('la'), Js('lengdeng'), Js('li'), Js('lo'), Js('ma'), Js('mar'), Js('mena'), Js('namar'), Js('ne'), Js('nia'), Js('noy'), Js('ré'), Js('réda'), Js('ra'), Js('riba'), Js('ro'), Js('ry'), Js('saguet'), Js('sala'), Js('senya'), Js('so'), Js('soro'), Js('sou'), Js('ti'), Js('tine'), Js('to'), Js('ya'), Js('zou')]))
var.put('nm9', Js([Js('Ake'), Js('Ba'), Js('Baf'), Js('Bafwa'), Js('Baga'), Js('Bak'), Js('Bala'), Js('Balam'), Js('Bam'), Js('Bana'), Js('Bandu'), Js('Bandun'), Js('Bara'), Js('Basan'), Js('Baso'), Js('Befa'), Js('Be'), Js('Biko'), Js('Bin'), Js('Boen'), Js('Boko'), Js('Bokun'), Js('Bolo'), Js('Bolom'), Js('Bomon'), Js('Bon'), Js('Bongan'), Js('Boso'), Js('Bosobo'), Js('Bud'), Js('Buka'), Js('Bulun'), Js('Bum'), Js('Bu'), Js('Busin'), Js('Bu'), Js('Butem'), Js('De'), Js('Deke'), Js('Dem'), Js('Di'), Js('Diba'), Js('Dilo'), Js('Dulun'), Js('Dum'), Js('Dumbe'), Js('Dhu'), Js('Dun'), Js('Du'), Js('Fe'), Js('Fi'), Js('Fungu'), Js('Fun'), Js('Ga'), Js('Gan'), Js('Ganda'), Js('Gba'), Js('Gbado'), Js('Ge'), Js('Geme'), Js('Go'), Js('Gun'), Js('Gwa'), Js('Idi'), Js('Idio'), Js('Ike'), Js('Ile'), Js('In'), Js('Ingen'), Js('Inki'), Js('Inon'), Js('Iru'), Js('Isa'), Js('Isan'), Js('Isi'), Js('Kaba'), Js('Kabam'), Js('Kaba'), Js('Kabe'), Js('Kabin'), Js('Kabon'), Js('Kahem'), Js('Kale'), Js('Kali'), Js('Kam'), Js('Kambo'), Js('Kami'), Js('Kampe'), Js('Kana'), Js('Kanan'), Js('Kania'), Js('Kan'), Js('Kante'), Js('Kanya'), Js('Kapan'), Js('Kasan'), Js('Kasen'), Js('Kason'), Js('Kata'), Js('Katan'), Js('Kat'), Js('Kay'), Js('Kazum'), Js('Ken'), Js('Ki'), Js('Kibom'), Js('Kik'), Js('Kim'), Js('Kin'), Js('Kunsha'), Js('Kin'), Js('Kupam'), Js('Kipu'), Js('Ki'), Js('Kirum'), Js('Kisan'), Js('Kito'), Js('Kitu'), Js('Kol'), Js('Kon'), Js('Kongo'), Js('Kun'), Js('Ku'), Js('Liben'), Js('Lika'), Js('Lisa'), Js('Lod'), Js('Lome'), Js('Lu'), Js('Lube'), Js('Lubu'), Js('Lubum'), Js('Lue'), Js('Lui'), Js('Luko'), Js('Luku'), Js('Luo'), Js('Lupa'), Js('Lupata'), Js('Lupu'), Js('Lusa'), Js('Lusam'), Js('Lwam'), Js('Maha'), Js('Malem'), Js('Man'), Js('Mangi'), Js('Mankan'), Js('Mano'), Js('Masi'), Js('Manim'), Js('Masi'), Js('Mata'), Js('Mban'), Js('Mbanda'), Js('Mban'), Js('Mbu'), Js('Mbuji'), Js('Mia'), Js('Mitwa'), Js('Mo'), Js('Moba'), Js('Mokam'), Js('Mong'), Js('Mon'), Js('Mua'), Js('Muan'), Js('Mulon'), Js('Mu'), Js('Mutsha'), Js('Mwe'), Js('Nian'), Js('nio'), Js('Nyun'), Js('Oi'), Js('Opa'), Js('Po'), Js('Popo'), Js('Pu'), Js('Pwe'), Js('Ru'), Js('Rutshu'), Js('Sa'), Js('Saka'), Js('San'), Js('Sed'), Js('Sha'), Js('Shabun'), Js('Shin'), Js('Shinko'), Js('Songo'), Js('Tshe'), Js('Tshi'), Js('Tshika'), Js('Tshilen'), Js('Tshim'), Js('Ubu'), Js('Ubun'), Js('Uvi'), Js('Vi'), Js('Wali'), Js('Walun'), Js('Wam'), Js('Wa'), Js('Yahu'), Js('Yako'), Js('Yanga'), Js('Za'), Js('Zon')]))
var.put('nm10', Js([Js('ba'), Js('baka'), Js('balo'), Js('bambare'), Js('bao'), Js('bare'), Js('bashi'), Js('baya'), Js('bayi'), Js('bayonge'), Js('befu'), Js('belenge'), Js('benge'), Js('bero'), Js('besa'), Js('beya'), Js('bi'), Js('binda'), Js('bo'), Js('bolo'), Js('bombo'), Js('bongo'), Js('bove'), Js('budi'), Js('bulu'), Js('bumbashi'), Js('bunda'), Js('bundu'), Js('butu'), Js('bwalu'), Js('cha'), Js('da'), Js('daka'), Js('dhala'), Js('diofa'), Js('do'), Js('doa'), Js('du'), Js('dundu'), Js('fale'), Js('ga'), Js('gai'), Js('gambi'), Js('gandanga'), Js('gani'), Js('gara'), Js('gata'), Js('gende'), Js('gina'), Js('go'), Js('gololo'), Js('gu'), Js('gulu'), Js('gurume'), Js('hagi'), Js('hemba'), Js('huma'), Js('ka'), Js('kabaka'), Js('kale'), Js('kama'), Js('kambo'), Js('kania'), Js('kanza'), Js('kapa'), Js('kasi'), Js('kavu'), Js('kela'), Js('kese'), Js('keti'), Js('ki'), Js('kisi'), Js('ko'), Js('kolela'), Js('kolobwe'), Js('koma'), Js('koro'), Js('koto'), Js('kula'), Js('kungu'), Js('kusu'), Js('kwa'), Js('kwit'), Js('la'), Js('lamba'), Js('lebo'), Js('lela'), Js('lemba'), Js('lemie'), Js('lenge'), Js('lima'), Js('lo'), Js('lobo'), Js('lobwe'), Js('lolo'), Js('lombo'), Js('longo'), Js('lonji'), Js('lunga'), Js('lungu'), Js('ma'), Js('mela'), Js('mena'), Js('mina'), Js('mongo'), Js('na'), Js('nana'), Js('nanga'), Js('ne'), Js('nia'), Js('niama'), Js('nimba'), Js('nongo'), Js('nono'), Js('pala'), Js('pamba'), Js('panga'), Js('pata'), Js('pene'), Js('pese'), Js('pushi'), Js('puta'), Js('raka'), Js('ri'), Js('ru'), Js('rumba'), Js('rumu'), Js('sala'), Js('sambo'), Js('sangi'), Js('sangulu'), Js('sende'), Js('senga'), Js('shasa'), Js('shatsha'), Js('shi'), Js('shie'), Js('shuru'), Js('singa'), Js('siro'), Js('sisi'), Js('sobolo'), Js('soko'), Js('songo'), Js('ta'), Js('tadi'), Js('tako'), Js('tanda'), Js('tapata'), Js('teba'), Js('tembo'), Js('to'), Js('tona'), Js('tuga'), Js('tuku'), Js('twa'), Js('twaba'), Js('vi'), Js('vira'), Js('wanga'), Js('wasende'), Js('we'), Js('wezi'), Js('wi'), Js('za'), Js('zau'), Js('zi'), Js('zu'), Js('zumba'), Js('zzo')]))
var.put('nm11', Js([Js('Ako'), Js('Ba'), Js('Bakou'), Js('Bakoum'), Js('Batoua'), Js('Be'), Js('Belin'), Js('Bi'), Js('Bita'), Js('Bo'), Js('Bon'), Js('Bongo'), Js('Co'), Js('De'), Js('Eka'), Js('Ete'), Js('Fou'), Js('Fouga'), Js('Ga'), Js('Gam'), Js('Ge'), Js('Gen'), Js('Ka'), Js('Kan'), Js('Kema'), Js('Kou'), Js('Koula'), Js('La'), Js('Lala'), Js('Lam'), Js('Lamba'), Js('Lastou'), Js('Le'), Js('Leco'), Js('Leko'), Js('Li'), Js('Loa'), Js('Loan'), Js('Ma'), Js('Mako'), Js('Mayu'), Js('Mbi'), Js('Me'), Js('Medou'), Js('Mekam'), Js('Mi'), Js('Mimo'), Js('Mimon'), Js('Min'), Js('Mit'), Js('Mo'), Js('Moa'), Js('Moan'), Js('Mou'), Js('Moui'), Js('Mouna'), Js('Nde'), Js('Nden'), Js('Ndjo'), Js('Nka'), Js('Nko'), Js('Nkola'), Js('Ntou'), Js('Ok'), Js('Okan'), Js('Oko'), Js('Okon'), Js('Om'), Js('Owe'), Js('Owen'), Js('Oye'), Js('Tchi'), Js('Tchiba'), Js('Tso'), Js('Zou')]))
var.put('nm12', Js([Js('ba'), Js('banga'), Js('barene'), Js('bo'), Js('bona'), Js('coni'), Js('da'), Js('de'), Js('dja'), Js('do'), Js('douneu'), Js('foun'), Js('ga'), Js('gamou'), Js('go'), Js('gou'), Js('kambo'), Js('kata'), Js('ke'), Js('kok'), Js('kokou'), Js('koni'), Js('kou'), Js('koumba'), Js('la'), Js('lara'), Js('labona'), Js('le'), Js('linga'), Js('ma'), Js('mo'), Js('mongo'), Js('mou'), Js('moutou'), Js('na'), Js('nana'), Js('ne'), Js('ni'), Js('nis'), Js('ra'), Js('rene'), Js('ta'), Js('tam'), Js('teke'), Js('tou'), Js('touala'), Js('voul'), Js('yem'), Js('yumba'), Js('zic')]))
var.put('nm13', Js([Js('Be'), Js('Bou'), Js('Boua'), Js('Bouan'), Js('Boukie'), Js('Boun'), Js('Bra'), Js('Dja'), Js('Djam'), Js('Do'), Js('Doli'), Js('Don'), Js('En'), Js('Enye'), Js('Etou'), Js('Etoum'), Js('Ewo'), Js('Ga'), Js('Gam'), Js('Gambo'), Js('Imp'), Js('Impfo'), Js('Impfon'), Js('Ka'), Js('Kaye'), Js('Ke'), Js('Kel'), Js('Ki'), Js('Kin'), Js('Kinda'), Js('Kindam'), Js('Kinka'), Js('Ko'), Js('Komo'), Js('Le'), Js('Leka'), Js('Loa'), Js('Loan'), Js('Loandji'), Js('Lou'), Js('Loudi'), Js('Louko'), Js('Loute'), Js('Ma'), Js('Madi'), Js('Madin'), Js('Maka'), Js('Mbi'), Js('Mbin'), Js('Mi'), Js('Min'), Js('Mindou'), Js('Mo'), Js('Mos'), Js('Mossa'), Js('Mosse'), Js('Mossen'), Js('Mou'), Js('Mouyo'), Js('Mouyon'), Js('Ngo'), Js('Nka'), Js('Nza'), Js('Ollo'), Js('Ollom'), Js('Oue'), Js('Oues'), Js('Owa'), Js('Owan'), Js('Oyo'), Js('Po'), Js('Poko'), Js('Se'), Js('Sem'), Js('Si'), Js('Sibi'), Js('Tcha'), Js('Tcham'), Js('Za'), Js('Zana')]))
var.put('nm14', Js([Js('ba'), Js('bala'), Js('bana'), Js('be'), Js('bi'), Js('binda'), Js('biti'), Js('bo'), Js('boma'), Js('da'), Js('damba'), Js('dima'), Js('dingou'), Js('dji'), Js('djo'), Js('do'), Js('douli'), Js('fondo'), Js('ga'), Js('gou'), Js('jili'), Js('ka'), Js('kabana'), Js('kala'), Js('kana'), Js('kiero'), Js('kola'), Js('kolela'), Js('koua'), Js('la'), Js('le'), Js('lela'), Js('li'), Js('lisie'), Js('lombo'), Js('ma'), Js('mono'), Js('na'), Js('naga'), Js('no'), Js('ro'), Js('sa'), Js('saka'), Js('sendjo'), Js('si'), Js('sie'), Js('so'), Js('te'), Js('tete'), Js('ti'), Js('tou'), Js('toumbi'), Js('wo'), Js('ya'), Js('yelle'), Js('yes'), Js('yondzi'), Js('zi')]))
var.put('nm15', Js([Js('Cha'), Js('Cham'), Js('Che'), Js('Chem'), Js('Chi'), Js('Chie'), Js('Chi'), Js('Chin'), Js('Cho'), Js('Gwe'), Js('Gwem'), Js('Iso'), Js('Ka'), Js('Kabo'), Js('Kabom'), Js('Kafu'), Js('Kaful'), Js('Kala'), Js('Kale'), Js('Kalo'), Js('Kalu'), Js('Kan'), Js('Kanye'), Js('Kanyem'), Js('Kao'), Js('Kappi'), Js('Kase'), Js('Kasem'), Js('Kashi'), Js('Kata'), Js('Kate'), Js('Kawa'), Js('Kawam'), Js('Kaze'), Js('Kazem'), Js('Kazu'), Js('Kazun'), Js('Lu'), Js('Luf'), Js('Lufwa'), Js('Lufwan'), Js('Luku'), Js('Lun'), Js('Ma'), Js('Make'), Js('Man'), Js('Maza'), Js('Mba'), Js('Mbe'), Js('Mbere'), Js('Mfu'), Js('Mi'), Js('Mile'), Js('Milen'), Js('Misi'), Js('Mku'), Js('Mo'), Js('Mon'), Js('Mpi'), Js('Mpo'), Js('Mporo'), Js('Mpu'), Js('Mpulu'), Js('Mum'), Js('Mu'), Js('Muyo'), Js('Muyom'), Js('Mwi'), Js('Mwini'), Js('Nche'), Js('Nchele'), Js('Ngo'), Js('Nka'), Js('Nse'), Js('Nselu'), Js('Pe'), Js('Pem'), Js('Petau'), Js('Sa'), Js('Sam'), Js('Se'), Js('Sena'), Js('Senan'), Js('Sere'), Js('Seren'), Js('Se'), Js('Seshe'), Js('Shi'), Js('Sia'), Js('Siavo'), Js('Siavon'), Js('Si'), Js('Sika'), Js('Sina'), Js('Za'), Js('Zam'), Js('Zi'), Js('Zim')]))
var.put('nm16', Js([Js('ba'), Js('bala'), Js('be'), Js('beshi'), Js('bezi'), Js('bo'), Js('bombo'), Js('bombwe'), Js('bomene'), Js('bompo'), Js('buka'), Js('bwa'), Js('dazi'), Js('diza'), Js('du'), Js('fue'), Js('fulwe'), Js('fya'), Js('gi'), Js('gula'), Js('je'), Js('ka'), Js('ke'), Js('keni'), Js('kishi'), Js('koso'), Js('kulu'), Js('labo'), Js('lene'), Js('lenge'), Js('lomo'), Js('longo'), Js('lu'), Js('lubi'), Js('luka'), Js('lunga'), Js('lungu'), Js('lushi'), Js('ma'), Js('mene'), Js('na'), Js('nanga'), Js('piri'), Js('po'), Js('renje'), Js('reshi'), Js('ri'), Js('rokoso'), Js('rundu'), Js('sali'), Js('samba'), Js('sempa'), Js('sheke'), Js('shi'), Js('sisi'), Js('soka'), Js('taba'), Js('tauke'), Js('tete'), Js('vonga'), Js('vuma'), Js('wa'), Js('wambwa'), Js('wanyama'), Js('we'), Js('yama'), Js('yembo'), Js('yingi'), Js('za'), Js('ze'), Js('zembe'), Js('zongwe')]))
pass
pass


# Add lib to the module scope
centralAfricanTowns = var.to_python()