__all__ = ['countryDescriptions']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nameGen'])
@Js
def PyJsHoisted_nameGen_(this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this}, var)
    var.registers(['names26b', 'names4', 'names15', 'random15', 'random26', 'names5', 'names27', 'names2', 'random30', 'random33b', 'random33e', 'name', 'names23', 'name7', 'names21', 'random5', 'name3', 'name6', 'random11', 'names20', 'random21', 'names28', 'random29', 'names7b', 'names26c', 'name2', 'random10', 'names14', 'names18', 'random8', 'random20', 'random33', 'random31', 'names25', 'random35', 'name4', 'random3', 'random17', 'random25', 'random6', 'names13', 'names8', 'names16', 'random27', 'names3', 'names12', 'names1', 'random34', 'random9', 'random7', 'names22', 'random4', 'random18', 'result', 'names26', 'random2', 'random12', 'random22', 'random23', 'names6', 'names10', 'random28', 'random19', 'name5', 'random1', 'names19', 'random33d', 'random13', 'names7', 'random32', 'random33c'])
    var.put('names1', Js([Js('Lessau'), Js('Ogria'), Js('Fulor'), Js('Ostax'), Js('Quvania'), Js('Emain'), Js('Athea'), Js('Udor'), Js('Zorus'), Js('Oxtrad'), Js('Ashia'), Js('Bunia'), Js('Gorus'), Js('Omen'), Js('Asharia'), Js('Osium'), Js('Covania'), Js('Toria'), Js('Cedoria'), Js('Uskium')]))
    var.put('names2', Js([Js(' large'), Js(' huge'), Js('n enormous'), Js(' vast'), Js('n immense'), Js(' little'), Js(' modest'), Js(' humble'), Js(' small'), Js(' tiny'), Js('n average-sized')]))
    var.put('names3', var.get('parseInt')(var.get('Math').callprop('floor', ((var.get('Math').callprop('random')*Js(15000000.0))+Js(1000000.0)))))
    var.put('names4', Js([Js('blood elves'), Js('dark elves'), Js('dwarves'), Js('elves'), Js('dwarves'), Js('elves'), Js('fairies'), Js('giants'), Js('gnomes'), Js('goblins'), Js('halflings'), Js('high elves'), Js('humans'), Js('humans'), Js('humans'), Js('humans'), Js('night elves'), Js('orcs'), Js('trolls'), Js('wood elves')]))
    var.put('names5', Js([Js('a bamboo forest'), Js('a calm ocean'), Js('a calm river'), Js('a calm sea'), Js('rich forests'), Js('fertile grounds'), Js('mineral rich mountains'), Js('a canal'), Js('a frozen sea'), Js('a glacier'), Js('a huge forest'), Js('a huge lake'), Js('a huge mountain'), Js('a huge ocean'), Js('a huge sea'), Js('a jungle'), Js('a large mountain'), Js('a large, frozen lake'), Js('a marsh'), Js('a mountain'), Js('a mountain range'), Js('a river'), Js('a sea'), Js('a small mountain range'), Js('a small ocean'), Js('a small sea'), Js('a stone wall'), Js('a swampland'), Js('a tall mountain range'), Js('a tropical forest'), Js('a volcano'), Js('a wide river'), Js('a wild ocean'), Js('a wild river'), Js('a wild sea'), Js('an ocean'), Js('desertland'), Js('fjords'), Js('frozen lands'), Js('frozen mountains'), Js('highlands'), Js('hills'), Js('huge cliffs'), Js('huge mountains'), Js('huge, open plains'), Js('large hills'), Js('large mountains'), Js('large rock formations'), Js('pristine beaches'), Js('rough beaches'), Js('tall mountains'), Js('wasteland'), Js('woodlands')]))
    var.put('names6', Js([Js('alchemy'), Js('animal breeding'), Js('animal training'), Js('armorsmithing'), Js('baking'), Js('beer brewing'), Js('blacksmithing'), Js('carpenting'), Js('cooking'), Js('crafting'), Js('engineering'), Js('farming'), Js('fishing'), Js('fletching'), Js('herbalism'), Js('hunting'), Js('jewelcrafting'), Js('leatherworking'), Js('medicine'), Js('mining'), Js('tailoring'), Js('thieving'), Js('trade'), Js('war'), Js('weaponsmithing'), Js('wine brewing'), Js('wood production'), Js('woodcrafting')]))
    var.put('names7', Js([Js('tundras'), Js('frozen lakes'), Js('frozen lands'), Js('deserts'), Js('sand plains'), Js('barren lands'), Js('uninhabitable mountains'), Js('uninhabitable wastelands'), Js('rock formations'), Js('wastelands'), Js('jungles'), Js('swamps'), Js('grasslands'), Js('rainforests'), Js('lakes'), Js('rivers and lakes'), Js('fertile lands'), Js('caves'), Js('flatlands'), Js('forests'), Js('hills'), Js('large hills'), Js('marshlands'), Js('mountains'), Js('open fields'), Js('rich woodlands'), Js('rivers'), Js('shallow lakes'), Js('shallow rivers'), Js('steep mountains'), Js('tall forests'), Js('tall mountains'), Js('woodlands')]))
    var.put('names7b', Js([Js('hot'), Js('cold'), Js('humid'), Js('snowy'), Js('warm'), Js('dry'), Js('wet'), Js('tropical'), Js('arctic'), Js('temperate'), Js('polar'), Js('windy'), Js('rainy'), Js('stormy'), Js('calm')]))
    var.put('names8', Js([Js('thinly spread'), Js('sparsely spread'), Js('lightly spread'), Js('freely spread'), Js('stretched'), Js('dispersed'), Js('scattered'), Js('loosely concentrated'), Js('closely concentrated'), Js('tightly concentrated'), Js('compactly concentrated'), Js('closely gathered'), Js('localized'), Js('fairly centered'), Js('congested'), Js('cramped'), Js('crowded'), Js('packed')]))
    var.put('names10', Js([Js('large settlements'), Js('large villages'), Js('big cities'), Js('huge settlements'), Js('settlements'), Js('huge towns'), Js('big settlements'), Js('cities'), Js('metropolises'), Js('megalopolises')]))
    var.put('names12', Js([Js('gorgeous'), Js('quite gorgeous'), Js('pleasant'), Js('quite pleasant'), Js('delightful'), Js('elegant'), Js('impressive'), Js('sublime'), Js('stunning'), Js('enjoyable'), Js('colorful'), Js('beautiful'), Js('quite beautiful'), Js('delicate'), Js('cheerful'), Js('lovely'), Js('friendly'), Js('depressing'), Js('dreary'), Js('dark'), Js('hideous'), Js('frightening'), Js('uninviting'), Js('unsightly'), Js('grisly'), Js('vile'), Js('wicked'), Js('wretched'), Js('fairly depressing'), Js('quite frightening'), Js('dangerous'), Js('vicious'), Js('sinister'), Js('ominous'), Js('gloomy'), Js('treacherous'), Js('dour')]))
    var.put('names13', Js([Js('gentle hills'), Js('mellow rivers'), Js('majestic mountain tops'), Js('luscious fields'), Js('green, open fields'), Js('silent mountains'), Js('cascading rivers'), Js('calm lakes'), Js('green forests'), Js('magnificent wildlife'), Js('gorgeous flower fields'), Js('scented flowers'), Js('snow-capped mountains'), Js('gorgeous farmlands'), Js('emerald forests'), Js('sapphire lakes'), Js('jade green fields'), Js('misty mountains'), Js('imposing fjords'), Js('huge waterfalls'), Js('small, hidden ponds'), Js('pink blossom forests'), Js('white blossom forests'), Js('red leaved trees'), Js('white sandy beaches'), Js('dramatic rock formations'), Js('neverending fields of green'), Js('small, playful waterfalls'), Js('dramatic mountain views'), Js('impressive architecture'), Js('relaxing hot springs'), Js('soft, foggy fields'), Js('terraced fields of green'), Js('white, snowy trees'), Js('pristine, snow covered fields'), Js('steep, magnificent mountains'), Js('astonishing aquatic wildlife'), Js('half frozen rivers'), Js('frozen lakes'), Js('imposing volcanic lava flows')]))
    var.put('names14', Js([Js('allure'), Js('appeal'), Js('attractions'), Js('beauty'), Js('brilliance'), Js('charm'), Js('delicacy'), Js('elegance'), Js('features'), Js('glory'), Js('gorgeousness'), Js('grace'), Js('hidden treasures'), Js('magnificence'), Js('majesty'), Js('richness'), Js('spectacles'), Js('splendor'), Js('treasures'), Js('wealth of beauty')]))
    var.put('names15', Js([Js('popular'), Js('famous'), Js('beloved'), Js('favored'), Js('loved'), Js('praised'), Js('a preferred destination'), Js('a sought-after destination'), Js('a famous destination'), Js('cherished'), Js('adored'), Js('embraced'), Js('revered'), Js('treasured'), Js('admired'), Js('commended'), Js('an admired destination'), Js('a cherished destination'), Js('a favored destination'), Js('a popular destination')]))
    var.put('names16', Js([Js('charitable'), Js('compassionate'), Js('courteous'), Js('friendly'), Js('generous'), Js('gentle'), Js('gracious'), Js('helpful'), Js('kind'), Js('kindhearted'), Js('loving'), Js('neighborly'), Js('polite'), Js('sociable'), Js('supportive'), Js('sympathetic'), Js('tolerant'), Js('toughtful'), Js('warm'), Js('welcoming'), Js('cold'), Js('bitter'), Js('hostile'), Js('reserved'), Js('alienating'), Js('unwelcoming'), Js('brusque'), Js('rude'), Js('unsociable'), Js('unreceptive'), Js('resentful'), Js('insensitive'), Js('malicious'), Js('spiteful'), Js('heartless'), Js('unsympathetic'), Js('selfish'), Js('rough'), Js('ill-tempered'), Js('unpleasant')]))
    var.put('names18', Js([Js('a feast'), Js('a hearty meal'), Js('a place to stay'), Js('a bright smile'), Js('cold beverages'), Js('companionship'), Js('comradery'), Js('drinks'), Js('food'), Js('food and a place to stay'), Js('fresh food'), Js('friendliness'), Js('generosity'), Js('goodwill'), Js('heartiness'), Js('hospitality'), Js('kindness'), Js('open arms'), Js('warm beverages'), Js('warm food'), Js('warmth'), Js('warmth and kindness')]))
    var.put('names19', Js([Js('advance'), Js('aid'), Js('assist'), Js('augment'), Js('bolster'), Js('boost'), Js('bring prosperity'), Js('contribute'), Js('contribute to'), Js('empower'), Js('extend'), Js('feed'), Js('fortify'), Js('further develop'), Js('further finance'), Js('help'), Js('innervate'), Js('intensify'), Js('invigorate'), Js('maintain'), Js('nourish'), Js('nurse'), Js('popularize'), Js('promote'), Js('protect'), Js('raise'), Js('reinforce'), Js('sponsor'), Js('stimulate'), Js('strengthen'), Js('subsidize'), Js('support'), Js('vitalize')]))
    var.put('names20', Js([Js('tough'), Js('flexible'), Js('loose'), Js('calm'), Js('gentle'), Js('docile'), Js('mellow'), Js('humane'), Js('pleasant'), Js('mild'), Js('moderate'), Js('firm'), Js('hard'), Js('precise'), Js('resolute'), Js('rigid'), Js('rough'), Js('stern'), Js('strict'), Js('tight')]))
    var.put('names21', Js([Js('to be expected'), Js('to be expected'), Js('fairly normal'), Js('quite normal'), Js('fairly normal'), Js('quite normal'), Js('predictable'), Js("what you'd expect"), Js('normal for their situation'), Js('expected in their circumstances')]))
    var.put('names22', Js([Js('at peace'), Js('balanced'), Js('calm'), Js('content'), Js('friendly'), Js('gentle'), Js('happy'), Js('harmonious'), Js('joyful'), Js('mellow'), Js('nonviolent'), Js('pacifistic'), Js('peace-loving'), Js('peaceful'), Js('restful'), Js('satisfied'), Js('serene'), Js('tranquil'), Js('unconcerend'), Js('untroubled')]))
    var.put('names23', Js([Js('successful crops, thanks to'), Js('a harmonious way of life, thanks to'), Js('a bountiful life, thanks to'), Js('a peaceful society, thanks to'), Js("the country's natural beauty, thanks to"), Js('their freedom, thanks to'), Js('their safety, thanks to'), Js('plenty of oportunities for stess relief, thanks to'), Js('various great entertainment sources, thanks to'), Js('the calm nature around them, thanks to'), Js('their rich lands, thanks to'), Js('great neighborly relations, thanks to'), Js('prosperous trade, thanks to'), Js('their gentle nature, thanks to'), Js('their culture, thanks to'), Js('their rich history, thanks to'), Js('their healthy lives, thanks to'), Js('long lasting peace, thanks to'), Js('their bond with nature, thanks to'), Js('their skills and powers, thanks to')]))
    var.put('names25', Js([Js('a cross dividing a background in 4 square parts'), Js('a cross dividing a background in 4 triangular parts'), Js('a cross on a background'), Js('a large star'), Js('a moon and a star on a background'), Js('a moon and two stars on a background'), Js('an important spiritual symbol'), Js('an outlined cross dividing a background in 4 square parts'), Js('an outlined cross dividing a background in 4 triangular parts'), Js('an outlined cross'), Js('five horizontal stripes'), Js('five vertical stripes'), Js('four horizontal stripes'), Js('four small crosses'), Js('four vertical stripes'), Js('one circle'), Js("the country's outline on a background"), Js('three circles'), Js('three connected cirlces'), Js('three horizontal stripes and a circle'), Js('three horizontal stripes and a triangle'), Js('three horizontal stripes'), Js('three small crosses'), Js('three vertical stripes and a cirlce'), Js('three vertical stripes and a triangle'), Js('three vertical stripes'), Js('two circles'), Js('two connected circles'), Js('two diagonally divided parts'), Js('two horizontal and 1 vertical stripe'), Js('two horizontal stripes and a cirlce'), Js('two horizontal stripes and a star'), Js('two horizontal stripes and a triangle'), Js('two horizontal stripes'), Js('two jaggedly connected parts'), Js('two small crosses'), Js('two vertical stripes and a circle'), Js('two vertical stripes and a star'), Js('two vertical stripes and a triangle'), Js('two vertical stripes')]))
    var.put('names26', Js([Js('black'), Js('blue'), Js('bronze'), Js('brown'), Js('gold'), Js('grey'), Js('orange'), Js('pink'), Js('purple'), Js('red'), Js('silver'), Js('white'), Js('yellow'), Js('dark blue'), Js('dark bronze'), Js('dark brown'), Js('dark gold'), Js('dark grey'), Js('dark orange'), Js('dark pink'), Js('dark purple'), Js('dark red'), Js('dark silver'), Js('dark yellow'), Js('light blue'), Js('light bronze'), Js('light brown'), Js('light gold'), Js('light grey'), Js('light orange'), Js('light pink'), Js('light purple'), Js('light red'), Js('light silver'), Js('light yellow')]))
    var.put('names26b', Js([Js(', black'), Js(', blue'), Js(', bronze'), Js(', brown'), Js(', gold'), Js(', grey'), Js(', orange'), Js(', pink'), Js(', purple'), Js(', red'), Js(', silver'), Js(', white'), Js(', yellow'), Js(', dark blue'), Js(', dark bronze'), Js(', dark brown'), Js(', dark gold'), Js(', dark grey'), Js(', dark orange'), Js(', dark pink'), Js(', dark purple'), Js(', dark red'), Js(', dark silver'), Js(', dark yellow'), Js(', light blue'), Js(', light bronze'), Js(', light brown'), Js(', light gold'), Js(', light grey'), Js(', light orange'), Js(', light pink'), Js(', light purple'), Js(', light red'), Js(', light silver'), Js(', light yellow'), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js(''), Js('')]))
    var.put('names26c', Js([Js(' and black'), Js(' and blue'), Js(' and bronze'), Js(' and brown'), Js(' and gold'), Js(' and grey'), Js(' and orange'), Js(' and pink'), Js(' and purple'), Js(' and red'), Js(' and silver'), Js(' and white'), Js(' and yellow'), Js(' and dark blue'), Js(' and dark bronze'), Js(' and dark brown'), Js(' and dark gold'), Js(' and dark grey'), Js(' and dark orange'), Js(' and dark pink'), Js(' and dark purple'), Js(' and dark red'), Js(' and dark silver'), Js(' and dark yellow'), Js(' and light blue'), Js(' and light bronze'), Js(' and light brown'), Js(' and light gold'), Js(' and light grey'), Js(' and light orange'), Js(' and light pink'), Js(' and light purple'), Js(' and light red'), Js(' and light silver'), Js(' and light yellow')]))
    var.put('names27', Js([Js('is a bell'), Js("is a bird's claw"), Js('is a bow'), Js('is a bow and arrow'), Js('is a castle'), Js('is a cat'), Js('is a chicken'), Js('is a crescent moon'), Js('is a dagger'), Js('is a dog'), Js('is a dragon'), Js('is a dragontooth'), Js('is a feather'), Js('is a fish'), Js('is a flower'), Js('is a hammer'), Js('is a hand'), Js('is a large star'), Js('is a lion'), Js('is a local animal'), Js('is a moon'), Js('is a mythical bird'), Js('is a rooster'), Js('is a sea monster'), Js('is a sickle'), Js('is a skull'), Js('is a snake'), Js('is a snowflake'), Js('is a spear'), Js('is a spider'), Js('is a sword'), Js('is a tree'), Js('is a twig'), Js('is a whale'), Js("is a whale's tail"), Js('is a wolf'), Js("is an anima's claw"), Js("is an animal's tail"), Js('is an arrow'), Js('is an eagle'), Js('is an important spiritual symbol'), Js('are angel wings'), Js('are animal teeth'), Js('are devil horns'), Js('is grain'), Js('are snowflakes'), Js('is the sun'), Js('are three fish'), Js('are two arrows'), Js('are two cats'), Js('are two daggers'), Js('are two dogs'), Js('are two dragonteeth'), Js('are two feathers'), Js('are two fish'), Js('are two hands'), Js('are two lions'), Js('are two ravens'), Js('are two shaking hands'), Js('are two twigs'), Js('are two wolves')]))
    var.put('names28', Js([Js('above a lake'), Js('above a river'), Js('on a circle'), Js('on a hexagon'), Js('on a pentagon'), Js('on a shield'), Js('on a square'), Js('on a triangle'), Js('on top of a hill'), Js('on top of a mountain'), Js('on top of a stripe'), Js('on top of a wave'), Js('on top of three small circles'), Js('on top of three stripes'), Js('on top of two small circles'), Js('on top of two stripes'), Js('on top of two waves'), Js('surrounded by 3 small stars'), Js('surrounded by leaves'), Js('surrounded by small stars'), Js('surrounded by smaller spiritual symbols'), Js('surrounded by stripes'), Js('surrounded by sun rays'), Js('under a key'), Js('with 2 pillars on either side'), Js('with two arrows on either side'), Js('with two keys on either side'), Js('with two shields on either side'), Js('with two smaller spiritual symbols on either side'), Js('with two swords on either side')]))
    var.put('random1', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names1').get('length')))))
    var.put('random2', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names2').get('length')))))
    if (var.get('random2')>Js(4.0)):
        var.put('names3', var.get('parseInt')(var.get('Math').callprop('floor', ((var.get('Math').callprop('random')*Js(1200000.0))+Js(100000.0)))))
    else:
        if (var.get('random2')==Js(10.0)):
            var.put('names3', var.get('parseInt')(var.get('Math').callprop('floor', ((var.get('Math').callprop('random')*Js(5000000.0))+Js(500000.0)))))
    var.put('random4', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names4').get('length')))))
    var.put('random5', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length')))))
    var.put('random6', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length')))))
    var.put('random7', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length')))))
    var.put('random8', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length')))))
    var.put('random9', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length')))))
    var.put('random10', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length')))))
    while (var.get('random9')==var.get('random10')):
        var.put('random10', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length')))))
    var.put('random11', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length')))))
    while ((var.get('random11')==var.get('random10')) or (var.get('random11')==var.get('random9'))):
        var.put('random11', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length')))))
    var.put('random12', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names7').get('length')))))
    if (var.get('random12')<Js(3.0)):
        var.put('names7b', Js([Js('cold'), Js('snowy'), Js('arctic'), Js('polar'), Js('windy'), Js('stormy'), Js('calm')]))
    else:
        if ((var.get('random12')<Js(6.0)) and (var.get('random12')>Js(2.0))):
            var.put('names7b', Js([Js('hot'), Js('warm'), Js('dry'), Js('calm')]))
        else:
            if ((var.get('random12')<Js(10.0)) and (var.get('random12')>Js(5.0))):
                var.put('names7b', Js([Js('hot'), Js('cold'), Js('humid'), Js('snowy'), Js('warm'), Js('dry'), Js('wet'), Js('arctic'), Js('temperate'), Js('polar'), Js('windy'), Js('rainy'), Js('stormy'), Js('calm')]))
            else:
                if ((var.get('random12')<Js(14.0)) and (var.get('random12')>Js(9.0))):
                    var.put('names7b', Js([Js('humid'), Js('warm'), Js('wet'), Js('tropical'), Js('rainy'), Js('stormy'), Js('calm')]))
    var.put('random3', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names7b').get('length')))))
    var.put('random13', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names8').get('length')))))
    if (var.get('random13')<Js(8.0)):
        var.put('names10', Js([Js('villages'), Js('tiny villages'), Js('small villages'), Js('small towns'), Js('tiny towns'), Js('towns'), Js('small hamlets'), Js('hamlets'), Js('small outposts'), Js('outposts'), Js('townships'), Js('small settlements'), Js('tiny settlements')]))
    var.put('random15', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names10').get('length')))))
    var.put('random17', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names12').get('length')))))
    if (var.get('random17')>Js(16.0)):
        def PyJs_LONG_0_(var=var):
            return var.put('names13', Js([Js('somber hills'), Js('wild rivers'), Js('cold, windy mountains'), Js('dreary fields'), Js('chaotic, overgrown fields'), Js('silent mountains'), Js('rushing rivers'), Js('dried up lakes'), Js('gloomy forests'), Js('aggressive wildlife'), Js('withered flower fields'), Js('prickly flowers'), Js('ice-cold mountains'), Js('forgotten farmlands'), Js('dark, gloomy forests'), Js('black lakes'), Js('dry, barren fields'), Js('dangerous mountains'), Js('collapsing fjords'), Js('destructive waterfalls'), Js('smelly, overgrown ponds'), Js('bleak, bare forests'), Js('decaying forests'), Js('ominous trees'), Js('rocky beaches'), Js('fiercy rock formations'), Js('desolate grasslands'), Js('small, deserted waterfalls'), Js('concealed mountain views'), Js('somber architecture'), Js('icy springs'), Js('depressing fields'), Js('wild, overgrown forests'), Js('black, decaying trees'), Js('icy, snow covered fields'), Js('steep, sinister mountains'), Js('creepy, aquatic wildlife'), Js('drying rivers'), Js('murky lakes'), Js('an ash spewing volcano')]))
        PyJs_LONG_0_()
        var.put('names14', Js([Js('dangers'), Js('roughness'), Js('crudeness'), Js('harshness'), Js('brusqueness'), Js('unrefinement'), Js('foulness'), Js('crudity'), Js('blankness'), Js('barrenness'), Js('sterility'), Js('aridity'), Js('bleakness'), Js('desolation'), Js('melancholia'), Js('loneliness'), Js('solitude'), Js('obscurity'), Js('misery'), Js('dysphoria')]))
        def PyJs_LONG_1_(var=var):
            return var.put('names15', Js([Js('a shunned destination'), Js('a skipped destination'), Js('an avoided destination'), Js('an evaded destination'), Js('an infamous destination'), Js('an unpopular destination'), Js('avoided'), Js('despised'), Js('dodged'), Js('evaded'), Js('ignored'), Js('infamous'), Js('neglected'), Js('notorious'), Js('rejected'), Js('scorned'), Js('shirked'), Js('shunned'), Js('unpopular'), Js('hated')]))
        PyJs_LONG_1_()
    var.put('random18', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names13').get('length')))))
    var.put('random19', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names13').get('length')))))
    var.put('random20', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names13').get('length')))))
    var.put('random21', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names14').get('length')))))
    var.put('random22', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names15').get('length')))))
    var.put('random23', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names16').get('length')))))
    if (var.get('random23')>Js(19.0)):
        var.put('names18', Js([Js('turned cheeks'), Js('avoiding eyes'), Js('greed'), Js('coldness'), Js('avoidance'), Js('resentment'), Js('animosity'), Js('irritation'), Js('annoyance'), Js('displeasure'), Js('cynicism'), Js('bitterness'), Js('turned backs'), Js('sarcasm'), Js('apathy'), Js('indifference'), Js('disintrest'), Js('disdain'), Js('nonchalance'), Js('neutrality'), Js('detachment')]))
        def PyJs_LONG_2_(var=var):
            return var.put('names19', Js([Js('block'), Js('butcher'), Js('constrain'), Js('cripple'), Js('damage'), Js('deface'), Js('disturb'), Js('further delay'), Js('further ruin'), Js('hamper'), Js('harm'), Js('hinder'), Js('hold up'), Js('inhibit'), Js('injure'), Js('interfere with'), Js('interrupt'), Js('mutilate'), Js('obstruct'), Js('pollute'), Js('prohibit'), Js('ravage'), Js('restrict'), Js('ruin'), Js('sabotage'), Js('slow down'), Js('suppress'), Js('thwart'), Js('weigh down')]))
        PyJs_LONG_2_()
    var.put('random25', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names18').get('length')))))
    var.put('random26', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names19').get('length')))))
    var.put('random27', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names20').get('length')))))
    if (var.get('random23')>Js(9.0)):
        var.put('names22', Js([Js('aggravated'), Js('agitated'), Js('angered'), Js('anquished'), Js('anxious'), Js('concerend'), Js('displeased'), Js('distressed'), Js('disturbed'), Js('frightened'), Js('hostily'), Js('irritated'), Js('restless'), Js('tormented'), Js('troubled'), Js('unbalanced'), Js('unfriendly'), Js('unsatisfied'), Js('upset'), Js('violent')]))
        def PyJs_LONG_3_(var=var):
            return var.put('names23', Js([Js('failing crops, caused by'), Js('recent wars, caused by'), Js('impending wars, caused by'), Js('ferocious wildlife, caused by'), Js('mediocre medicine, caused by'), Js('gloomy nature, caused by'), Js('questionable safety, caused by'), Js('lack of freedom, caused by'), Js('lack of food variety, caused by'), Js('spreading diseases, caused by'), Js('recent destructions, caused by'), Js('infertile lands, caused by'), Js('a decreasing population, caused by'), Js('lack of trade, caused by'), Js('traitors and spies, caused by'), Js('distressed nature and wildlife, caused by'), Js('declining neighbor relations, caused by'), Js('their unhealthy lives, caused by'), Js('a lack of skilled craftsmen, caused by'), Js('deteriorating infrastructure, caused by')]))
        PyJs_LONG_3_()
    var.put('random28', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names21').get('length')))))
    var.put('random29', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names22').get('length')))))
    var.put('random30', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names23').get('length')))))
    var.put('random31', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names24').get('length')))))
    var.put('random32', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names25').get('length')))))
    var.put('random33', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26').get('length')))))
    var.put('random33b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26b').get('length')))))
    while (var.get('random33b')==var.get('random33')):
        var.put('random33b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26b').get('length')))))
    var.put('random33c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26b').get('length')))))
    while ((var.get('random33b')==var.get('random33c')) or (var.get('random33')==var.get('random33c'))):
        var.put('random33c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26b').get('length')))))
    var.put('random33d', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26b').get('length')))))
    while (((var.get('random33d')==var.get('random33')) or (var.get('random33d')==var.get('random33b'))) or (var.get('random33d')==var.get('random33c'))):
        var.put('random33d', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26b').get('length')))))
    var.put('random33e', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26c').get('length')))))
    while ((((var.get('random33e')==var.get('random33')) or (var.get('random33e')==var.get('random33b'))) or (var.get('random33e')==var.get('random33c'))) or (var.get('random33e')==var.get('random33d'))):
        var.put('random33e', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names26c').get('length')))))
    var.put('random34', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names27').get('length')))))
    var.put('random35', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names28').get('length')))))
    var.put('name', (((((((Js('The country of ')+var.get('names1').get(var.get('random1')))+Js(' is a'))+var.get('names2').get(var.get('random2')))+Js(' country with a population of '))+var.get('names3'))+Js(' '))+var.get('names4').get(var.get('random4'))))
    def PyJs_LONG_4_(var=var):
        return (((((((((((Js('Bordered between ')+var.get('names5').get(var.get('random5')))+Js(' to the North, '))+var.get('names5').get(var.get('random6')))+Js(' to the South, '))+var.get('names5').get(var.get('random7')))+Js(' to the East and '))+var.get('names5').get(var.get('random8')))+Js(' to the West, the country of '))+var.get('names1').get(var.get('random1')))+Js(' mainly lives of '))+var.get('names6').get(var.get('random9')))
    var.put('name2', (((((PyJs_LONG_4_()+Js(', '))+var.get('names6').get(var.get('random10')))+Js(' and '))+var.get('names6').get(var.get('random11')))+Js('.')))
    def PyJs_LONG_5_(var=var):
        return ((((((((var.get('names1').get(var.get('random1'))+Js(' itself is mainly covered in '))+var.get('names7').get(var.get('random12')))+Js(' and has a '))+var.get('names7b').get(var.get('random3')))+Js(' climate, which has lead to a '))+var.get('names8').get(var.get('random13')))+Js(' population, despite the number of people, which means most of them live in '))+var.get('names10').get(var.get('random15')))
    var.put('name3', (PyJs_LONG_5_()+Js('.')))
    def PyJs_LONG_6_(var=var):
        return ((((((((((((Js("The country's landscape is ")+var.get('names12').get(var.get('random17')))+Js('; '))+var.get('names13').get(var.get('random18')))+Js(', '))+var.get('names13').get(var.get('random19')))+Js(' and '))+var.get('names13').get(var.get('random20')))+Js(' are just a sliver of the '))+var.get('names14').get(var.get('random21')))+Js(' '))+var.get('names1').get(var.get('random1')))+Js(' has to offer, which is why the country is '))
    var.put('name4', ((PyJs_LONG_6_()+var.get('names15').get(var.get('random22')))+Js(' among foreigners.')))
    var.put('name5', ((((((((Js('The people of ')+var.get('names1').get(var.get('random1')))+Js(' are '))+var.get('names16').get(var.get('random23')))+Js(' towards foreigners and tend to welcome them with '))+var.get('names18').get(var.get('random25')))+Js('. They feel foreigners could '))+var.get('names19').get(var.get('random26')))+Js(" the country's well being.")))
    var.put('name6', (((((((((((var.get('names1').get(var.get('random1'))+Js(' has '))+var.get('names20').get(var.get('random27')))+Js(' laws and law enforcement, which is '))+var.get('names21').get(var.get('random28')))+Js('. The people are '))+var.get('names22').get(var.get('random29')))+Js(' due to '))+var.get('names23').get(var.get('random30')))+Js(' '))+var.get('names24').get(var.get('random31')))+Js('.')))
    def PyJs_LONG_7_(var=var):
        return (((((((((Js("This is also reflected in the country's flag, which has ")+var.get('names25').get(var.get('random32')))+Js(' in '))+var.get('names26').get(var.get('random33')))+var.get('names26b').get(var.get('random33b')))+var.get('names26b').get(var.get('random33c')))+var.get('names26b').get(var.get('random33d')))+var.get('names26c').get(var.get('random33e')))+Js('. Their coat of arms '))+var.get('names27').get(var.get('random34')))
    var.put('name7', ((PyJs_LONG_7_()+Js(' '))+var.get('names28').get(var.get('random35'))))
    pass
    var.put('result', Js([]))
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
pass
pass


# Add lib to the module scope
countryDescriptions = var.to_python()