__all__ = ['houseDescriptions']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nameGen'])
@Js
def PyJsHoisted_nameGen_(this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this}, var)
    var.registers(['nm19', 'nm8d', 'nm1', 'nm11', 'nm24', 'rnd15', 'rnd18', 'rnd11', 'rnd19', 'rnd22', 'nm16', 'rnd8', 'name', 'nm23', 'nm10b', 'nm3', 'rnd14', 'rnd23', 'name3', 'nms10', 'rnd17', 'name6', 'nm2', 'rnd2', 'nm8a', 'br', 'name2', 'nm22', 'nm14', 'nm7', 'nm21', 'name4', 'nm15', 'nm20', 'rnd21', 'rnd5', 'nm12', 'nm5', 'nm8b', 'rnd4', 'nm8c', 'rnd7', 'rnd24', 'result', 'nms8', 'nm6', 'nm8e', 'rnd6', 'rnd20', 'rnd13', 'nm4', 'rnd3', 'name5', 'nm18', 'nm10a', 'nm17', 'nm10c', 'nm13', 'nm9', 'rnd10', 'rnd16', 'rnd25', 'rnd9', 'rnd12', 'rnd1'])
    var.put('nm1', Js([Js('magnificent'), Js('cozy'), Js('warm and cozy'), Js('stylish'), Js('very elegant'), Js('gorgeous'), Js('grandiose'), Js('impressive'), Js('lavish'), Js('snug and comfortable'), Js('intimate and cozy'), Js('luxurious'), Js('posh and extravagant'), Js('nice and traditional'), Js('old, but wonderful')]))
    var.put('nm2', Js([Js('blue stones'), Js('bricks covered in render'), Js('brown bricks'), Js('brown stones'), Js('burgandy bricks'), Js('cypress wood'), Js('fir wood'), Js('grey bricks'), Js('grey stones'), Js('oak wood'), Js('poplar wood'), Js('red bricks'), Js('red pine wood'), Js('sandstone'), Js('spruce wood'), Js('tan bricks'), Js('tan stones'), Js('walnut wood'), Js('wheat colored bricks'), Js('white bricks'), Js('white cedar wood'), Js('white pine wood'), Js('white stones'), Js('wood covered in render'), Js('yellow pine wood')]))
    var.put('nm3', Js([Js('blue stone'), Js('brown brick'), Js('brown stone'), Js('burgandy brick'), Js('cypress wooden'), Js('fir wooden'), Js('grey brick'), Js('grey stone'), Js('oak wooden'), Js('poplar wooden'), Js('red brick'), Js('red pine wooden'), Js('sandstone'), Js('spruce wooden'), Js('tan brick'), Js('tan stone'), Js('marble'), Js('granite'), Js('mahogany wooden'), Js('walnut wood'), Js('white brick'), Js('white cedar wooden'), Js('white pine wooden'), Js('white stone'), Js('yellow pine wooden')]))
    var.put('nm4', Js([Js('Tall, large'), Js('Tall, wide'), Js('Short, wide'), Js('Small, rounded'), Js('Tall, rounded'), Js('Small, squared'), Js('Tall, squared'), Js('Small, rectangular'), Js('Tall, rectangular'), Js('Small, half rounded'), Js('Tall, half rounded'), Js('Small, octagon'), Js('Large, octagon'), Js('Small, triangular'), Js('Large, triangular')]))
    var.put('nm5', Js([Js('let in plenty of light'), Js('brighten up the house'), Js('add to the overall style of the house'), Js('add to the overall look of the house'), Js('allow enough light to enter the home')]))
    var.put('nm6', Js([Js('in a very symmetric way'), Js('in a mostly symmetric way'), Js('in a very asymmetric way'), Js('in a mostly asymmetric way'), Js('in a fairly symmetrical pattern'), Js('in a fairly asymmetrical pattern')]))
    var.put('nm7', Js([Js('shaped like a T'), Js('shaped like an L'), Js('shaped like a short U'), Js('shaped like a squared S'), Js('square shaped'), Js('rectangular shaped'), Js('fairly rounded in shape'), Js('shaped like a circle')]))
    var.put('nm8a', Js([Js('The two extensions are linked by a patio circling around half the house'), Js('The two extensions are linked by a covered patio circling around half the house'), Js('The two extensions are linked by glass overhanging panels circling around half the house'), Js('The two extensions are linked by wooden overhanging panels circling around half the house'), Js('The two extensions are linked by cloth sunscreens circling around half the house'), Js('The two extensions are linked by wooden sunscreens structures circling around half the house'), Js('The two extensions are linked by stylish gardens circling around half the house'), Js('The two extensions are linked by a garden path circling around half the house'), Js('The two extensions are linked by overgrown wooden overhanging panels circling around half the house'), Js('The two extensions extend into a patio reaching until the end of that side of the house'), Js('The two extensions extend into a covered patio reaching until the end of that side of the house'), Js('The two extensions extend into glass overhanging panels reaching until the end of that side of the house'), Js('The two extensions extend into wooden overhanging panels reaching until the end of that side of the house'), Js('The two extensions extend into cloth sunscreens reaching until the end of that side of the house'), Js('The two extensions extend into wooden sunscreens structures reaching until the end of that side of the house'), Js('The two extensions extend into stylish gardens reaching until the end of that side of the house'), Js('The two extensions extend into a garden path reaching until the end of that side of the house'), Js('The two extensions extend into overgrown wooden overhanging panels reaching until the end of that side of the house')]))
    var.put('nm8b', Js([Js('The extension extends into a patio circling around half the house'), Js('The extension extends into a covered patio circling around half the house'), Js('The extension extends into glass overhanging panels circling around half the house'), Js('The extension extends into wooden overhanging panels circling around half the house'), Js('The extension extends into cloth sunscreens circling around half the house'), Js('The extension extends into wooden sunscreens structures circling around half the house'), Js('The extension extends into stylish gardens circling around half the house'), Js('The extension extends into a garden path circling around half the house'), Js('The extension extends into overgrown wooden overhanging panels circling around half the house'), Js('The extension extends into a patio reaching until the end of that side of the house'), Js('The extension extends into a covered patio reaching until the end of that side of the house'), Js('The extension extends into glass overhanging panels reaching until the end of that side of the house'), Js('The extension extends into wooden overhanging panels reaching until the end of that side of the house'), Js('The extension extends into cloth sunscreens reaching until the end of that side of the house'), Js('The extension extends into wooden sunscreens structures reaching until the end of that side of the house'), Js('The extension extends into stylish gardens reaching until the end of that side of the house'), Js('The extension extends into a garden path reaching until the end of that side of the house'), Js('The extension extends into overgrown wooden overhanging panels reaching until the end of that side of the house')]))
    var.put('nm8c', Js([Js('The two extensions are linked by a patio'), Js('The two extensions are linked by a covered patio'), Js('The two extensions are linked by glass overhanging panels'), Js('The two extensions are linked by wooden overhanging panels'), Js('The two extensions are linked by cloth sunscreens'), Js('The two extensions are linked by wooden sunscreens structures'), Js('The two extensions are linked by stylish gardens'), Js('The two extensions are linked by a garden path'), Js('The two extensions are linked by overgrown wooden overhanging panels'), Js('The two extensions extend into a patio to each side'), Js('The two extensions extend into a covered patio to each side'), Js('The two extensions extend into glass overhanging panels to each side'), Js('The two extensions extend into wooden overhanging panels to each side'), Js('The two extensions extend into cloth sunscreens to each side'), Js('The two extensions extend into wooden sunscreens structures to each side'), Js('The two extensions extend into stylish gardens to each side'), Js('The two extensions extend into a garden path to each side'), Js('The two extensions extend into overgrown wooden overhanging panels to each side')]))
    var.put('nm8d', Js([Js('The two extensions extend into a patio circling around half the house'), Js('The two extensions extend into a covered patio circling around half the house'), Js('The two extensions extend into glass overhanging panels circling around half the house'), Js('The two extensions extend into wooden overhanging panels circling around half the house'), Js('The two extensions extend into cloth sunscreens circling around half the house'), Js('The two extensions extend into wooden sunscreens structures circling around half the house'), Js('The two extensions extend into stylish gardens circling around half the house'), Js('The two extensions extend into a garden path circling around half the house'), Js('The two extensions extend into overgrown wooden overhanging panels circling around half the house'), Js('The two extensions extend into a patio to each side'), Js('The two extensions extend into a covered patio to each side'), Js('The two extensions extend into glass overhanging panels to each side'), Js('The two extensions extend into wooden overhanging panels to each side'), Js('The two extensions extend into cloth sunscreens to each side'), Js('The two extensions extend into wooden sunscreens structures to each side'), Js('The two extensions extend into stylish gardens to each side'), Js('The two extensions extend into a garden path to each side'), Js('The two extensions extend into overgrown wooden overhanging panels to each side')]))
    var.put('nm8e', Js([Js('The house is half surrounded by a patio'), Js('The house is half surrounded by a covered patio'), Js('The house is half surrounded by glass overhanging panels'), Js('The house is half surrounded by wooden overhanging panels'), Js('The house is half surrounded by cloth sunscreens'), Js('The house is half surrounded by wooden sunscreens structures'), Js('The house is half surrounded by stylish gardens'), Js('The house is half surrounded by a garden path'), Js('The house is half surrounded by overgrown wooden overhanging panels'), Js('The house is fully surrounded by a patio'), Js('The house is fully surrounded by a covered patio'), Js('The house is fully surrounded by glass overhanging panels'), Js('The house is fully surrounded by wooden overhanging panels'), Js('The house is fully surrounded by cloth sunscreens'), Js('The house is fully surrounded by wooden sunscreens structures'), Js('The house is fully surrounded by stylish gardens'), Js('The house is fully surrounded by a garden path'), Js('The house is fully surrounded by overgrown wooden overhanging panels'), Js('The house is partially surrounded by a patio on two sides'), Js('The house is partially surrounded by a covered patio on two sides'), Js('The house is partially surrounded by glass overhanging panels on two sides'), Js('The house is partially surrounded by wooden overhanging panels on two sides'), Js('The house is partially surrounded by cloth sunscreens on two sides'), Js('The house is partially surrounded by wooden sunscreens structures on two sides'), Js('The house is partially surrounded by stylish gardens on two sides'), Js('The house is partially surrounded by a garden path on two sides'), Js('The house is partially surrounded by overgrown wooden overhanging panels on two sides')]))
    var.put('nm9', Js([Js('bigger than the first'), Js('smaller than the first'), Js('the same size as the first')]))
    var.put('nm10a', Js([Js('which creates a stylish overhang around the entire house'), Js('which creates a stylish overhang around half the house'), Js('which creates a stylish overhang on one side of the house'), Js('which creates a stylish overhang on two sides of the house'), Js('which creates several overhanging parts on several sides of the house'), Js('which creates several overhanging parts on one side of the house')]))
    var.put('nm10b', Js([Js('which allowed for a large balcony on one side of the house'), Js('which allowed for several small balconies on one side of the house'), Js('which allowed for several balconies on the sides of the house'), Js('which creates a layered style of look in combination with the roof'), Js('which, in combination with its placement, creates an original look'), Js('which allowed for a roof garden on one side of the house'), Js('which allowed for a roof garden on two sides of the house')]))
    var.put('nm10c', Js([Js('which has been built exactly on top of the floor below it'), Js('but part of it hangs over the edge of the floor below, creating an overhang on one side and a balcony on the other')]))
    var.put('nm11', Js([Js('follows the same style as'), Js('has a slightly different style than'), Js('has a different style than'), Js('has a very different style than'), Js('has roughly the same style as')]))
    var.put('nm12', Js([Js('high and triangular'), Js('low and triangular'), Js('high and pyramid shaped'), Js('low and pyramid shaped'), Js('flat'), Js('low and slanted to one side'), Js('high and slanted to one side'), Js('high, triangular and layered'), Js('low, triangular and layered'), Js('high, triangular, but one side is longer than the other'), Js('low, triangular, but one side is longer than the other'), Js('high and v-shaped'), Js('low and v-shaped'), Js('low and square shaped'), Js('high and square shaped'), Js('high and rounded'), Js('low and rounded')]))
    var.put('nm13', Js([Js('black ceramic tiles'), Js('black roof tiles'), Js('brown ceramic tiles'), Js('brown roof tiles'), Js('brown wood shingles'), Js('dark ceramic tiles'), Js('flat roof tiles'), Js('grey ceramic tiles'), Js('grey roof tiles'), Js('grey wood shingles'), Js('overlapping roof tiles'), Js('red ceramic tiles'), Js('red roof tiles'), Js('red wood shingles'), Js('rounded roof tiles'), Js('seagrass'), Js('slate shingles'), Js('stone slabs'), Js('wheat straw'), Js('wood shingles')]))
    var.put('nm14', Js([Js('One large chimney pokes out the center of the roof'), Js('Two large chimneys poke out the center of the roof'), Js('One large chimney sits at the side of the house'), Js('Two large chimneys sit at the side of the house'), Js('Two large chimneys sit at either side of the house'), Js('There are no chimneys'), Js('One small chimney pokes out the center of the roof'), Js('Two small chimneys poke out the center of the roof'), Js('One small chimney sits at the side of the house'), Js('Two small chimneys sit at the side of the house'), Js('Two small chimneys sit at either side of the house')]))
    var.put('nm15', Js([Js('Several large windows let in plenty of light to the rooms below the roof'), Js('Many smaller windows let in plenty of light to the rooms below the roof'), Js('Several small windows let in just enough light to the rooms below the roof'), Js('A few large windows let in just enough light to the rooms below the roof'), Js('A few round, small windows let in enough light to the rooms below the roof'), Js('Several long, thin windows let in plenty of light to the rooms below the roof'), Js('Two roof terraces let in plenty of light to the rooms below the roof'), Js('Large, skylight windows let in plenty of light to the rooms below the roof'), Js('Rows of small windows let in plenty of light to the rooms below the roof'), Js('There are no windows on the roof')]))
    var.put('nm16', Js([Js('a gorgeous garden with many hidden lights that make the garden come to life at night'), Js('a gorgeous garden, including hanging grape vines, a pagoda, a pond and many different flowers'), Js('a gorgeous garden, including various trees, bushes, flowers and a large pond'), Js('a modest garden, covered mostly in grass, a few flower patches and with a small pond'), Js('a modest garden, with mostly grass and a few small trees'), Js("a modest garden, with mostly grass, a few flower patches and a children's playground"), Js("a modest, childsafe garden covered mostly in grass and with a children's playground in the center"), Js('a tranquil garden, with various flowers, a long pond including a small waterfall and various rock formations'), Js('a well kept garden, with a grass field and flower patches at the edges of the garden'), Js('a well kept garden. Grass, flower patches and trees have been placed in a stylish way'), Js('grass, a huge tree in the center and bushes on the borders of the plot'), Js('paved ground, with a pool at the backside of the house'), Js('paved ground, with a small pond at one side and various potted plants all around the house'), Js('paved ground, with an outdoor eating and relaxing space and various potted plants'), Js('paved ground, with various party spots, like a fancy barbeque and a firepit')]))
    var.put('nm17', Js([Js('a large'), Js('a small'), Js('a modern'), Js('a huge'), Js('an average'), Js('an old-fashioned')]))
    var.put('nm18', Js([Js('two bathrooms'), Js('one large bathroom'), Js('one small bathroom'), Js('one average bathroom'), Js('one modern bathroom'), Js('two modern bathrooms'), Js('three bathrooms')]))
    var.put('nm19', Js([Js('large'), Js('cozy'), Js('small'), Js('warm'), Js('huge'), Js('fairly small'), Js('comfortable'), Js('snug'), Js('generous'), Js('spacious')]))
    var.put('nm20', Js([Js('two bedrooms'), Js('three bedrooms'), Js('four bedrooms'), Js('five bedrooms')]))
    var.put('nm21', Js([Js('a small'), Js('a large'), Js('a cozy'), Js('a snug'), Js('a spacious'), Js('a modest'), Js('a grand'), Js('a roomy')]))
    var.put('nm22', Js([Js('dining room'), Js('dining area')]))
    var.put('nm23', Js([Js(''), Js(''), Js(''), Js(''), Js(''), Js(', a lounge area'), Js(', a study'), Js(', a library'), Js(', a game room'), Js(', a bar'), Js(', a sun room'), Js(', a playroom'), Js(', a multimedia room'), Js(', an office')]))
    var.put('nm24', Js([Js('storage room'), Js('garage'), Js('basement')]))
    var.put('nms8', Js(''))
    var.put('nms10', Js(''))
    var.put('rnd1', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm1').get('length')))))
    var.put('rnd2', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm2').get('length')))))
    var.put('rnd3', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length')))))
    var.put('rnd4', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    var.put('rnd5', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    var.put('rnd6', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm6').get('length')))))
    var.put('rnd7', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm7').get('length')))))
    var.put('rnd8', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8e').get('length')))))
    if PyJsStrictEq(var.get('rnd7'),Js(0.0)):
        var.put('rnd8', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8a').get('length')))))
        var.put('nms8', var.get('nm8a').get(var.get('rnd8')))
    else:
        if PyJsStrictEq(var.get('rnd7'),Js(1.0)):
            var.put('rnd8', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8b').get('length')))))
            var.put('nms8', var.get('nm8b').get(var.get('rnd8')))
        else:
            if PyJsStrictEq(var.get('rnd7'),Js(2.0)):
                var.put('rnd8', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8c').get('length')))))
                var.put('nms8', var.get('nm8c').get(var.get('rnd8')))
            else:
                if PyJsStrictEq(var.get('rnd7'),Js(3.0)):
                    var.put('rnd8', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8d').get('length')))))
                    var.put('nms8', var.get('nm8d').get(var.get('rnd8')))
                else:
                    var.put('nms8', var.get('nm8e').get(var.get('rnd8')))
    var.put('rnd9', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm9').get('length')))))
    var.put('rnd10', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm10a').get('length')))))
    if PyJsStrictEq(var.get('rnd9'),Js(1.0)):
        var.put('rnd10', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm10b').get('length')))))
        var.put('nms10', var.get('nm10b').get(var.get('rnd10')))
    else:
        if PyJsStrictEq(var.get('rnd9'),Js(2.0)):
            var.put('rnd10', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm10c').get('length')))))
            var.put('nms10', var.get('nm10c').get(var.get('rnd10')))
        else:
            var.put('nms10', var.get('nm10a').get(var.get('rnd10')))
    var.put('rnd11', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm11').get('length')))))
    var.put('rnd12', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm12').get('length')))))
    var.put('rnd13', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm13').get('length')))))
    var.put('rnd14', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm14').get('length')))))
    var.put('rnd15', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm15').get('length')))))
    var.put('rnd16', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm16').get('length')))))
    var.put('rnd17', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm17').get('length')))))
    var.put('rnd18', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm18').get('length')))))
    var.put('rnd19', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm19').get('length')))))
    var.put('rnd20', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm20').get('length')))))
    var.put('rnd21', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm21').get('length')))))
    var.put('rnd22', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm22').get('length')))))
    var.put('rnd23', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm23').get('length')))))
    var.put('rnd24', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm24').get('length')))))
    var.put('rnd25', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm21').get('length')))))
    def PyJs_LONG_0_(var=var):
        return (((((((((((Js('From the outside this house looks ')+var.get('nm1').get(var.get('rnd1')))+Js('. It has been built with '))+var.get('nm2').get(var.get('rnd2')))+Js(' and has '))+var.get('nm3').get(var.get('rnd3')))+Js(' decorations. '))+var.get('nm4').get(var.get('rnd4')))+Js(' windows '))+var.get('nm5').get(var.get('rnd5')))+Js(' and have been added to the house '))+var.get('nm6').get(var.get('rnd6')))
    var.put('name', (PyJs_LONG_0_()+Js('.')))
    def PyJs_LONG_1_(var=var):
        return ((((((((((((Js('The house is equipped with ')+var.get('nm17').get(var.get('rnd17')))+Js(' kitchen and '))+var.get('nm18').get(var.get('rnd18')))+Js(', it also has a '))+var.get('nm19').get(var.get('rnd19')))+Js(' living room, '))+var.get('nm20').get(var.get('rnd20')))+Js(', '))+var.get('nm21').get(var.get('rnd21')))+Js(' '))+var.get('nm22').get(var.get('rnd22')))+var.get('nm23').get(var.get('rnd23')))
    var.put('name2', (((((PyJs_LONG_1_()+Js(' and '))+var.get('nm21').get(var.get('rnd25')))+Js(' '))+var.get('nm24').get(var.get('rnd24')))+Js('.')))
    var.put('name3', ((((Js('The building is ')+var.get('nm7').get(var.get('rnd7')))+Js('. '))+var.get('nms8'))+Js('.')))
    var.put('name4', ((((((Js('The second floor is ')+var.get('nm9').get(var.get('rnd9')))+Js(', '))+var.get('nms10'))+Js('. This floor '))+var.get('nm11').get(var.get('rnd11')))+Js(' the floor below.')))
    var.put('name5', ((((((((Js('The roof is ')+var.get('nm12').get(var.get('rnd12')))+Js(' and is covered with '))+var.get('nm13').get(var.get('rnd13')))+Js('. '))+var.get('nm14').get(var.get('rnd14')))+Js('. '))+var.get('nm15').get(var.get('rnd15')))+Js('.')))
    var.put('name6', ((Js('The house itself is surrounded by ')+var.get('nm16').get(var.get('rnd16')))+Js('.')))
    var.put('br', Js([]))
    #for JS loop
    var.put('i', Js(0.0))
    while (var.get('i')<Js(8.0)):
        try:
            pass
        finally:
                (var.put('i',Js(var.get('i').to_number())+Js(1))-Js(1))
    pass
    var.put('result', Js([]))
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
pass
pass


# Add lib to the module scope
houseDescriptions = var.to_python()