__all__ = ['middleEastTowns']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nm1', 'nm11', 'nm12', 'nm4', 'nameGen', 'nm5', 'nm8', 'nm14', 'nm3', 'nm13', 'nm7', 'nm9', 'nm10', 'nm2', 'nm6'])
@Js
def PyJsHoisted_nameGen_(this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this}, var)
    var.registers(['result'])
    var.put('result', Js([]))
    #for JS loop
    var.put('i', Js(0.0))
    while (var.get('i')<Js(14.0)):
        try:
            if (var.get('i')<Js(2.0)):
                var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm1').get('length'))))
                var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm2').get('length'))))
                var.put('names', (var.get('nm1').get(var.get('rnd'))+var.get('nm2').get(var.get('rnd2'))))
            else:
                if (var.get('i')<Js(4.0)):
                    var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length'))))
                    var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length'))))
                    var.put('names', (var.get('nm3').get(var.get('rnd'))+var.get('nm4').get(var.get('rnd2'))))
                else:
                    if (var.get('i')<Js(6.0)):
                        var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length'))))
                        var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm6').get('length'))))
                        var.put('names', (var.get('nm5').get(var.get('rnd'))+var.get('nm6').get(var.get('rnd2'))))
                    else:
                        if (var.get('i')<Js(8.0)):
                            var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm7').get('length'))))
                            var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8').get('length'))))
                            var.put('names', (var.get('nm7').get(var.get('rnd'))+var.get('nm8').get(var.get('rnd2'))))
                        else:
                            if (var.get('i')<Js(10.0)):
                                var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm9').get('length'))))
                                var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm10').get('length'))))
                                var.put('names', (var.get('nm9').get(var.get('rnd'))+var.get('nm10').get(var.get('rnd2'))))
                            else:
                                if (var.get('i')<Js(12.0)):
                                    var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm11').get('length'))))
                                    var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm12').get('length'))))
                                    var.put('names', (var.get('nm11').get(var.get('rnd'))+var.get('nm12').get(var.get('rnd2'))))
                                else:
                                    var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm13').get('length'))))
                                    var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm14').get('length'))))
                                    var.put('names', (var.get('nm13').get(var.get('rnd'))+var.get('nm14').get(var.get('rnd2'))))
            var.get('result').callprop('push', var.get('names'))
        finally:
                (var.put('i',Js(var.get('i').to_number())+Js(1))-Js(1))
    pass
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
var.put('nm1', Js([Js('Çaki'), Js('Çana'), Js('Çari'), Js('Çayi'), Js('Çeri'), Js('Çuku'), Js('Abdi'), Js('Abi'), Js('Aca'), Js('Ada'), Js('Aga'), Js('Agi'), Js('Agla'), Js('Ahi'), Js('Akça'), Js('Akda'), Js('Akpa'), Js('Akte'), Js('Alpa'), Js('Alti'), Js('Ata'), Js('Ava'), Js('Bade'), Js('Baga'), Js('Bahçe'), Js('Baka'), Js('Bayi'), Js('Bege'), Js('Boga'), Js('Boya'), Js('Bula'), Js('Dala'), Js('Dede'), Js('Deni'), Js('Didi'), Js('Diki'), Js('Doga'), Js('Duro'), Js('Elma'), Js('Espi'), Js('Fela'), Js('Findi'), Js('Göko'), Js('Göne'), Js('Göre'), Js('Gümü'), Js('Güze'), Js('Gele'), Js('Gere'), Js('Geyi'), Js('Haci'), Js('Hasa'), Js('Here'), Js('Huzu'), Js('Ili'), Js('Ine'), Js('Inhi'), Js('Kagi'), Js('Kala'), Js('Kama'), Js('Kara'), Js('Kaya'), Js('Kema'), Js('Keme'), Js('Kiri'), Js('Kizi'), Js('Koca'), Js('Konu'), Js('Kuma'), Js('Kusa'), Js('Lima'), Js('Mahmu'), Js('Malka'), Js('Marma'), Js('Meci'), Js('Mehme'), Js('Mursa'), Js('Nebio'), Js('Nurha'), Js('Nusa'), Js('Olu'), Js('Omu'), Js('Orha'), Js('Osma'), Js('Ova'), Js('Pasi'), Js('Paya'), Js('Paza'), Js('Peli'), Js('Pina'), Js('Pira'), Js('Sala'), Js('Samsa'), Js('Sari'), Js('Sebi'), Js('Seli'), Js('Seri'), Js('Siri'), Js('Sivri'), Js('Sogu')]))
var.put('nm2', Js([Js('çören'), Js('çoban'), Js('çulha'), Js('bagi'), Js('bey'), Js('bolu'), Js('borlu'), Js('ca'), Js('calar'), Js('celi'), Js('cevaz'), Js('dere'), Js('gaç'), Js('gbasi'), Js('gmus'), Js('gzi'), Js('hisar'), Js('ka'), Js('kapi'), Js('kaya'), Js('kent'), Js('kese'), Js('khan'), Js('kiraz'), Js('kisla'), Js('kle'), Js('kli'), Js('koca'), Js('koyun'), Js('koyunlu'), Js('ler'), Js('li'), Js('lica'), Js('lkan'), Js('llar'), Js('lpasa'), Js('luk'), Js('madeni'), Js('me'), Js('mit'), Js('mli'), Js('nözü'), Js('nüzüm'), Js('naga'), Js('nar'), Js('nbey'), Js('nbeyli'), Js('ncali'), Js('ncik'), Js('ndi'), Js('ndik'), Js('ndira'), Js('ndost'), Js('nekin'), Js('ngazi'), Js('nhisar'), Js('nkaya'), Js('nkum'), Js('nkuyu'), Js('nlik'), Js('noluk'), Js('npasa'), Js('pasa'), Js('pinari'), Js('rasi'), Js('rdi'), Js('rdir'), Js('rhan'), Js('rhisar'), Js('rlar'), Js('rly'), Js('rmuslu'), Js('rnas'), Js('rsamba'), Js('salih'), Js('san'), Js('sar'), Js('saray'), Js('si'), Js('sil'), Js('sler'), Js('sli'), Js('slu'), Js('sova'), Js('ssu'), Js('sun'), Js('talan'), Js('tlar'), Js('tlu'), Js('tpasa'), Js('ttin'), Js('turak'), Js('va'), Js('veli'), Js('yayla'), Js('yeri'), Js('yuva'), Js('züyük'), Js('zar'), Js('zdere'), Js('zkale')]))
var.put('nm3', Js([Js('Aba'), Js('Abha'), Js('Abya'), Js('Abye'), Js('Aha'), Js('Ahva'), Js('Ala'), Js('Ali'), Js('Andi'), Js('Ara'), Js('Arda'), Js('Asa'), Js('Ashke'), Js('Asta'), Js('Babo'), Js('Baha'), Js('Balo'), Js('Barda'), Js('Behba'), Js('Bija'), Js('Bona'), Js('Bora'), Js('Boru'), Js('Dara'), Js('Deyla'), Js('Dorou'), Js('Fara'), Js('Fasha'), Js('Firou'), Js('Fou'), Js('Gavri'), Js('Gena'), Js('Golba'), Js('Gona'), Js('Hama'), Js('Heri'), Js('Hida'), Js('Jale'), Js('Java'), Js('Jiro'), Js('Kahnu'), Js('Kamya'), Js('Kanga'), Js('Kasha'), Js('Kaze'), Js('Kerma'), Js('Kha'), Js('Khome'), Js('Khora'), Js('Khorra'), Js('Kila'), Js('Kosa'), Js('Latia'), Js('Lava'), Js('Maha'), Js('Mala'), Js('Manoo'), Js('Mara'), Js('Mari'), Js('Meya'), Js('Mia'), Js('Minoo'), Js('Moha'), Js('Nagha'), Js('Naha'), Js('Naja'), Js('Nata'), Js('Nazara'), Js('Nisha'), Js('Noba'), Js('Nura'), Js('Omi'), Js('Omidi'), Js('Oru'), Js('Para'), Js('Parsa'), Js('Pira'), Js('Qamsa'), Js('Qazvi'), Js('Qorve'), Js('Ramsa'), Js('Rezva'), Js('Saha'), Js('Sara'), Js('Sarda'), Js('Sarpo'), Js('Sarve'), Js('Sene'), Js('Shahi'), Js('Shahri'), Js('Shira'), Js('Taba'), Js('Taka'), Js('Tehra'), Js('Vara'), Js('Yasou'), Js('Zabo'), Js('Zahe'), Js('Zara'), Js('Zarri')]))
var.put('nm4', Js([Js('b'), Js('bad'), Js('beh'), Js('bleh'), Js('bod'), Js('chan'), Js('daj'), Js('dan'), Js('dasht'), Js('dbar'), Js('deh'), Js('doab'), Js('dsar'), Js('fabad'), Js('ft'), Js('gheh'), Js('han'), Js('hijan'), Js('hkal'), Js('hnuj'), Js('hran'), Js('hreza'), Js('hriar'), Js('hroud'), Js('j'), Js('jan'), Js('jarm'), Js('jeran'), Js('jil'), Js('ker'), Js('khs'), Js('lam'), Js('lan'), Js('lard'), Js('ldasht'), Js('le'), Js('lfa'), Js('lkhal'), Js('lmas'), Js('man'), Js('min'), Js('mleh'), Js('msar'), Js('n'), Js('nab'), Js('nabad'), Js('nd'), Js('ndaj'), Js('neh'), Js('ngan'), Js('nj'), Js('njan'), Js('nrud'), Js('nsahr'), Js('nshah'), Js('nshahr'), Js('nz'), Js('pur'), Js('qqez'), Js('r'), Js('rabad'), Js('rahan'), Js('rand'), Js('raz'), Js('rgan'), Js('rin'), Js('ris'), Js('rmagh'), Js('rman'), Js('rmuj'), Js('roft'), Js('roud'), Js('roun'), Js('rvan'), Js('rveh'), Js('s'), Js('san'), Js('sar'), Js('sh'), Js('shahr'), Js('shan'), Js('sht'), Js('shtar'), Js('sk'), Js('st'), Js('stan'), Js('star'), Js('tian'), Js('vand'), Js('var'), Js('vaz'), Js('veh'), Js('vrik'), Js('yaan'), Js('yeh'), Js('yer'), Js('zd'), Js('zeh'), Js('zmian'), Js('zvin')]))
var.put('nm5', Js([Js('Ad Da'), Js('Ad Diwa'), Js('Afa'), Js('Al Ba'), Js('Al Diwa'), Js('Al Fallu'), Js('Al Hilla'), Js('Al Iska'), Js('Al Ku'), Js('Al Miqda'), Js('Al-Fa'), Js("Al-Qa'i"), Js('Al-Qu'), Js('Al-Sha'), Js('Ama'), Js('An Na'), Js('An Nasi'), Js('An Ra'), Js('An Rama'), Js('An Ru'), Js('Arbi'), Js('As Sa'), Js('As Sama'), Js('As Sula'), Js('At Ta'), Js('Az Zu'), Js('Ba'), Js('Baby'), Js('Bai'), Js('Baiji'), Js('Bala'), Js('Baqu'), Js('Cte'), Js('Ctesi'), Js('Dahu'), Js('Diho'), Js('Diwa'), Js('Erbi'), Js('Eri'), Js('Fallu'), Js('Hadi'), Js('Hala'), Js('Haqla'), Js('Iska'), Js('Kadhi'), Js('Karba'), Js('Kha'), Js('Khana'), Js('Ki'), Js('Kirku'), Js('Laga'), Js('Mo'), Js('Mosu'), Js('Muqda'), Js('Naja'), Js('Nasi'), Js('Nasiri'), Js('Ni'), Js('Nine'), Js('Nippu'), Js('Nuzi'), Js('Qu'), Js('Rama'), Js('Sama'), Js('Sha'), Js('Sula'), Js('Sume'), Js('Tal Afa'), Js('Tal Laga'), Js('Tall Afa'), Js('Tall Diwa'), Js('Tall Fallu'), Js('Tall Hilla'), Js('Tall Iska'), Js('Tall Ka'), Js('Tall Kha'), Js('Tall Ku'), Js('Tall Miqda'), Js('Tall-Fa'), Js("Tall-Qa'i"), Js('Tall-Qu'), Js('Tall-Sha'), Js('Tel Ha'), Js('Tel Hadi'), Js('Tel Hala'), Js('Tel Iska'), Js('Tel Kadhi'), Js('Tel Karba'), Js('Tel Ke'), Js('Tel Kha'), Js('Tel Khana'), Js('Tel Ki'), Js('Tell Ra'), Js('Tell Ubai'), Js('Tikri'), Js('Umm Naja'), Js('Umm Qa'), Js('Za'), Js('Zakho'), Js('Zuba')]))
var.put('nm6', Js([Js('bah'), Js('baid'), Js('bair'), Js('bala'), Js('bayr'), Js('bil'), Js('bja'), Js('bjah'), Js('dariya'), Js('dariyah'), Js('dhimiya'), Js('din'), Js('ditha'), Js('diyah'), Js('du'), Js('far'), Js('gash'), Js('hdad'), Js('hok'), Js('huk'), Js('jaf'), Js('jah'), Js('ji'), Js('kho'), Js('krit'), Js('kuk'), Js('la'), Js('lad'), Js('lah'), Js('llah'), Js('lujah'), Js('madi'), Js('maniyah'), Js('marra'), Js('mer'), Js('mia'), Js('miya'), Js('na'), Js('nah'), Js('naqin'), Js('nawa'), Js('nbar'), Js('niyah'), Js('phon'), Js('ppe'), Js('ppur'), Js('qin'), Js('qubah'), Js('rah'), Js('riya'), Js('riyah'), Js('rkuk'), Js('rma'), Js('rnah'), Js('rra'), Js('ruk'), Js('sh'), Js('sit'), Js('siyyah'), Js('sra'), Js('srah'), Js('sul'), Js('tba'), Js('tbah'), Js('tha'), Js('thah'), Js('thana'), Js('tra'), Js('veh'), Js('wah'), Js('wja'), Js('wr'), Js('ya'), Js('yah'), Js('yala'), Js('yji'), Js('ysan'), Js('zi')]))
var.put('nm7', Js([Js('Abu'), Js('Abu Ha'), Js('Abu Hu'), Js('Abu Ka'), Js('Abu Qi'), Js('Abu Su'), Js('Abu Ti'), Js('Aga'), Js('Ako'), Js('Al-Bali'), Js('Al-Basa'), Js('Al-Fa'), Js('Al-Ha'), Js('Al-Hu'), Js('Al-Ibra'), Js('Al-Ka'), Js('Al-Kana'), Js('Al-Ma'), Js('Al-Mara'), Js('Al-Qu'), Js('Al-Tu'), Js('Al-Wa'), Js('Al-Za'), Js('Ama'), Js('Anti'), Js('Ari'), Js('Arma'), Js('As-Sa'), Js('As-Si'), Js('Ash-Sha'), Js('Aswa'), Js('Awla'), Js('Balti'), Js('Bani'), Js('Beni Ha'), Js('Beni Ma'), Js('Beni Su'), Js('Cai'), Js('Cu'), Js('Dai'), Js('Dama'), Js('Damie'), Js('Dara'), Js('Dei'), Js('Dende'), Js('Diki'), Js('Disu'), Js('El Ala'), Js('El Ari'), Js('El Ba'), Js('El Dele'), Js('El Gama'), Js('El Gha'), Js('El Kana'), Js('El Ma'), Js('El Maha'), Js('El Mata'), Js('El Mi'), Js('El Qa'), Js('El Ra'), Js('El Sa'), Js('El Thou'), Js('Eta'), Js('Fa'), Js('Fai'), Js('Ghana'), Js('Hala'), Js('Hermo'), Js('Ihna'), Js('Ismai'), Js('Juha'), Js('Kha'), Js('Khu'), Js('Ko'), Js('Magha'), Js('Malla'), Js('Manfa'), Js('Mansou'), Js('Manza'), Js('Mara'), Js('Menou'), Js('Mi'), Js('Naba'), Js('Naqa'), Js('Nou'), Js('Qaha'), Js('Qalli'), Js('Que'), Js('Ra'), Js('Riya'), Js('Safa'), Js('Sama'), Js('Saqu'), Js('Senu'), Js('She'), Js('Shi'), Js('Shibi'), Js('Shu'), Js('Shubra'), Js('Sidi'), Js('Siwa'), Js('Sumu'), Js('Taba'), Js('Tami'), Js('Zaga'), Js('Fara')]))
var.put('nm8', Js([Js('baroh'), Js('barya'), Js('bes'), Js('bin'), Js('bra'), Js('dah'), Js('dari'), Js('dfa'), Js('dh'), Js('diyah'), Js('fag'), Js('faga'), Js('fta'), Js('ghada'), Js('hag'), Js('halla'), Js('hel'), Js('himiya'), Js('hta'), Js('kh'), Js('khit'), Js('khla'), Js('lawein'), Js('lem'), Js('lia'), Js('lim'), Js('lkha'), Js('lqas'), Js('ltah'), Js('ltim'), Js('lwan'), Js('lyana'), Js('lyub'), Js('ma'), Js('malut'), Js('mein'), Js('miya'), Js('mmam'), Js('mrah'), Js('nater'), Js('nayat'), Js('nayem'), Js('ndera'), Js('nha'), Js('nhur'), Js('nieh'), Js('niyah'), Js('nnoud'), Js('nsoura'), Js('nta'), Js('nuris'), Js('nyet'), Js('nzala'), Js('qadah'), Js('qas'), Js('qf'), Js('qiya'), Js('qous'), Js('ragha'), Js('raw'), Js('rbin'), Js('reen'), Js('reya'), Js('rga'), Js('ria'), Js('rib'), Js('ris'), Js('rish'), Js('rm'), Js('rnis'), Js('roh'), Js('rqa'), Js('rrani'), Js('rshut'), Js('rut'), Js('sae'), Js('san'), Js('seir'), Js('shawai'), Js('shn'), Js('shna'), Js('shtul'), Js('siya'), Js('skur'), Js('sna'), Js('sta'), Js('suf'), Js('sus'), Js('syoun'), Js('tara'), Js('ter'), Js('tikh'), Js('wah'), Js('wai'), Js('yana'), Js('yna'), Js('youm'), Js('yum'), Js('zar'), Js('zig')]))
var.put('nm9', Js([Js('Abqa'), Js('Al Arta'), Js('Al Ba'), Js('Al Bada'), Js('Al Ha'), Js('Al Hasa'), Js('Al Ja'), Js('Al Jafe'), Js('Al Khu'), Js('Al Li'), Js('Al Ma'), Js('Al Mi'), Js('Al Na'), Js('Al Ola'), Js('Al Oyoo'), Js('Al Qu'), Js('Al Qunfu'), Js('Al Wa'), Js('Ar Ra'), Js('As Su'), Js('As Sula'), Js('Az Zai'), Js('Balju'), Js('Bare'), Js('Bi'), Js('Bura'), Js('Burai'), Js('Daha'), Js('Damma'), Js('Dawa'), Js('Dha'), Js('Dhu'), Js('Diri'), Js('Do'), Js('Doma'), Js('Duba'), Js('Duma'), Js('Fara'), Js('Gura'), Js('Ha'), Js('Haba'), Js('Hai'), Js('Harma'), Js('Hau'), Js('Hofu'), Js('Hota'), Js('Hura'), Js('Ja'), Js('Jaba'), Js('Jala'), Js('Jedda'), Js('Jiza'), Js('Juba'), Js('Kha'), Js('Kho'), Js('La'), Js('Lihya'), Js('Mastoo'), Js('Medi'), Js('Muza'), Js('Najra'), Js('Qa'), Js('Qadei'), Js('Qai'), Js('Qati'), Js('Rabi'), Js('Rafha'), Js('Riya'), Js('Ruma'), Js('Rumai'), Js('Sai'), Js('Saka'), Js('Sha'), Js('Sharu'), Js('Tabou'), Js('Tabu'), Js('Tai'), Js('Tano'), Js('Tanu'), Js('Tarou'), Js('Tha'), Js('Thadi'), Js('Thu'), Js('Thuwa'), Js('Tura'), Js('Unai'), Js('Uqa'), Js('Uqai'), Js('Uya'), Js('Uyu'), Js('Wa'), Js('Wadi'), Js('Ya'), Js('Zu')]))
var.put('nm10', Js([Js('bail'), Js('bala'), Js('balah'), Js('ban'), Js('bar'), Js('bha'), Js('bigh'), Js('buk'), Js('bwa'), Js('cca'), Js('dah'), Js('dair'), Js('dal'), Js('dameih'), Js('dayea'), Js('ddah'), Js('dina'), Js('dinah'), Js('diq'), Js('dmi'), Js('dr'), Js('fer'), Js('fji'), Js('fudhah'), Js('fuf'), Js('ha'), Js('haban'), Js('hah'), Js('hat'), Js('hran'), Js('hsa'), Js('hyan'), Js('jh'), Js('jrah'), Js('jran'), Js('kah'), Js('kaka'), Js('khwah'), Js('kkah'), Js('la'), Js('liyah'), Js('loj'), Js('mah'), Js('mailah'), Js('mam'), Js('mas'), Js('mi'), Js('mila'), Js('mim'), Js('mis'), Js('miyya'), Js('mloj'), Js('mmam'), Js('mran'), Js('nbu'), Js('ndal'), Js('nomah'), Js('nura'), Js('qaiq'), Js('qbah'), Js('qraa'), Js('qrah'), Js('raidah'), Js('rasan'), Js('rashi'), Js('rayat'), Js('reeq'), Js('reg'), Js('rija'), Js('riyah'), Js('rma'), Js('rmah'), Js('rout'), Js('rraz'), Js('sa'), Js('san'), Js('sfan'), Js('sha'), Js('sumah'), Js('tat'), Js('tgat'), Js('th'), Js('tif'), Js('tin'), Js('toorah'), Js('tt'), Js('turah'), Js('wadmi'), Js('wain'), Js('weeiyah'), Js('wf'), Js('yadh'), Js('ybah'), Js('ydah'), Js('yla'), Js('yna'), Js('ynah'), Js('yoon'), Js('yyil'), Js('zah'), Js('zan'), Js('zzan')]))
var.put('nm11', Js([Js('Abya'), Js('Ad-Da'), Js('Ad-Dahi'), Js('Ad-Di'), Js('Ade'), Js('Al-Abi'), Js('Al-Fa'), Js('Al-Faqi'), Js('Al-Gha'), Js('Al-Ghai'), Js('Al-Hu'), Js('Al-Huda'), Js('Al-Ja'), Js('Al-Jarra'), Js('Al-Kha'), Js('Al-Ki'), Js('Al-Ma'), Js('Al-Maha'), Js('Al-Manu'), Js('Al-Mara'), Js('Al-Marhi'), Js('Al-Mi'), Js('Al-Mila'), Js('Al-Mu'), Js('Al-Muka'), Js('Al-Qa'), Js('Al-Qu'), Js('Al-Quta'), Js('Al-bay'), Js('Ar-Ra'), Js('Ar-Rahi'), Js('As Sa'), Js('As-Sai'), Js('Ash Shi'), Js('At-Tu'), Js('Az-Za'), Js('Az-Zaydi'), Js('Bai'), Js('Baji'), Js('Cha'), Js('Dha'), Js('Dhi'), Js('Di'), Js('Dimna'), Js('Faqi'), Js('Gha'), Js('Ha'), Js('Haba'), Js('Hai'), Js('Hajja'), Js('Hara'), Js('Huda'), Js('Ja'), Js("Ja'a"), Js('Jarra'), Js('Ji'), Js('Kha'), Js('Lahi'), Js('Lawda'), Js("Ma'ba"), Js('Madi'), Js('Maha'), Js('Maqba'), Js('Mara'), Js('Marhi'), Js('Mari'), Js('Mila'), Js('Misra'), Js('Mo'), Js('Muka'), Js('Ni'), Js("Qa'i"), Js('Ri'), Js('Rida'), Js('Sa'), Js("Sa'da"), Js('Saha'), Js('Sai'), Js('Sali'), Js('Sana'), Js("Say'u"), Js('Sayhu'), Js('Sha'), Js('Shafa'), Js('Shi'), Js('Soco'), Js('Sufa'), Js("Ta'i"), Js('Tari'), Js('Thi'), Js('Wa'), Js('Wazi'), Js('Ya'), Js('Yari'), Js('Za'), Js('Zabi'), Js('Zaydi'), Js('Zi'), Js('Zinji')]))
var.put('nm12', Js([Js('bam'), Js('banah'), Js('bar'), Js('barut'), Js('bid'), Js('bischa'), Js('bish'), Js('bishah'), Js('blah'), Js('bs'), Js('byan'), Js('cha'), Js('da'), Js('dah'), Js('den'), Js('dir'), Js('dis'), Js('diyah'), Js('diyya'), Js('dschil'), Js('fal'), Js('far'), Js('han'), Js('har'), Js('hi'), Js('hidah'), Js('hij'), Js('hr'), Js('hwit'), Js('jibar'), Js('jjah'), Js('kalla'), Js('khah'), Js('la'), Js('layn'), Js('lif'), Js('lla'), Js('mar'), Js('mnat'), Js('mr'), Js('mran'), Js('nah'), Js('q'), Js('qban'), Js('qbanah'), Js('qih'), Js('ra'), Js('rakh'), Js('ran'), Js('rawi'), Js('rbah'), Js('rhinah'), Js('rib'), Js('rim'), Js('riyah'), Js('rut'), Js('sab'), Js('shah'), Js('shtun'), Js('srakh'), Js('taq'), Js('tra'), Js('wdar'), Js('wi'), Js('wit'), Js('wkhah'), Js('yda'), Js('ydah'), Js('yya'), Js('yyan'), Js('zm'), Js('zz')]))
var.put('nm13', Js([Js('Abo Fa'), Js('Abu Ka'), Js('Afri'), Js('Al Anna'), Js('Al Bahlu'), Js('Al Bari'), Js('Al Darba'), Js('Al Di'), Js('Al Fa'), Js('Al Ghu'), Js('Al Ha'), Js('Al Haja'), Js('Al Hami'), Js('Al Hasa'), Js('Al Kari'), Js('Al Mrie'), Js('Al Na'), Js('Al Qamsi'), Js('Al Qusa'), Js('Al Ra'), Js('Al Ruhei'), Js('Al Sala'), Js('Al Sana'), Js('Al Sisa'), Js('Al Suqa'), Js('Al Tawa'), Js('Ama'), Js('Amu'), Js('Ari'), Js('Arra'), Js('Assa'), Js('Ata'), Js('Aza'), Js('Bani'), Js('Bebi'), Js('Binni'), Js('Brou'), Js('Brumma'), Js('Burra'), Js('Busta'), Js('Dali'), Js('Dama'), Js('Dara'), Js('Dei'), Js('Dou'), Js('Duma'), Js('Dumei'), Js('Fai'), Js('Gha'), Js('Hama'), Js('Hami'), Js('Hamma'), Js('Hara'), Js('Hare'), Js('Henna'), Js('Jable'), Js('Jara'), Js('Jasse'), Js('Juna'), Js('Kafa'), Js('Khaba'), Js('Lata'), Js('Maalou'), Js('Maara'), Js('Mada'), Js('Marma'), Js('Masya'), Js('Maya'), Js('Maysa'), Js('Mha'), Js('Mishe'), Js('Mnee'), Js('Muze'), Js('Nawa'), Js('Qami'), Js('Qana'), Js('Qarda'), Js('Qata'), Js('Qudsa'), Js('Qunei'), Js('Rabi'), Js('Saasa'), Js('Sada'), Js('Saf'), Js('Saha'), Js('Salma'), Js('Sara'), Js('Sasa'), Js('Sayyi'), Js('Sha'), Js('Sibba'), Js('Sihna'), Js('Sirgha'), Js('Sura'), Js('Tali'), Js('Talka'), Js('Tartu'), Js('Yabru'), Js('Zaba'), Js('Zai'), Js('Zwei')]))
var.put('nm14', Js([Js('bea'), Js('bet'), Js('bi'), Js('bila'), Js('bk'), Js('bleh'), Js('bous'), Js('bulus'), Js('dad'), Js('dan'), Js('dani'), Js('daya'), Js('din'), Js('diyah'), Js('dmur'), Js('dmus'), Js('dsaya'), Js('ffag'), Js('fira'), Js('fita'), Js('forrah'), Js('froun'), Js('hnaya'), Js('hum'), Js('jar'), Js('kamah'), Js('khoura'), Js('kia'), Js('kish'), Js('kiyah'), Js('lakh'), Js('lbeh'), Js('liha'), Js('likiyah'), Js('lin'), Js('liyah'), Js('lkalakh'), Js('lkhad'), Js('lkrom'), Js('ma'), Js('mal'), Js('manah'), Js('marit'), Js('mas'), Js('mayn'), Js('meir'), Js('miyah'), Js('mmam'), Js('mmanet'), Js('msiyah'), Js('nawat'), Js('naynat'), Js('niyah'), Js('niyas'), Js('niyye'), Js('nnadi'), Js('nnish'), Js('qah'), Js('qaq'), Js('qib'), Js('qiyah'), Js('qqah'), Js('ra'), Js('rah'), Js('raj'), Js('rasta'), Js('rayya'), Js('rdah'), Js('rdaha'), Js('rdeh'), Js('rem'), Js('rera'), Js('rimah'), Js('rita'), Js('rke'), Js('rouz'), Js('rouzeh'), Js('rrah'), Js('rran'), Js('rraq'), Js('rwad'), Js('sab'), Js('sakah'), Js('salun'), Js('saniyah'), Js('sayr'), Js('shli'), Js('shniyah'), Js('siyah'), Js('slan'), Js('sra'), Js('ssem'), Js('sta'), Js('stan'), Js('syaf'), Js('takia'), Js('tayfah'), Js('tina'), Js('tra'), Js('wahin'), Js('wayda'), Js('wda'), Js('wrah'), Js('wrat'), Js('yadin'), Js('yah'), Js('yamayn'), Js('ykish'), Js('zah'), Js('zeh'), Js('zeraa')]))
pass
pass


# Add lib to the module scope
middleEastTowns = var.to_python()