__all__ = ['potionDescription']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nameGen'])
@Js
def PyJsHoisted_nameGen_(this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this}, var)
    var.registers(['nm19', 'name11', 'nm1', 'rnd19', 'rnd18', 'rnd5a', 'rnd5e', 'rnd11', 'rnd15', 'nm16', 'rnd8', 'name', 'name7', 'name10', 'nm3', 'rnd14', 'name3', 'rnd17', 'name6', 'nm2', 'rnd2', 'name9', 'rnd3e', 'br', 'rnd4c', 'rnd5c', 'name2', 'nm14', 'rnd3a', 'nm7', 'nm10', 'rnd3b', 'name4', 'nm15', 'nm12', 'nm5', 'rnd3d', 'rnd3c', 'rnd4d', 'rnd4e', 'rnd7', 'name8', 'rnd5b', 'rnd4b', 'result', 'nm6', 'rnd6', 'rnd4a', 'rnd13', 'nm4', 'nm8', 'name5', 'nm18', 'nm17', 'nm13', 'rnd5d', 'nm9', 'rnd10', 'rnd16', 'rnd9', 'rnd12', 'rnd1'])
    var.put('nm1', Js([Js('n accuracy'), Js('n agility'), Js('n amnesia'), Js('n anger'), Js('n apathy'), Js('n arcane enhancement'), Js('n arcane protection'), Js('n aura balancing'), Js('n awakening'), Js(' balance'), Js(' beauty'), Js(' berserker'), Js(' blinding'), Js(' bloodlust'), Js(' brutality'), Js(' camouflage'), Js(' chaos'), Js(' clairvoyance'), Js(' comforting'), Js(' concentration'), Js(' deafening'), Js(' death'), Js(' deep sleep'), Js(' deliriousness'), Js(' delusion'), Js(' depression'), Js(' desire'), Js(' disabling'), Js(' disease curing'), Js(' dmonic'), Js(' domination'), Js(' dream inducement'), Js(' dream vision'), Js(' dreamless sleeping'), Js(' dreamwalker'), Js('n eagle vision'), Js('n ecstasy'), Js('n empathy'), Js('n empowerment'), Js('n energy'), Js('n enhanced pain relief'), Js('n enhanced reflexes'), Js('n enhanced senses'), Js('n enhanced sight'), Js('n eternal sleeping'), Js('n excitement'), Js(' farsight'), Js(' feather weight'), Js(' fever'), Js(' fire protection'), Js(' fire resistance'), Js(' fixation'), Js(' flight'), Js(' focus'), Js(' foresight'), Js(' forgetfulness'), Js(' fortitude'), Js(' fortune'), Js(' free will'), Js(' frozen blood'), Js(' fury'), Js(' ghost sight'), Js(' giant growth'), Js(' gills'), Js(' growth'), Js(' hallicination'), Js(' happiness'), Js(' harmony'), Js(' haste'), Js(' healing'), Js(' health'), Js(' hidden talent'), Js(' honesty'), Js(' hunger'), Js(' hysteria'), Js('n idle mind'), Js('n immobilizing'), Js('n immortality'), Js('n immunity'), Js('n incapacitating'), Js('n increased health'), Js('n increased immunity'), Js('n insanity'), Js('n insight'), Js('n insomnia'), Js('n intellect'), Js('n intuition'), Js('n invisibility'), Js('n invulnerability'), Js('n iron skin'), Js(' jealousy'), Js(' joy'), Js(' knowledge'), Js(' light feet'), Js(' lightning speed'), Js(' love'), Js(' lucid dream'), Js(' lunacy'), Js(' lust'), Js(' madness'), Js(' manipulation'), Js(' mind alteration'), Js(' mind blanking'), Js(' mind control'), Js(' mind corrupting'), Js(' mind domination'), Js(' mind paralyzing'), Js(' mind restricting'), Js(' mind soothing'), Js(' misfortune'), Js(' night vision'), Js(' nightmare'), Js(' nightmare inducement'), Js(' pain relief'), Js(' paralyzing'), Js(' patience'), Js(' perception'), Js(' petrification'), Js(' piece of mind'), Js(' premonition'), Js(' purification'), Js(' rage'), Js(' rejuvenation'), Js(' restricting'), Js(' revelation'), Js(' reversed growth'), Js(' seduction'), Js(' serenity'), Js(' shrinking'), Js(' silence'), Js(' sleeping'), Js(' slowing'), Js(' strength'), Js(' stunning'), Js(' swiftness'), Js(' tranquillity'), Js(' transcendence'), Js(' truth'), Js(' vigor'), Js(' vision'), Js(' vision inducement'), Js(' vitality'), Js(' wisdom')]))
    var.put('nm2', Js([Js('follow the steps closely and with great attention to detail'), Js('follow the steps with absolute precision'), Js('follow the steps below, but feel free to add your own twist'), Js('stick to the recipe below as much as you can'), Js('follow the recipe reasonably close, adding your own spin if so desired'), Js('follow the recipe well, but feel free to experiment if so desired'), Js('stick to the recipe, there can be no substitutes or mistakes'), Js('follow the recipe well, but feel free to use close substitutes if required'), Js('follow the recipe with exact precision or risk an uncertain outcome'), Js('stick to the recipe, even small mistakes can lead to a different effect')]))
    var.put('nm3', Js([Js('1 batch'), Js('2 batches'), Js('3 batches'), Js('1 tablespoon'), Js('2 tablespoons'), Js('3 tablespoons'), Js('5 tablespoons'), Js('4 tablespoons'), Js('1 handful'), Js('2 handfuls'), Js('2 bits'), Js('3 bits'), Js('4 bits'), Js('5 bits'), Js('6 bits'), Js('1 heap'), Js('2 heaps'), Js('3 heaps'), Js('1 teaspoon'), Js('2 teaspoons'), Js('3 teaspoons'), Js('4 teaspoons'), Js('5 teaspoons'), Js('1 cup'), Js('2 cups'), Js('1 pinch'), Js('2 pinches'), Js('3 pinches'), Js('4 pinches'), Js('1 dash'), Js('2 dashes'), Js('3 dashes'), Js('1 sprinkle'), Js('2 sprinkles'), Js('3 sprinkles'), Js('4 sprinkles')]))
    var.put('nm4', Js([Js('Abyss'), Js('Angel'), Js('Arctic'), Js('Ash'), Js('Assassin'), Js('Autumn'), Js('Bitter'), Js('Black'), Js('Blister'), Js('Blood'), Js('Blue'), Js('Brown'), Js('Bruise'), Js('Candy'), Js('Cave'), Js('Cavern'), Js('Cinder'), Js('Cliff'), Js('Demon'), Js('Devil'), Js('Dragon'), Js('Drake'), Js('Dream'), Js('Earth'), Js('Elephant'), Js('Ember'), Js('Emerald'), Js('Fade'), Js('Fire'), Js('Flux'), Js('Forest'), Js('Golden'), Js('Hate'), Js('Hazel'), Js('Heart'), Js('Hybernation'), Js('Ice'), Js('Ivory'), Js('Jade'), Js("King's"), Js('Knettle'), Js('Knot'), Js('Lake'), Js('Love'), Js('Mage'), Js('Mammoth'), Js('Mellow'), Js('Mercy'), Js("Monk's"), Js('Moon'), Js('Mountain'), Js('Mud'), Js('Ocean'), Js('Orange'), Js('Peace'), Js('Pearl'), Js('Pygmy'), Js("Queen's"), Js('Rain'), Js('Red'), Js('River'), Js('Ruby'), Js('Sanguine'), Js('Sapphire'), Js('Sea'), Js('Shimmer'), Js('Silk'), Js('Snowy'), Js('Sorrow'), Js('Sour'), Js('Spark'), Js('Spring'), Js('Star'), Js('Stinky'), Js('Storm'), Js('Summer'), Js('Sun'), Js('Swamp'), Js('Sweet'), Js('Thorn'), Js('Thunder'), Js('Tiger'), Js('Tundra'), Js('Venom'), Js('Viper'), Js('Void'), Js('Water'), Js('White'), Js('Wild'), Js('Winter'), Js("Witch's"), Js('Wolf'), Js('Worm'), Js('Yellow')]))
    var.put('nm5', Js([Js('Angelica'), Js('Anise'), Js('Aniseed'), Js('Avens'), Js('Barberry'), Js('Bark'), Js('Basil'), Js('Bay Leaf'), Js('Blossom'), Js('Borage'), Js('Caraway'), Js('Cardamom'), Js('Cassia'), Js('Catnip'), Js('Celery'), Js('Chervil'), Js('Chicory'), Js('Chives'), Js('Cilantro'), Js('Cinnamon'), Js('Clary'), Js('Clove'), Js('Coriander'), Js('Cress'), Js('Cudweed'), Js('Culantro'), Js('Cumin'), Js('Curry Leaf'), Js('Dill'), Js('Dill Seed'), Js('Fennel'), Js('Fenugreek'), Js('Flower'), Js('Galangal'), Js('Galingale'), Js('Garlic'), Js('Ginger'), Js('Grains'), Js('Grass'), Js('Herb'), Js('Hyssop'), Js('Lavender'), Js('Leaf'), Js('Leaves'), Js('Licorice'), Js('Lovage'), Js('Mace'), Js('Mallow'), Js('Marjoram'), Js('Mint'), Js('Moss'), Js('Mustard'), Js('Nigella'), Js('Nutmeg'), Js('Oregano'), Js('Paprika'), Js('Parsley'), Js('Pepper'), Js('Peppermint'), Js('Petal'), Js('Quassia'), Js('Root'), Js('Rosemary'), Js('Rue'), Js('Safflower'), Js('Saffron'), Js('Sage'), Js('Salt'), Js('Sassafras'), Js('Savory'), Js('Seed'), Js('Shiso'), Js('Sorrel'), Js('Spearmint'), Js('Spice'), Js('Sumac'), Js('Tarragon'), Js('Thyme'), Js('Turmeric'), Js('Vanilla'), Js('Bloom'), Js('Tea Leaf'), Js('Ivy'), Js('Weed'), Js('Creeper'), Js('Vine')]))
    var.put('nm6', Js([Js('Crush'), Js('Smash'), Js('Mash'), Js('Bruise'), Js('Break'), Js('Squeeze'), Js('Pulverize'), Js('Beat'), Js('Crunch'), Js('Squash'), Js('Grind')]))
    var.put('nm7', Js([Js('with a pestle and mortar'), Js('with whatever you can find and put it in a container'), Js('with a suitable utensil and put it in a cup'), Js('in a towel with a rolling pin and put it in a cup'), Js('with your hands and put the result in a container'), Js('with whatever does the job for you and put the result in a cup'), Js("in a cup, making sure you don't break the cup as it's probably a delicate cup"), Js('in a suitable container by using your hands'), Js("until you think you've done a good job and put the result in a cup"), Js("until you're done and put it in a container"), Js("for a good few minutes or until you're bored and put it into a cup"), Js('with a suitable tool until your arms get tired. If you start to bleed, go see a doctor and start over'), Js('with your hands, or make your friend do it for you, and put it to a cup'), Js('by summoning one of your minions and having it do the work for you, make it put the result in a cup'), Js('very delicately at first, then with unleashed fury at the end. Put the result in a cup'), Js("as you'd do with your enemies and put the result in a container"), Js('and, while doing so, let go of all your stress. Put the result in a container')]))
    var.put('nm8', Js([Js('some water'), Js('a dash of water'), Js('a little bit of water'), Js('a sprinkle of liquid ice'), Js('a dash of liquid steam'), Js('an equal amount of water'), Js('a handful of water'), Js('a dash of preboiled water'), Js('some purified water'), Js('some ice, let it melt'), Js('some clean water')]))
    var.put('nm9', Js([Js('a smooth paste'), Js('a smooth-ish paste'), Js('a messy mix'), Js('a watery mixture'), Js('a cream-like paste'), Js('a lumpy paste'), Js('a lumpy cream'), Js('a thick paste'), Js("what's now basically dirty water, or tea"), Js('messy water'), Js('a jelly-like salve'), Js('a thick emulsion'), Js('a smooth emulsion'), Js('a creamy emulsion')]))
    var.put('nm10', Js([Js('one half at a time'), Js(' one quarter at a time'), Js(' a little bit at a time'), Js(' all at once'), Js(' in small amounts at a time'), Js(' in tiny amounts at a time'), Js(', first one tiny amount, then everything else'), Js(', first almost everything, then the last tiny remnants'), Js(" all at once and make sure you don't leave any remnants"), Js(' all at once. If it came in a package, recycle the package'), Js(", one half at a time until you've added three parts"), Js(', all at once, then take it out again and put it back in'), Js(', a quarter first, then a half and then a third of it')]))
    var.put('nm12', Js([Js('slowly bring it to a simmer'), Js('slowly bring it to a boil'), Js('bring it to a boil as fast as you can'), Js('let it sit there for a while, then bring it to a boil'), Js('turn up the heat, then turn on the stove and bring the mixture to a boil'), Js('gently warm up the mixture. Cuddling is an option, but the stove works better'), Js('bring it to a boil, then freeze it, then bring it to a simmer'), Js('freeze it, then let it melt and bring it to a gentle simmer'), Js('cool it down with how cool you are, then bring the mixture to a boil'), Js('let it rest for a while. Wake up the mixture and bring it to a simmer'), Js('let it steep while you do something fun, then come back and bring it to a boil'), Js('gently, very gently bring it to a simmer')]))
    var.put('nm13', Js([Js("brew overnight, or not if you're impatient"), Js('reduce until a thick syrup'), Js("simmer for a while, you've earned a break"), Js('rest overnight'), Js('reduce by half'), Js("boil until you can smell it's burned"), Js('imbue for an hour or so'), Js('simmer and steep while you take a power nap'), Js('steam for a short while'), Js('simmer until it starts to shimmer'), Js('cool down to the body temperature of a reptile'), Js('cool down until it feels slightly scalding'), Js('cool down until it has changed color'), Js('simmer until it has darkened in color'), Js('reduce until it has changed color')]))
    var.put('nm14', Js([Js('in that order'), Js('in reverse order'), Js('a half at a time of a mixture of both'), Js('a half at a time, alternating between the two'), Js('a quarter at a time of a mixture of both'), Js('a quarter at a time, alternating between the two'), Js('all at once of one, then half at a time of the other'), Js('all at once on the count of three. Yes, three shall be the number of counting'), Js('mix both together first, then add all at once'), Js('make sure to add them in the right order, from least to most volatile'), Js('add them all at once, but do it very gently'), Js("just throw it all in there, show them who's boss"), Js('gently drop them in, the less splashing the better')]))
    var.put('nm15', Js([Js('Reheat everything and let it simmer'), Js('Bring everything back to a boil, turn of the heat'), Js('Turn up the heat one last time'), Js('Gently warm up the mixture once more'), Js('Slowly, very slowly bring the mixture up to a simmer'), Js('Quickly bring everything up to a boil'), Js('Reheat what by now is a foul liquid'), Js('Gently warm the currently disgusting mixture'), Js("Reheat what's now already a quite appealing mixture"), Js("Rapidly heat the mixture until it's hot")]))
    var.put('nm16', Js([Js('cool down to room temperature'), Js('cool down and rest for an hour'), Js('rest until the mixture has a thick consistency'), Js('cool down until the mixture is thick and gloopy'), Js('rest for a short while to let everything intermingle'), Js('cool down and rest, you should probably do the same'), Js('rest for an hour, you could do something else in the meantime, like make a potion'), Js("cool down. If you touch the liquid and it burns you, it hasn't cooled down enough"), Js("rest for a while. If you're impatient you can skip this and move on"), Js("cool down, but don't let it become too cool, like 'too cool for school' cool"), Js("cool down until it's roughly as cool as the cool side of a pillow"), Js("rest while you take a power nap, maybe two since you've worked hard"), Js('rest and steep for about half an hour')]))
    var.put('nm17', Js([Js('Pour everything through a fine sieve to remove any clumps'), Js('Pour the mixture through a very fine sieve to remove impurities'), Js("Pour everything through a broad sieve. It's pointless, but looks cool,"), Js('Stir everything a final time to thoroughly mix everything'), Js("Stir the mixture a final time, if it sticks you know it's right"), Js('Stir everything one last time to make sure what you made is in fact a potion'), Js("Whisk the mixture heavily to aerate it. Stop when it's frothy"), Js('Whisk everything with a knife until you realize you look like a fool'), Js('Whisk the mixture gently to break up any potential clumps'), Js('Remove the impurities floating at the surface with a spoon'), Js('Remove the impurities at the surface and banish them to oblivion'), Js('Remove the solidified impurities floating at the surface'), Js('Take a small sip to test your potion. If your potion has a bad effect and you still took a sip you might as well drink everything'), Js("Take a small sip to test your potion. Make sure you have an antidote ready, if you don't then, well, good luck")]))
    var.put('nm18', Js([Js('Only a small sip will be needed for the potion to take effect, store leftovers in a cold place'), Js('Only a droplet is needed for the potion to take effect. If you made a lot you can store leftovers in oblivion'), Js('Only a small sip is needed for the potion to be effective, but it tastes really good so a big sip is more fun'), Js('Only a droplet is needed for the potion to work. Store leftovers in a dark, cold place. Like your heart'), Js('A good gulp is needed for the potion to work. Restraints may be needed to feed it to your victim, I mean sacrifice. No I did mean victim'), Js('A good gulp is needed for potion to be effective, but it tastes awful so maybe mix it with some honey'), Js('A good amount is needed for the potion to take effect, a bad amount would be bad'), Js('A good amount is needed for the potion to work, so make sure you use enough, but not too much'), Js("Only a droplet is needed for the potion to work. That's right, this potion is super potent, almost omnipotent. Almost"), Js("Only a small sip is needed for the potion to be effective, but when you use it on bugs it's not very effective"), Js("A lot is needed for the potion to take effect, if you didn't make enough go back to step 1"), Js("A lot is needed for the potion to work, like 'a lot' a lot. Like you need to practically bathe in it 'a lot'"), Js("A lot is needed for the potion to be effective. It's not very potent. We should probably have used different ingredients"), Js("A few sips is all that's needed for the potion to work. A few gulps will work too, but a few slurps will be too little and not very classy"), Js("Only a small amount is needed for the potion to work. If your target is small a puny amount will do. If your target is puny, a potion isn't really needed"), Js("Only a small amount is needed for the potion to work. Perhaps turn it into ice cubes for a 'special' party"), Js('A small, but very cold amount is needed for the potion to be effective. Mixing it in a milkshake could work, but be warry of brain freeze'), Js('One droplet is enough for the potion to work. Two droplets would be overkill. Three droplets would be, well, why would anybody dare use three droplets'), Js('Three droplets is all it takes for the potion to work. Three shall be the number of droplets, the number of droplets shall be three. Four shall not be the number of droplets, nor two'), Js('A lot is needed for the potion to work. About a bucket will do. If the potion is meant to kill or incapacitate something, you might as well throw the bucket itself')]))
    var.put('nm19', Js([Js('Several Snapes'), Js('Ano N. Ymous'), Js('Ariane'), Js('Babidibi'), Js('Chef-Queen Elzar'), Js('Dr.'), Js('Dr. Bunsen Honeydew, Tested on Beaker'), Js("Dr. Disaster (Name's a coincidence, I promise)"), Js('Dr. Jekyll'), Js('Dr. Pepper'), Js('Dr. Stranger'), Js("Gul'Dan"), Js("Kel'Thuzad"), Js('Merelin'), Js('Millhouse Manastorm'), Js('Miss Daisy Oopsey'), Js('Morrigan'), Js('Neloth'), Js('Nemo'), Js('Professor Farnsworth'), Js('Professor Wernstrom'), Js('Randal Flag'), Js('The Brain'), Js('The Greying Wizard'), Js('The Quarterblood Prince'), Js('The White Witcher'), Js('Tim the Enchanter'), Js('Van Helsing'), Js('Victor Frankenstein'), Js('Walter Heisenberg'), Js('Wilter Whate'), Js('Wolly Winka')]))
    var.put('rnd1', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm1').get('length')))))
    var.put('rnd2', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm2').get('length')))))
    var.put('rnd3a', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length')))))
    var.put('rnd3b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length')))))
    var.put('rnd3c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length')))))
    var.put('rnd3d', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length')))))
    var.put('rnd3e', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm3').get('length')))))
    var.put('rnd4a', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    var.put('rnd4b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    while PyJsStrictEq(var.get('rnd4b'),var.get('rnd4a')):
        var.put('rnd4b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    var.put('rnd4c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    while (PyJsStrictEq(var.get('rnd4b'),var.get('rnd4c')) or PyJsStrictEq(var.get('rnd4a'),var.get('rnd4c'))):
        var.put('rnd4c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    var.put('rnd4d', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    while ((PyJsStrictEq(var.get('rnd4d'),var.get('rnd4a')) or PyJsStrictEq(var.get('rnd4d'),var.get('rnd4b'))) or PyJsStrictEq(var.get('rnd4d'),var.get('rnd4c'))):
        var.put('rnd4d', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    var.put('rnd4e', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    while (((PyJsStrictEq(var.get('rnd4e'),var.get('rnd4a')) or PyJsStrictEq(var.get('rnd4e'),var.get('rnd4b'))) or PyJsStrictEq(var.get('rnd4e'),var.get('rnd4c'))) or PyJsStrictEq(var.get('rnd4e'),var.get('rnd4d'))):
        var.put('rnd4e', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm4').get('length')))))
    var.put('rnd5a', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    var.put('rnd5b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    while PyJsStrictEq(var.get('rnd5b'),var.get('rnd5a')):
        var.put('rnd5b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    var.put('rnd5c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    while (PyJsStrictEq(var.get('rnd5b'),var.get('rnd5c')) or PyJsStrictEq(var.get('rnd5a'),var.get('rnd5c'))):
        var.put('rnd5c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    var.put('rnd5d', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    while ((PyJsStrictEq(var.get('rnd5d'),var.get('rnd5a')) or PyJsStrictEq(var.get('rnd5d'),var.get('rnd5b'))) or PyJsStrictEq(var.get('rnd5d'),var.get('rnd5c'))):
        var.put('rnd5d', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    var.put('rnd5e', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    while (((PyJsStrictEq(var.get('rnd5e'),var.get('rnd5a')) or PyJsStrictEq(var.get('rnd5e'),var.get('rnd5b'))) or PyJsStrictEq(var.get('rnd5e'),var.get('rnd5c'))) or PyJsStrictEq(var.get('rnd5e'),var.get('rnd5d'))):
        var.put('rnd5e', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm5').get('length')))))
    var.put('rnd6', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm6').get('length')))))
    var.put('rnd7', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm7').get('length')))))
    var.put('rnd8', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm8').get('length')))))
    var.put('rnd9', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm9').get('length')))))
    var.put('rnd10', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm10').get('length')))))
    var.put('rnd11', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm11').get('length')))))
    var.put('rnd12', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm12').get('length')))))
    var.put('rnd13', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm13').get('length')))))
    var.put('rnd14', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm14').get('length')))))
    var.put('rnd15', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm15').get('length')))))
    var.put('rnd16', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm16').get('length')))))
    var.put('rnd17', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm17').get('length')))))
    var.put('rnd18', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm18').get('length')))))
    var.put('rnd19', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('nm19').get('length')))))
    var.put('name', ((((Js('To brew a')+var.get('nm1').get(var.get('rnd1')))+Js(' potion, gather the following ingredients and '))+var.get('nm2').get(var.get('rnd2')))+Js('.')))
    var.put('name2', (((((Js('- ')+var.get('nm3').get(var.get('rnd3a')))+Js(' of '))+var.get('nm4').get(var.get('rnd4a')))+Js(' '))+var.get('nm5').get(var.get('rnd5a'))))
    var.put('name3', (((((Js('- ')+var.get('nm3').get(var.get('rnd3b')))+Js(' of '))+var.get('nm4').get(var.get('rnd4b')))+Js(' '))+var.get('nm5').get(var.get('rnd5b'))))
    var.put('name4', (((((Js('- ')+var.get('nm3').get(var.get('rnd3c')))+Js(' of '))+var.get('nm4').get(var.get('rnd4c')))+Js(' '))+var.get('nm5').get(var.get('rnd5c'))))
    var.put('name5', (((((Js('- ')+var.get('nm3').get(var.get('rnd3d')))+Js(' of '))+var.get('nm4').get(var.get('rnd4d')))+Js(' '))+var.get('nm5').get(var.get('rnd5d'))))
    var.put('name6', (((((Js('- ')+var.get('nm3').get(var.get('rnd3e')))+Js(' of '))+var.get('nm4').get(var.get('rnd4e')))+Js(' '))+var.get('nm5').get(var.get('rnd5e'))))
    def PyJs_LONG_0_(var=var):
        return ((((((((((((((var.get('nm6').get(var.get('rnd6'))+Js(' the '))+var.get('nm4').get(var.get('rnd4a')))+Js(' '))+var.get('nm5').get(var.get('rnd5a')))+Js(' '))+var.get('nm7').get(var.get('rnd7')))+Js('. Add '))+var.get('nm8').get(var.get('rnd8')))+Js(' to turn it into '))+var.get('nm9').get(var.get('rnd9')))+Js(', then add the '))+var.get('nm4').get(var.get('rnd4b')))+Js(' '))+var.get('nm5').get(var.get('rnd5b')))
    var.put('name7', ((PyJs_LONG_0_()+var.get('nm10').get(var.get('rnd10')))+Js('.')))
    def PyJs_LONG_1_(var=var):
        return (((((((((((((Js('Fill a pan with ')+var.get('nm11').get(var.get('rnd11')))+Js(', add the mixture and '))+var.get('nm12').get(var.get('rnd12')))+Js('. Let it '))+var.get('nm13').get(var.get('rnd13')))+Js(' before adding the '))+var.get('nm4').get(var.get('rnd4c')))+Js(' '))+var.get('nm5').get(var.get('rnd5c')))+Js(' and '))+var.get('nm4').get(var.get('rnd4d')))+Js(' '))+var.get('nm5').get(var.get('rnd5d')))
    var.put('name8', (((PyJs_LONG_1_()+Js(', '))+var.get('nm14').get(var.get('rnd14')))+Js('.')))
    var.put('name9', (((((((var.get('nm15').get(var.get('rnd15'))+Js(', mix in the '))+var.get('nm4').get(var.get('rnd4e')))+Js(' '))+var.get('nm5').get(var.get('rnd5e')))+Js(' and let everything '))+var.get('nm16').get(var.get('rnd16')))+Js('.')))
    var.put('name10', (((var.get('nm17').get(var.get('rnd17'))+Js('. Your potion is ready to be used. '))+var.get('nm18').get(var.get('rnd18')))+Js('.')))
    var.put('name11', ((Js('Recipe by ')+var.get('nm19').get(var.get('rnd19')))+Js('.')))
    var.put('br', Js([]))
    #for JS loop
    var.put('i', Js(0.0))
    while (var.get('i')<Js(13.0)):
        try:
            pass
        finally:
                (var.put('i',Js(var.get('i').to_number())+Js(1))-Js(1))
    pass
    var.put('result', Js([]))
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
pass
pass


# Add lib to the module scope
potionDescription = var.to_python()