__all__ = ['tavernDescriptions']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nameGen'])
@Js
def PyJsHoisted_nameGen_(this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this}, var)
    var.registers(['names4', 'names15', 'random15', 'names5', 'names2', 'name', 'name7', 'random5', 'random8a', 'name3', 'name6', 'random1a', 'random11', 'random1c', 'type', 'name2', 'random10', 'names14', 'names11', 'names18', 'names17', 'name4', 'random1b', 'random3', 'random17', 'random6', 'names9', 'names13', 'names8', 'names16', 'names3', 'names12', 'names1', 'random9', 'random7', 'random4', 'random18', 'result', 'random2', 'random12', 'names6', 'names10', 'random19', 'random14', 'name5', 'random16', 'names19', 'random13', 'names7', 'random8b'])
    var.put('type', var.get('Math').callprop('random'))
    var.put('names1', Js([Js('welcoming'), Js('cozy'), Js('inviting'), Js('warm'), Js('cheerful'), Js('snug'), Js('delightful'), Js('well maintained'), Js('clean'), Js('homey'), Js('folksy'), Js('pleasant'), Js('intimate'), Js('rustic'), Js('modest'), Js('humble'), Js('peaceful'), Js('beautiful'), Js('enchanting'), Js('cheerful')]))
    var.put('names2', Js([Js('Bricks'), Js('Clay'), Js('Clay bricks'), Js('Hardwooden planks'), Js('Large and small stones'), Js('Large stones'), Js('Logs'), Js('Plastered walls'), Js('Sandstone bricks'), Js('Small stones'), Js('Softwood'), Js('Softwooden planks'), Js('Stacked boulders'), Js('Stacked stones'), Js('Timber')]))
    var.put('names3', Js([Js('carved pillars'), Js('hardwooden beams'), Js('hardwooden pillars'), Js('hardwooden tree trunks'), Js('huge, stone beams'), Js('huge, stone pillars'), Js('intricate stone carvings'), Js('intricate wooden carvings'), Js('marble details'), Js('marble pillars'), Js('marble stones'), Js('sandstone pillars'), Js('softwooden tree trunks'), Js('stone beams'), Js('stone pillars'), Js('thick, hardwooden logs'), Js('thick, stone beams'), Js('tree trunks'), Js('well-crafted wooden beams'), Js('wooden pillars')]))
    var.put('names4', Js([Js('hard'), Js('near impossible'), Js('difficult'), Js('tough'), Js('impossible')]))
    var.put('names5', Js([Js('curtained windows'), Js('darkened windows'), Js('high windows'), Js('large, curtained windows'), Js('large, stained glass windows'), Js('small, curtained windows'), Js('small, stained glass windows'), Js('stained glass windows'), Js('windows'), Js('closed windows')]))
    var.put('names6', Js([Js('animation'), Js('cheerful sounds'), Js('clapping and cheering'), Js('clinking of beer glasses'), Js('energy and excitement'), Js('enjoyment'), Js('entertained voices'), Js('entertainment'), Js('enthusiastic noises'), Js('excited voices'), Js('excitement'), Js('happiness and joy'), Js('hustling and bustling'), Js('inviting music'), Js('laughter'), Js('laughter and cheering'), Js('livelyness'), Js('music and songs'), Js('music and voices'), Js('noise'), Js('passionate voices'), Js('sounds of cutlery and drinking glasses'), Js('sounds of dancing and singing'), Js('thrilled sounds'), Js('warm noises')]))
    var.put('names7', Js([Js('decorated, metal door'), Js('decorated, wooden door'), Js('hardwooden door'), Js('heavily used, metal door'), Js('heavily used, wooden door'), Js('heavy, metallic door'), Js('heavy, wooden door'), Js('huge, hardwooden door'), Js('old, hardwooden door'), Js('old, metal door'), Js('old, wooden door'), Js('small, softwooden door'), Js('thick, metal door'), Js('thick, wooden door'), Js('well-crafted, metal door')]))
    var.put('names8', Js([Js('amazing, but unknown scents'), Js('a pleasant atmosphere'), Js('excitement'), Js('joyful music'), Js('cheerful singing'), Js('the smell of alcohol'), Js('laughing voices'), Js('clapping hands'), Js('dancing people'), Js('aromas of roasted meats'), Js('the smile of a waitress'), Js('overall happiness'), Js('a sense of home'), Js('a feeling of comfort')]))
    var.put('names9', Js([Js('busy'), Js('extremely busy'), Js('quite busy'), Js('a little preoccupied'), Js('handling some customers'), Js('engaged in a conversation'), Js('working hard'), Js('buried in orders'), Js('swamped in work'), Js('working up a sweat')]))
    var.put('names10', Js([Js('short wave'), Js('smile'), Js('wink'), Js('friendly nod'), Js('wave')]))
    var.put('names11', Js([Js('lovely'), Js('alluring'), Js('enchanting'), Js('engaging'), Js('charming')]))
    var.put('names12', Js([Js('Hardwooden beams'), Js('Marble pillars'), Js('Rounded, stone beams'), Js('Rounded, wooden beams'), Js('Several walls'), Js('Sqaured, stone beams'), Js('Squared, wooden beams'), Js('Stone beams'), Js('Tree logs'), Js('Wooden beams')]))
    var.put('names13', Js([Js('Christmas-like lights'), Js('ambient lights'), Js('candles'), Js('chandeliers'), Js('decorational lights'), Js('fans'), Js('huge lamps'), Js('lanterns'), Js('large candles'), Js('light fixtures'), Js('lights'), Js('rows of small candles'), Js('rows of small lights'), Js('sconces'), Js('torches')]))
    var.put('names14', Js([Js("clear of anything, though signs do show plenty of things used to hang on the walls, though they've probably been knocked off by customers who had too much to drink."), Js('completely empty, besides the lighting, most likely because customers stumble against the walls too often and would knock off anything on the walls.'), Js('covered in photographs of personal achievements, all related to the nearby mountain. Some of people who reached the summit, others simply of happy people.'), Js("decorated with mounted animal heads, hides and small animals. It's clear the owner is an avid hunter and the smells coming from the kitchen indicate the animals don't go to waste."), Js("decorated with sports memorabilia, it's clear the owner, and probably the customers, are avid fans."), Js('full of paintings, all in a different style, but all of the surrounding area.'), Js("full of paintings, judging by the style they're all done by 1 person, perhaps the owner."), Js("littered with all sorts of memorabilia, though whether they're collected or donated is uncertain."), Js("littered with so many different memorabilia, you're not sure if they tried going for a specific style at one time or just put up anything they like."), Js('loaded with hundreds of memorabilia, all signed and most likely donated by customers.'), Js('overflowing with signatures and written messages, undoubtedly from happy customers.'), Js('packed with all sorts of travel memorabilia, most likely all collected by the owner.'), Js('packed with rows of painted portraits. You recognize the bartender on one of them, so the others must be either friends, family or previous owners.'), Js("swarmed with flags of all sorts and sizes. Some are from nearby towns or provinces, others from the far corners of the world. They must've been fited to the owner."), Js('swarming with photographs, some of what undoubtedly must be famous people and others of happy customers.')]))
    var.put('names15', Js([Js('Locals'), Js('Tourists'), Js('Travelers'), Js('Passing traders'), Js('Workers'), Js('Soldiers'), Js("Groups belonging to some kind of organization, whether sport, music or other you're not sure of,")]))
    var.put('names16', Js([Js('is often a good sign.'), Js('could be seen as the best sign you can get.'), Js("could be seen as a bad sign, though you're sure it's not."), Js('often indicates great food.'), Js('often means great company.'), Js('often leads to exciting evenings.'), Js('is probably the best clientele for the owner.')]))
    var.put('names17', Js([Js(', what looks like couples, lone travellers and anybody else who enjoys great company.'), Js(', what must be seperate groups who have bonded over great food and conversation.'), Js(', what seems to be entire families, all enjoying the food, drinks and company of each other.'), Js(', what seems to be one large group of people.'), Js(', what seems to be the entire surrounding village.'), Js(' happy, excited groups of people, some are dancing on the table, while others cheer them on with clapping and yelling.'), Js(' locals, travellers, foreigners and anybody else who wishes to join.'), Js(' seperate groups of people, all enjoying themselves, but they keep to themselves.'), Js(' seperate groups who, after having had quite a few drinks, seem to be trying to prove which group is best.'), Js(' several smaller groups of people.')]))
    var.put('names18', Js([Js('are clearly having a good time.'), Js('seem to be enjoying themselves a lot, perhaps too much, if such a thing is possible.'), Js('are probably starting to reach the point of having drunk too much, though nobody seems to mind.'), Js("clearly enjoy each other's company, though they seem to be strangers who have met here."), Js('are playing games and, judging by their laughter, are either telling jokes or great, perhaps embarrasing, tales.'), Js('seem to be close with the owner, though they happily welcome others among their midst.'), Js('are singing and dancing, occassionaly pulling an unsuspecting waitress amidst their dancing group.'), Js('are indulging in great food and drinks, while some do try to strike a conversation, others can barely speak a word between eating what must be delicious food.'), Js("who seem to be strangers to each other, all sitting here because there are no other seats. Though they all clearly enjoy each other's company.")]))
    var.put('names19', Js([Js('the smells of grilled and cooked food coming from the kitchen, it must be the food.'), Js("the amount of cups, tankards and glasses on the table, it's probably the fine alcoholic drinks."), Js("the amount of men staring at one of the waitresses, it's probably her beauty and charm."), Js("the amount of women in this tavern and the amount of them trying to subtly eye the bartender, it's probably his good looks and charm."), Js('the music and how many people are dancing, it must be the live band who just started playing.'), Js('the angelic voice who just started singing, it must be famous for this singer.'), Js("the laughter, cheering and overall enjoyment of everybody, it's probably the people themselves who make this tavern famous."), Js("the warmth and joy radiating throught the tavern, it's probably the atmosphere that makes this tavern famous.")]))
    if (var.get('type')>Js(0.5)):
        var.put('names1', Js([Js('broken'), Js('cheerless'), Js('cold'), Js('crude'), Js('dark'), Js('depressing'), Js('dire'), Js('dirty'), Js('disturbing'), Js('dull'), Js('gloomy'), Js('horrible'), Js('nasty'), Js('rough'), Js('ugly'), Js('uncomfortable'), Js('unenjoyable'), Js('unfriendly'), Js('uninviting'), Js('unwelcoming')]))
        var.put('names5', Js([Js('curtained windows'), Js('darkened windows'), Js('high windows'), Js('large, curtained windows'), Js('large, stained glass windows'), Js('small, curtained windows'), Js('small, stained glass windows'), Js('stained glass windows'), Js('windows'), Js('closed windows'), Js('dirty windows'), Js('dusty windows')]))
        var.put('names6', Js([Js('apathy'), Js('awkward silence'), Js('bitterness'), Js('coldness'), Js('depressing vibes'), Js('dire mood'), Js('gloominess'), Js('lack of joy'), Js('lack of life'), Js('lack of people'), Js('lethargy'), Js('lifelessness'), Js('ominous atmosphere'), Js('quiet sorrow'), Js('silence'), Js('uncomfortable atmosphere'), Js('whispers and weeping')]))
        def PyJs_LONG_0_(var=var):
            return var.put('names7', Js([Js('worn, metal door'), Js('worn, wooden door'), Js('hardwooden door'), Js('heavily used, metal door'), Js('heavily used, wooden door'), Js('heavy, metallic door'), Js('heavy, wooden door'), Js('huge, hardwooden door'), Js('old, hardwooden door'), Js('old, metal door'), Js('old, wooden door'), Js('small, softwooden door'), Js('thick, metal door'), Js('thick, wooden door'), Js('dirty, metal door'), Js('dirty, wooden door')]))
        PyJs_LONG_0_()
        def PyJs_LONG_1_(var=var):
            return var.put('names8', Js([Js('a horrific scent'), Js('dirt and dust from all places'), Js('silence'), Js('a few groans'), Js('watching eyes'), Js('the smell of alcohol'), Js('whispers'), Js('the sound of the wind outside'), Js('a coldness'), Js("aromas of what's probably food, hopefully"), Js('the rinkle of the doorbell'), Js('thick air'), Js('a layer of smoke hanging below the ceiling'), Js('a feeling of discomfort')]))
        PyJs_LONG_1_()
        var.put('names9', Js([Js('coughing into a dirty napkin'), Js('lying in a chair, doing nothing'), Js('pouring a drink for a customer'), Js('reading a newspaper'), Js("rubbing a glass with a cloth, though it's not getting cleaner"), Js('sleeping'), Js('smoking tobacco'), Js('staring at nothing'), Js('talking to a customer'), Js('trying to catch a spider')]))
        var.put('names10', Js([Js('')]))
        var.put('names11', Js([Js('dire'), Js('disgusting'), Js('dreary'), Js('dull'), Js('gloomy'), Js('horrible'), Js('somber')]))
        var.put('names13', Js([Js('candles'), Js('broken fans'), Js('huge, dusty lamps'), Js('lanterns'), Js('large, molten candles'), Js('light fixtures'), Js('broken lights'), Js('rows of small, molten candles'), Js('rows of small, broken lights'), Js('sconces'), Js('unlit torches')]))
        def PyJs_LONG_2_(var=var):
            return var.put('names14', Js([Js('completely empty, only covered in a layer of fatty grime'), Js('decorated, if you can call it that, with old paintings covered in dust'), Js('covered in cobwebs and any decoration that does hang there is now unrecognizable'), Js('covered in a layer of dust, making it near impossible to see what the few paintings on the walls are about'), Js("decorated with sport's memorabilia, though it looks like it hasn't been maintained or cleaned for years"), Js('loaded with pictures, though the dust and cobwebs stops you from taking a closer look'), Js('covered in messages, once written by loyal customers and now covered in dust, worn away and mostly unreadable'), Js('decorated with mounted animal heads and small animals, though most have become worn and broken, given the place an even creapier feel'), Js('littered with all sorts of memorabilia, many of which have become unrecognizable due to dust, cobwebs and other dirt'), Js("covered in photographs of what were undoubtedly better times for this tavern. They're now more of a painful reminder of what it has turned into")]))
        PyJs_LONG_2_()
        def PyJs_LONG_3_(var=var):
            return var.put('names15', Js([Js('could be locals, could be lost souls'), Js('could be anybody really'), Js("you'd like to stay away from"), Js('are silent and they keep to themselves'), Js("are eerily silent, you're unsure if all of them are even alive"), Js('appear to be quite ominous and suspicious in your eyes'), Js('appear to be dangerous in way or another'), Js('probably work less honorable operations')]))
        PyJs_LONG_3_()
        def PyJs_LONG_4_(var=var):
            return var.put('names16', Js([Js("you'd like to stay as for away from them as possible"), Js("you hope they'll leave you alone, just like you're leaving them alone"), Js('they give you an uncomfortable feeling of dread'), Js('it makes you a little nervous'), Js("you think it's probably time to leave, right now"), Js("it's about the clearest sign you can get, telling you you don't belong"), Js("you begin to fear for your safety, it's probably best to find a different place")]))
        PyJs_LONG_4_()
        var.put('names17', Js([Js('')]))
        var.put('names18', Js([Js('')]))
        def PyJs_LONG_5_(var=var):
            return var.put('names19', Js([Js("the figures lurking in the shadows, it's probably some dirty business"), Js("the dirt and unhygienic circumstances, it's probably food poisoning"), Js("everything you've seen so far, you don't really care and you probably don't want to know"), Js("the things and people you've seen, you're not waiting to find out"), Js('everything in this place, it must be something horrifying'), Js("judging by the people in this place, it's probably something shady and possibly dangerous for strangers like you")]))
        PyJs_LONG_5_()
    var.put('random1a', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names1').get('length')))))
    var.put('random1b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names1').get('length')))))
    while PyJsStrictEq(var.get('random1a'),var.get('random1b')):
        var.put('random1b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names1').get('length')))))
    var.put('random1c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names1').get('length')))))
    while (PyJsStrictEq(var.get('random1a'),var.get('random1c')) or PyJsStrictEq(var.get('random1b'),var.get('random1c'))):
        var.put('random1c', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names1').get('length')))))
    var.put('random2', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names2').get('length')))))
    var.put('random3', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names3').get('length')))))
    var.put('random4', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names4').get('length')))))
    var.put('random5', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length')))))
    var.put('random6', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length')))))
    var.put('random7', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names7').get('length')))))
    var.put('random8a', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names8').get('length')))))
    var.put('random8b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names8').get('length')))))
    while PyJsStrictEq(var.get('random8a'),var.get('random8b')):
        var.put('random8b', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names8').get('length')))))
    var.put('random9', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names9').get('length')))))
    var.put('random10', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names10').get('length')))))
    var.put('random11', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names11').get('length')))))
    var.put('random12', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names12').get('length')))))
    var.put('random13', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names13').get('length')))))
    var.put('random14', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names14').get('length')))))
    var.put('random15', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names15').get('length')))))
    var.put('random16', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names16').get('length')))))
    var.put('random17', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names17').get('length')))))
    var.put('random18', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names18').get('length')))))
    var.put('random19', var.get('parseInt')(var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names19').get('length')))))
    var.put('name', ((((((((((Js('From the outside it looks ')+var.get('names1').get(var.get('random1a')))+Js(', '))+var.get('names1').get(var.get('random1b')))+Js(' and '))+var.get('names1').get(var.get('random1c')))+Js('. '))+var.get('names2').get(var.get('random2')))+Js(' and '))+var.get('names3').get(var.get('random3')))+Js(" make up most of the building's outer structure.")))
    var.put('name2', ((((((Js("It's ")+var.get('names4').get(var.get('random4')))+Js(' to see through the '))+var.get('names5').get(var.get('random5')))+Js(', but the '))+var.get('names6').get(var.get('random6')))+Js(' from within can be felt outside.')))
    var.put('name3', ((((((Js('As you enter the tavern through the ')+var.get('names7').get(var.get('random7')))+Js(", you're welcomed by "))+var.get('names8').get(var.get('random8a')))+Js(' and '))+var.get('names8').get(var.get('random8b')))+Js('.')))
    var.put('name4', ((((Js('The bartender is ')+var.get('names9').get(var.get('random9')))+Js(', but still manages to welcome you with a '))+var.get('names10').get(var.get('random10')))+Js('.')))
    var.put('name5', ((((((((Js("It's as ")+var.get('names11').get(var.get('random11')))+Js(' inside as it is on the outside. '))+var.get('names12').get(var.get('random12')))+Js(' support the upper floor and the '))+var.get('names13').get(var.get('random13')))+Js(' attached to them. The walls are '))+var.get('names14').get(var.get('random14')))+Js('.')))
    def PyJs_LONG_6_(var=var):
        return ((((((((Js('The tavern itself is packed. ')+var.get('names15').get(var.get('random15')))+Js(' seem to be the primary clientele here, which '))+var.get('names16').get(var.get('random16')))+Js(' Several long tables are occupied by'))+var.get('names17').get(var.get('random17')))+Js(' The other, smaller tables are also occupied by people who '))+var.get('names18').get(var.get('random18')))+Js(' Even most of the stools at the bar are occupied, though nobody seems to mind more company.'))
    var.put('name6', PyJs_LONG_6_())
    var.put('name7', ((Js("You did hear rumors about this tavern, supposedly it's famous for something, but you can't remember what for. Though judging by ")+var.get('names19').get(var.get('random19')))+Js(' You manage to find a seat and prepare for what will undoubtedbly be a great evening.')))
    if (var.get('type')>Js(0.5)):
        var.put('name4', ((Js('The bartender is ')+var.get('names9').get(var.get('random9')))+Js(' and makes no effort to acknowledge your pressence.')))
        var.put('name6', ((((Js('The tavern itself is almost completely abanonded.  The few people inside ')+var.get('names15').get(var.get('random15')))+Js(', but whoever they are, '))+var.get('names16').get(var.get('random16')))+Js('.')))
        var.put('name7', ((Js("You did hear rumors about this tavern, supposedly it's infamous for something, but for the life of you you can't remember what for. Though juding by ")+var.get('names19').get(var.get('random19')))+Js('.')))
    pass
    var.put('result', Js([]))
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
pass
pass


# Add lib to the module scope
tavernDescriptions = var.to_python()