__all__ = ['videoGames']

# Don't look below, you will not understand this Python code :) I don't.

from js2py.pyjs import *
# setting scope
var = Scope( JS_BUILTINS )
set_global_object(var)

# Code follows:
var.registers(['nameGen'])
@Js
def PyJsHoisted_nameGen_(this, arguments, var=var):
    var = Scope({'arguments':arguments, 'this':this}, var)
    var.registers(['names4', 'names6', 'names5', 'names8', 'names2', 'choice', 'names3', 'names1', 'names7', 'result'])
    var.put('choice', var.get('$')(Js("#radioChoice input[type='radio']:checked")).callprop('val'))
    var.put('names1', Js([Js('Ace'), Js('Alien'), Js('Alpha'), Js('Ancient'), Js('Android'), Js('Angel'), Js('Arctic'), Js('Armageddon'), Js('Armed'), Js('Armored'), Js('Atomic'), Js('Bad'), Js('Battle'), Js('Bio'), Js('Bionic'), Js('Blood'), Js('Broken'), Js('Brutal'), Js('Bullet'), Js('Cannibal'), Js('Carnivore'), Js('Celestial'), Js('Chaos'), Js('Chrome'), Js('Cloud'), Js('Cold'), Js('Combat'), Js('Cosmic'), Js('Covert'), Js('Crimson'), Js('Cursed'), Js('Dark'), Js('Dead'), Js('Death'), Js('Demon'), Js('Dragon'), Js('Ebon'), Js('Emergency'), Js('Enemy'), Js('Eternal'), Js('Evil'), Js('Final'), Js('Forbidden'), Js('Forgotten'), Js('Frozen'), Js('Fury'), Js('Future'), Js('Galaxy'), Js('Ghost'), Js('Grand'), Js('Hallowed'), Js('Honor'), Js('Human'), Js('Hunting'), Js('Immortal'), Js('Infected'), Js('Infernal'), Js('Infinite'), Js('Just'), Js('Killing'), Js('Lifeless'), Js('Light'), Js('Lost'), Js('Lunar'), Js('Mass'), Js('Metal'), Js('Midnight'), Js('Monster'), Js('Mortal'), Js('Nuclear'), Js('Obscure'), Js('Parasite'), Js('Phantom'), Js('Primal'), Js('Prime'), Js('Private'), Js('Red'), Js('Sacred'), Js('Saint'), Js('Secret'), Js('Shadow'), Js('Silent'), Js('Silver'), Js('Solar'), Js('Solitary'), Js('Soul'), Js('Space'), Js('Special'), Js('Spirit'), Js('Star'), Js('Storm'), Js('Tactical'), Js('Thunder'), Js('Titan'), Js('Twilight'), Js('Vampire'), Js('Warrior'), Js('Werewolf'), Js('Zero'), Js('Zombie')]))
    var.put('names2', Js([Js('Abyss'), Js('Aftermath'), Js('Age'), Js('Agent'), Js('Alert'), Js('Alias'), Js('Alliance'), Js('Apocalypse'), Js('Armada'), Js('Assault'), Js('Asylum'), Js('Attack'), Js('Barrage'), Js('Betrayal'), Js('Blade'), Js('Bounty'), Js('Breakout'), Js('Breed'), Js('Calamity'), Js('Call'), Js('Campaign'), Js('Carnage'), Js('Castle'), Js('Cavern'), Js('Cell'), Js('Chronicles'), Js('Collapse'), Js('Command'), Js('Complex'), Js('Conflict'), Js('Conquest'), Js('Conspiracy'), Js('Crossing'), Js('Crusade'), Js('Cry'), Js('Curse'), Js('Dream'), Js('Edge'), Js('Ego'), Js('Elements'), Js('Emergency'), Js('Escape'), Js('Evolution'), Js('Experiment'), Js('Fear'), Js('Freedom'), Js('Frontier'), Js('Games'), Js('Guardians'), Js('Harvest'), Js('Haven'), Js('Hazard'), Js('Heart'), Js('Hero'), Js('Impact'), Js('Inquisition'), Js('Invasion'), Js('Island'), Js('Kingdom'), Js('Legacy'), Js('Legend'), Js('Machine'), Js('Mask'), Js('Master'), Js('Matters'), Js('Mercenary'), Js('Money'), Js('Network'), Js('Nightmare'), Js('Omen'), Js('Operation'), Js('Panic'), Js('Possession'), Js('Predator'), Js('Premonition'), Js('Project'), Js('Prototype'), Js('Rage'), Js('Realm'), Js('Reaver'), Js('Resurrection'), Js('Retribution'), Js('Rising'), Js('Road'), Js('Signs'), Js('Siren'), Js('State'), Js('Survival'), Js('Syndrome'), Js('System'), Js('Tales'), Js('Theft'), Js('Tombs'), Js('Universe'), Js('Vendetta'), Js('Virus'), Js('Voyage'), Js('Warfare'), Js('Woods'), Js('World'), Js('Wrath')]))
    var.put('names3', Js([Js('Arm'), Js('Assault'), Js('Attack'), Js('Battle'), Js('Besiege'), Js('Blast'), Js('Bombard'), Js('Breakout'), Js('Burn'), Js('Charge'), Js('Chase'), Js('Clash'), Js('Command'), Js('Conquer'), Js('Counter'), Js('Crash'), Js('Crush'), Js('Decimate'), Js('Defeat'), Js('Demolish'), Js('Destroy'), Js('Divide'), Js('Escape'), Js('Fight'), Js('Fortify'), Js('Guard'), Js('Hunt'), Js('Incinerate'), Js('Infect'), Js('Invade'), Js('Kill'), Js('Knockout'), Js('Pillage'), Js('Plan'), Js('Protect'), Js('Raid'), Js('Rescue'), Js('Resist'), Js('Retaliate'), Js('Revolt'), Js('Rise'), Js('Rule'), Js('Run'), Js('Shoot'), Js('Strategize'), Js('Strife'), Js('Strike'), Js('Struggle'), Js('Vengeance'), Js('Wipe Out')]))
    var.put('names4', Js([Js('Aggression'), Js('Assault'), Js('Atonement'), Js('Autonomy'), Js('Betrayal'), Js('Campaigns'), Js('Combat'), Js('Conflict'), Js('Deception'), Js('Democracy'), Js('Duplicity'), Js('Enforce'), Js('Execution'), Js('Freedom'), Js('Friction'), Js('Heroes'), Js('Heroics'), Js('Hypocrisy'), Js('Immunity'), Js('Infringement'), Js('Invasion'), Js('Law'), Js('Liberty'), Js('Lies'), Js('Logic'), Js('Opportunity'), Js('Order'), Js('Power'), Js('Privilige'), Js('Prosecution'), Js('Reason'), Js('Redemption'), Js('Regulations'), Js('Rescue'), Js('Resitution'), Js('Retribution'), Js('Rivalry'), Js('Rule'), Js('Salvation'), Js('Stipulation'), Js('Strife'), Js('Struggle'), Js('Transgression'), Js('Treachery'), Js('Trickery'), Js('Truth'), Js('Vengeance'), Js('Violation'), Js('War'), Js('Wrath')]))
    var.put('names5', Js([Js('Age'), Js('Annihilation'), Js('Apocalypse'), Js('Barrage'), Js('Battle'), Js('Battlefield'), Js('Born'), Js('Bridge'), Js('Burial'), Js('Century'), Js('Chamber'), Js('Chase'), Js('Chronicle'), Js('City'), Js('Codename'), Js('Command'), Js('Contract'), Js('Crime'), Js('Crisis'), Js('Cult'), Js('Danger'), Js('Day'), Js('Days'), Js('Death'), Js('Decade'), Js('Defense'), Js('Descent'), Js('Destruction'), Js('Dimension'), Js('Doom'), Js('Dream'), Js('Dynasty'), Js('Echoes'), Js('Edge'), Js('Embers'), Js('Empire'), Js('Epoch'), Js('Escalation'), Js('Execution'), Js('Extinction'), Js('Fight'), Js('Flashbacks'), Js('Force'), Js('Fortress'), Js('Galaxy'), Js('Game'), Js('Garden'), Js('Gateway'), Js('Genesis'), Js('Genocide'), Js('Ghosts'), Js('Glitch'), Js('Graves'), Js('Guns'), Js('Hazard'), Js('Home'), Js('House'), Js('Hunt'), Js('Impact'), Js('Invasion'), Js('Journey'), Js('Knights'), Js('Land'), Js('Law'), Js('Life'), Js('Matter'), Js('Maze'), Js('Memories'), Js('Murder'), Js('Nature'), Js('Order'), Js('Paradise'), Js('Planet'), Js('Power'), Js('Quest'), Js('Raid'), Js('Remorse'), Js('Renegade'), Js('Retribution'), Js('Revenge'), Js('Revival'), Js('Rush'), Js('Science'), Js('Shadow'), Js('Sons'), Js('Source'), Js('Space'), Js('Spells'), Js('Streets'), Js('Sword'), Js('Symphony'), Js('Thunder'), Js('Treasures'), Js('Voyage'), Js('Weapons'), Js('Week'), Js('Whispers'), Js('Words'), Js('World'), Js('Year')]))
    var.put('names6', Js([Js('Action'), Js('Agony'), Js('Ambition'), Js('Anarchy'), Js('Androids'), Js('Angels'), Js('Armor'), Js('Awe'), Js('Barbarians'), Js('Blood'), Js('Chaos'), Js('Conflict'), Js('Control'), Js('Death'), Js('Demons'), Js('Despair'), Js('Destruction'), Js('Disarray'), Js('Disorder'), Js('Domination'), Js('Doubt'), Js('Dragons'), Js('Dread'), Js('Dust'), Js('Duty'), Js('Earth'), Js('Evil'), Js('Evolution'), Js('Existence'), Js('Explosions'), Js('Faith'), Js('Fate'), Js('Fear'), Js('Fire'), Js('Fortune'), Js('Freedom'), Js('Frenzy'), Js('Gangs'), Js('Gods'), Js('Harmony'), Js('Havoc'), Js('Hell'), Js('Heroes'), Js('Honor'), Js('Hope'), Js('Immortals'), Js('Infinity'), Js('Innocents'), Js('Insanity'), Js('Kings'), Js('Legends'), Js('Liberty'), Js('Lies'), Js('Logic'), Js('Mayhem'), Js('Misery'), Js('Mortals'), Js('Mutants'), Js('Mystery'), Js('Nature'), Js('Nightmares'), Js('Nothing'), Js('Oracles'), Js('Order'), Js('Pain'), Js('Panic'), Js('Power'), Js('Predators'), Js('Prototypes'), Js('Rage'), Js('Reason'), Js('Reckoning'), Js('Redemption'), Js('Resistance'), Js('Revolution'), Js('Riddles'), Js('Rubble'), Js('Sacrifice'), Js('Salvation'), Js('Sanity'), Js('Secrets'), Js('Shadows'), Js('Skeletons'), Js('Skulls'), Js('Solitude'), Js('Souls'), Js('Stealth'), Js('Struggle'), Js('Terror'), Js('Time'), Js('Treason'), Js('Truth'), Js('Twisted Dreams'), Js('Valor'), Js('Vampires'), Js('Victory'), Js('War'), Js('Warfare'), Js('Werewolves'), Js('Zombies')]))
    var.put('names7', Js([Js('Air'), Js('Alpha'), Js('Alter'), Js('Anti'), Js('Arche'), Js('Astro'), Js('Back'), Js('Battle'), Js('Bio'), Js('Blade'), Js('Blaster'), Js('Block'), Js('Blood'), Js('Blue'), Js('Body'), Js('Border'), Js('Brutal'), Js('Bullet'), Js('Castle'), Js('Chroma'), Js('Cloud'), Js('Cluster'), Js('Cross'), Js('Crystal'), Js('Cyber'), Js('Data'), Js('Dead'), Js('Def'), Js('Delta'), Js('Demon'), Js('Dragon'), Js('Dread'), Js('Dream'), Js('Dyna'), Js('Ember'), Js('Endor'), Js('Ever'), Js('Evo'), Js('Ex'), Js('Far'), Js('Fire'), Js('Fuse'), Js('Fusion'), Js('Geo'), Js('Grim'), Js('Hell'), Js('Mad'), Js('Master'), Js('Ultra'), Js('War')]))
    var.put('names8', Js([Js('back'), Js('blade'), Js('blast'), Js('blaze'), Js('borne'), Js('bot'), Js('cell'), Js('chase'), Js('core'), Js('craft'), Js('craze'), Js('cry'), Js('doom'), Js('droid'), Js('dude'), Js('fight'), Js('fire'), Js('flight'), Js('force'), Js('gene'), Js('heart'), Js('hunt'), Js('land'), Js('life'), Js('light'), Js('line'), Js('lust'), Js('mania'), Js('mind'), Js('nite'), Js('phobia'), Js('plan'), Js('point'), Js('rage'), Js('rain'), Js('reign'), Js('rush'), Js('scape'), Js('shock'), Js('shot'), Js('side'), Js('site'), Js('sky'), Js('space'), Js('star'), Js('storm'), Js('tech'), Js('watch'), Js('wind'), Js('works'), Js('zone')]))
    while 1:
        SWITCHED = False
        CONDITION = (var.get('choice'))
        if SWITCHED or PyJsStrictEq(CONDITION, Js('adventure')):
            SWITCHED = True
            def PyJs_LONG_0_(var=var):
                return var.put('names1', Js([Js('Alien'), Js('Altered'), Js('Amber'), Js('Angelic'), Js('Bad'), Js('Banished'), Js('Bionic'), Js('Black'), Js('Blind'), Js('Blood'), Js('Broken'), Js('Brutal'), Js('Chaos'), Js('Chrono'), Js('Clockwork'), Js('Covert'), Js('Criminal'), Js('Crimson'), Js('Crystal'), Js('Cyber'), Js('Dark'), Js('Dead'), Js('Demonic'), Js('Digital'), Js('Dragon'), Js('Dread'), Js('Dual'), Js('Eastern'), Js('Ebon'), Js('Eclipsed'), Js('Elder'), Js('Enchanted'), Js('Endless'), Js('Epic'), Js('Eternal'), Js('Evil'), Js('Faery'), Js('Fatal'), Js('Fearless'), Js('Forbidden'), Js('Forgotten'), Js('Forsaken'), Js('Fortunate'), Js('Full On'), Js('Future'), Js('Global'), Js('Grand'), Js('Gray'), Js('Guilty'), Js('Happy'), Js('Hard'), Js('Haunted'), Js('Hero'), Js('Heroic'), Js('Hidden'), Js('Holy'), Js('Immoral'), Js('Immortal'), Js('Innocent'), Js('Invisible'), Js('Iron'), Js('Jade'), Js('Jungle'), Js("King's"), Js('Last'), Js('Magic'), Js('Midnight'), Js('Midsummer'), Js('Missing'), Js('Mortal'), Js('Mystery'), Js('Necro'), Js('Obsidian'), Js('Paradise'), Js('Parellel'), Js('Phantom'), Js('Primal'), Js('Prime'), Js('Project'), Js('Red'), Js('Rising'), Js('Robo'), Js('Royal'), Js('Sanguine'), Js('Shadow'), Js('Silent'), Js('Silver'), Js('Solar'), Js('Solstice'), Js('Space'), Js('Star'), Js('Tiny'), Js('Twilight'), Js('Twisted'), Js('Uncanny'), Js('Vampire'), Js('War'), Js('Werewolf'), Js('Whispering'), Js('Wild')]))
            PyJs_LONG_0_()
            def PyJs_LONG_1_(var=var):
                return var.put('names2', Js([Js('Abyss'), Js('Adventure'), Js('Age'), Js('Agent'), Js('Alchemy'), Js('Alien'), Js('Angel'), Js('Assassin'), Js('Assault'), Js('Attack'), Js('Betrayal'), Js('Blade'), Js('Canvas'), Js('Castle'), Js('Chamber'), Js('Circle'), Js('Code'), Js('Codex'), Js('Colony'), Js('Command'), Js('Conspiracy'), Js('Core'), Js('Crisis'), Js('Crown'), Js('Cry'), Js('Curse'), Js('Dawn'), Js('Days'), Js('Death'), Js('Demon'), Js('Destiny'), Js('Dimension'), Js('Disciple'), Js('Downfall'), Js('Dragon'), Js('Dream'), Js('Earth'), Js('Echo'), Js('Ego'), Js('Empire'), Js('Enigma'), Js('Escape'), Js('Evolution'), Js('Fantasy'), Js('Force'), Js('Gates'), Js('Guard'), Js('Halo'), Js('Heart'), Js('Honor'), Js('Inferno'), Js('Invasion'), Js('Investigation'), Js('Island'), Js('Kingdom'), Js('Kiss'), Js('Knight'), Js('Legacy'), Js('Lesson'), Js('Life'), Js('Light'), Js('Magic'), Js('Master'), Js('Memory'), Js('Mind'), Js('Mirror'), Js('Moon'), Js('Murder'), Js('Mystery'), Js('Nemesis'), Js('Nightmare'), Js('Oblivion'), Js('Oracle'), Js('Origin'), Js('Paragon'), Js('Path'), Js('Planet'), Js('Power'), Js('Pride'), Js('Realm'), Js('Report'), Js('Resurrection'), Js('Secrets'), Js('Sect'), Js('Seed'), Js('Shadows'), Js('Smile'), Js('Soul'), Js('Sun'), Js('Sword'), Js('Syndrome'), Js('Tide'), Js('Time'), Js('Tomb'), Js('Trail'), Js('Treasure'), Js('Tribe'), Js('Trinity'), Js('Venture'), Js('Wish')]))
            PyJs_LONG_1_()
            def PyJs_LONG_2_(var=var):
                return var.put('names3', Js([Js('Angels'), Js('Barbarians'), Js('Castles'), Js('Codes'), Js('Conquest'), Js('Crowns'), Js('Curses'), Js('Demons'), Js('Dragons'), Js('Dreams'), Js('Elves'), Js('Ghosts'), Js('Giants'), Js('Goblins'), Js('Illusions'), Js('Kings'), Js('Knights'), Js('Legends'), Js('Lords'), Js('Love'), Js('Magic'), Js('Monsters'), Js('Mysteries'), Js('Nightmares'), Js('Orcs'), Js('Outlaws'), Js('Phantoms'), Js('Pirates'), Js('Power'), Js('Prophecies'), Js('Realms'), Js('Riddles'), Js('Robots'), Js('Sailors'), Js('Secrets'), Js('Shadows'), Js('Shields'), Js('Ships'), Js('Sorcery'), Js('Souls'), Js('Spells'), Js('Spirits'), Js('Swords'), Js('Traitors'), Js('Treasures'), Js('Vampires'), Js('Vikings'), Js('War'), Js('Werewolves'), Js('Wizards')]))
            PyJs_LONG_2_()
            def PyJs_LONG_3_(var=var):
                return var.put('names4', Js([Js('Betrayal'), Js('Blasphemy'), Js('Bravery'), Js('Conquest'), Js('Conspiracies'), Js('Danger'), Js('Darkness'), Js('Death'), Js('Deception'), Js('Discipline'), Js('Dishonor'), Js('Eternity'), Js('Exploration'), Js('Faith'), Js('Fate'), Js('Fortune'), Js('Hauntings'), Js('Honor'), Js('Hope'), Js('Horrors'), Js('Infinity'), Js('Justice'), Js('Labyrinths'), Js('Legacies'), Js('Legends'), Js('Lies'), Js('Madness'), Js('Memories'), Js('Miracles'), Js('Murder'), Js('Mystery'), Js('Nightmares'), Js('Origins'), Js('Power'), Js('Revelations'), Js('Riddles'), Js('Rituals'), Js('Romance'), Js('Secrets'), Js('Shadows'), Js('Silence'), Js('Sins'), Js('Solitude'), Js('Sorrow'), Js('Stories'), Js('Theories'), Js('Time'), Js('Traps'), Js('Vengeance'), Js('War')]))
            PyJs_LONG_3_()
            def PyJs_LONG_4_(var=var):
                return var.put('names5', Js([Js('Abyss'), Js('Adventure'), Js('Age'), Js('Agent'), Js('Angel'), Js('Art'), Js('Assassins'), Js('Awakening'), Js('Beginning'), Js('Betrayal'), Js('Blade'), Js('Book'), Js('Burden'), Js('Case'), Js('Children'), Js('Chronicles'), Js('Circle'), Js('City'), Js('Conquest'), Js('Core'), Js('Creatures'), Js('Crypt'), Js('Cult'), Js('Curse'), Js('Danger'), Js('Darkness'), Js('Dawn'), Js('Death'), Js('Deception'), Js('Demon'), Js('Desire'), Js('Division'), Js('Doom'), Js('Dream'), Js('Dungeon'), Js('Edge'), Js('Enemy'), Js('Evil'), Js('Face'), Js('Fall'), Js('Fate'), Js('Forest'), Js('Game'), Js('Gate'), Js('God'), Js('Gravity'), Js('Guardians'), Js('Guilt'), Js('Hand'), Js('Heart'), Js('Heroes'), Js('House'), Js('Illusion'), Js('Immortals'), Js('Journey'), Js('King'), Js('Kingdom'), Js('Knight'), Js('Lair'), Js('Land'), Js('Last'), Js('Legacy'), Js('Legend'), Js('Light'), Js('Lord'), Js('Magic'), Js('Memories'), Js('Messenger'), Js('Monsters'), Js('Mortals'), Js('Mountain'), Js('Murder'), Js('Mystery'), Js('Oracle'), Js('Origin'), Js('Passage'), Js('Path'), Js('Phantom'), Js('Planet'), Js('Prisoner'), Js('Quest'), Js('Revelation'), Js('Riddles'), Js('Search'), Js('Secret'), Js('Seed'), Js('Shadows'), Js('Society'), Js('Soul'), Js('Sword'), Js('Tales'), Js('Temptation'), Js('Throne'), Js('Time'), Js('Tombs'), Js('Traitor'), Js('Truth'), Js('Voice'), Js('Whispers'), Js('World')]))
            PyJs_LONG_4_()
            def PyJs_LONG_5_(var=var):
                return var.put('names6', Js([Js('Adventure'), Js('Agony'), Js('Alchemy'), Js('Ancestors'), Js('Ancients'), Js('Angels'), Js('Autumn'), Js('Beasts'), Js('Blood'), Js('Chaos'), Js('Clans'), Js('Conspiracies'), Js('Corruption'), Js('Curses'), Js('Dark Motives'), Js('Darkness'), Js('Death'), Js('Desire'), Js('Destiny'), Js('Destruction'), Js('Dimensions'), Js('Doom'), Js('Dragons'), Js('Dreams'), Js('Echos'), Js('Eden'), Js('Elements'), Js('Enlightenment'), Js('Eternity'), Js('Evidence'), Js('Experiments'), Js('Faith'), Js('Fear'), Js('Fire'), Js('Giants'), Js('Gods'), Js('Gold'), Js('Happiness'), Js('Hatred'), Js('Heaven'), Js('Hell'), Js('Heroes'), Js('History'), Js('Honor'), Js('Hope'), Js('Illusions'), Js('Immortality'), Js('Infection'), Js('Infinity'), Js('Invention'), Js('Justice'), Js('Kings'), Js('Lies'), Js('Light'), Js('Love'), Js('Magic'), Js('Memories'), Js('Monsters'), Js('Mortality'), Js('Murder'), Js('Mutation'), Js('Mystery'), Js('Nightmares'), Js('Nothing'), Js('Obedience'), Js('Obsidian'), Js('Paradise'), Js('Power'), Js('Prophecies'), Js('Redemption'), Js('Relics'), Js('Riddles'), Js('Secrets'), Js('Separation'), Js('Serenity'), Js('Shadows'), Js('Silence'), Js('Silver'), Js('Sin'), Js('Sorrow'), Js('Souls'), Js('Space'), Js('Spirits'), Js('Spring'), Js('Stars'), Js('Summer'), Js('Survival'), Js('Time'), Js('Time Travel'), Js('Tomorrow'), Js('Tranquility'), Js('Treasure'), Js('Trinkets'), Js('Trust'), Js('Twilight'), Js('Valor'), Js('Vengeance'), Js('War'), Js('Winter'), Js('Wisdom')]))
            PyJs_LONG_5_()
            def PyJs_LONG_6_(var=var):
                return var.put('names7', Js([Js('Abyss'), Js('Alter'), Js('Anti'), Js('Arche'), Js('Astro'), Js('Battle'), Js('Bio'), Js('Blood'), Js('Border'), Js('Brutal'), Js('Bullet'), Js('Castle'), Js('Chrono'), Js('Cloud'), Js('Crystal'), Js('Cyber'), Js('Dark'), Js('Data'), Js('Dead'), Js('Demon'), Js('Dragon'), Js('Dread'), Js('Dream'), Js('Dyna'), Js('Ebon'), Js('Ember'), Js('Ever'), Js('Evo'), Js('Far'), Js('Fire'), Js('Fuse'), Js('Ghost'), Js('Grim'), Js('Hallow'), Js('Heaven'), Js('Hell'), Js('Hero'), Js('Inner'), Js('Iron'), Js('Knight'), Js('Light'), Js('Mad'), Js('Magic'), Js('Master'), Js('Mortal'), Js('Night'), Js('Phantom'), Js('Quest'), Js('Soul'), Js('War')]))
            PyJs_LONG_6_()
            def PyJs_LONG_7_(var=var):
                return var.put('names8', Js([Js('blade'), Js('scape'), Js('blaze'), Js('borne'), Js('bot'), Js('cast'), Js('cell'), Js('craft'), Js('crest'), Js('cry'), Js('doom'), Js('drift'), Js('droid'), Js('fight'), Js('fire'), Js('flight'), Js('force'), Js('heart'), Js('hunt'), Js('kin'), Js('land'), Js('light'), Js('line'), Js('mare'), Js('master'), Js('mind'), Js('mist'), Js('more'), Js('nite'), Js('path'), Js('piece'), Js('point'), Js('polis'), Js('rage'), Js('realm'), Js('reign'), Js('rite'), Js('rush'), Js('scape'), Js('ship'), Js('side'), Js('space'), Js('star'), Js('storm'), Js('tale'), Js('tomb'), Js('trail'), Js('view'), Js('ville'), Js('watch'), Js('way')]))
            PyJs_LONG_7_()
            break
        if SWITCHED or PyJsStrictEq(CONDITION, Js('role-playing')):
            SWITCHED = True
            def PyJs_LONG_8_(var=var):
                return var.put('names1', Js([Js('Alien'), Js('Ancestor'), Js('Arcane'), Js('Assassin'), Js('Battle'), Js('Birthright'), Js('Blood'), Js('Bloodline'), Js('Brave'), Js('Broken'), Js('Castle'), Js('Chaos'), Js('Chosen'), Js('Clone'), Js('Covert'), Js('Creature'), Js('Crystal'), Js('Dark'), Js('Dawn'), Js('Death'), Js('Demon'), Js('Divine'), Js('Dragon'), Js('Dungeon'), Js('Endless'), Js('Epic'), Js('Eternal'), Js('Exiled'), Js('Fallen'), Js('Fantasy'), Js('Forbidden'), Js('Forsaken'), Js('Freedom'), Js('Full Moon'), Js('Ghost'), Js('Golden'), Js('Gothic'), Js('Grand'), Js('Grim'), Js('Holy'), Js('Honest'), Js('Immortal'), Js('Incredible'), Js('Infernal'), Js('Infinite'), Js('Iron'), Js('Kingdom'), Js('Knight'), Js('Knightmare'), Js('Last'), Js('Lifeless'), Js('Lightning'), Js('Lost'), Js('Love'), Js('Mage'), Js('Magic'), Js('Majestic'), Js('Master'), Js('Metal'), Js('Monster'), Js('Moonlight'), Js('Morbid'), Js('Mortal'), Js('Mutant'), Js('Mystic'), Js('Nether'), Js('Night'), Js('Obsidian'), Js('Paradise'), Js('Phantom'), Js('Pioneer'), Js('Pirate'), Js('Plague'), Js('Planetary'), Js('Raiding'), Js('Rainbow'), Js('Reborn'), Js('Royal'), Js('Rune'), Js('Sacred'), Js('Scarlet'), Js('Shadow'), Js('Shapeshifter'), Js('Shattered'), Js('Simple'), Js('Soul'), Js('Space'), Js('Spellborn'), Js('Star'), Js('Stolen'), Js('Storm'), Js('Sunset'), Js('Tempest'), Js('Thunder'), Js('Ultimate'), Js('Undead'), Js('Undercover'), Js('Underworld'), Js('Vampire'), Js('Werewolf')]))
            PyJs_LONG_8_()
            def PyJs_LONG_9_(var=var):
                return var.put('names2', Js([Js('Adventure'), Js('Age'), Js('Awakening'), Js('Blade'), Js('Blitz'), Js('Brotherhood'), Js('Call'), Js('Challenge'), Js('Champions'), Js('Choice'), Js('Chronicles'), Js('Citizen'), Js('City'), Js('Clans'), Js('Clash'), Js('Colony'), Js('Crusade'), Js('Curse'), Js('Dawn'), Js('Defender'), Js('Desciple'), Js('Destiny'), Js('Dimension'), Js('Dominion'), Js('Dungeon'), Js('Empire'), Js('Evolution'), Js('Expedition'), Js('Faction'), Js('Fate'), Js('Flames'), Js('Force'), Js('Gates'), Js('Genesis'), Js('God'), Js('Guilds'), Js('Harbinger'), Js('Harvest'), Js('Heaven'), Js('Hell'), Js('Hero'), Js('Heroes'), Js('History'), Js('Hunter'), Js('Inferno'), Js('Invasion'), Js('Isle'), Js('King'), Js('Labyrinth'), Js('Lair'), Js('Lands'), Js('Legacy'), Js('Legend'), Js('Legends'), Js('Legions'), Js('Lord'), Js('Might'), Js('Mythos'), Js('Nightmare'), Js('Oath'), Js('Odyssey'), Js('Omen'), Js('Origins'), Js('Paradise'), Js('Past'), Js('Power'), Js('Prince'), Js('Prophecy'), Js('Quest'), Js('Reach'), Js('Realm'), Js('Reaper'), Js('Reign'), Js('Revelations'), Js('Rise'), Js('Rising'), Js('Saga'), Js('Sanctuary'), Js('School'), Js('Secrets'), Js('Siege'), Js('Skies'), Js('Sorcery'), Js('Soul'), Js('Spyre'), Js('Story'), Js('Stronghold'), Js('Surprise'), Js('Tale'), Js('Throne'), Js('Time'), Js('Treasure'), Js('Tribes'), Js('Universe'), Js('Vaults'), Js('War'), Js('Ward'), Js('Watch'), Js('Wizards'), Js('World')]))
            PyJs_LONG_9_()
            def PyJs_LONG_10_(var=var):
                return var.put('names3', Js([Js('Angels'), Js('Barbarians'), Js('Castles'), Js('Codes'), Js('Conquest'), Js('Crowns'), Js('Curses'), Js('Demons'), Js('Dragons'), Js('Dreams'), Js('Elves'), Js('Ghosts'), Js('Giants'), Js('Goblins'), Js('Illusions'), Js('Kings'), Js('Knights'), Js('Legends'), Js('Lords'), Js('Love'), Js('Magic'), Js('Monsters'), Js('Mysteries'), Js('Nightmares'), Js('Orcs'), Js('Outlaws'), Js('Phantoms'), Js('Pirates'), Js('Power'), Js('Prophecies'), Js('Realms'), Js('Riddles'), Js('Robots'), Js('Sailors'), Js('Secrets'), Js('Shadows'), Js('Shields'), Js('Ships'), Js('Sorcery'), Js('Souls'), Js('Spells'), Js('Spirits'), Js('Swords'), Js('Traitors'), Js('Treasures'), Js('Vampires'), Js('Vikings'), Js('War'), Js('Werewolves'), Js('Wizards')]))
            PyJs_LONG_10_()
            def PyJs_LONG_11_(var=var):
                return var.put('names4', Js([Js('Betrayal'), Js('Bravery'), Js('Conjury'), Js('Conquest'), Js('Danger'), Js('Darkness'), Js('Death'), Js('Deception'), Js('Enigmas'), Js('Exploration'), Js('Fables'), Js('Faith'), Js('Fate'), Js('Fortune'), Js('Hauntings'), Js('Heirlooms'), Js('Heritage'), Js('Honor'), Js('Hope'), Js('Horrors'), Js('Justice'), Js('Labyrinths'), Js('Legacies'), Js('Legends'), Js('Lore'), Js('Love'), Js('Magic'), Js('Memories'), Js('Miracles'), Js('Murder'), Js('Mystery'), Js('Mythology'), Js('Mythos'), Js('Myths'), Js('Nightmares'), Js('Oracles'), Js('Origins'), Js('Riddles'), Js('Rituals'), Js('Romance'), Js('Runes'), Js('Secrets'), Js('Shadows'), Js('Sins'), Js('Sorrow'), Js('Supremacy'), Js('Time'), Js('Triumph'), Js('Victory'), Js('Witchcraft')]))
            PyJs_LONG_11_()
            def PyJs_LONG_12_(var=var):
                return var.put('names5', Js([Js('Aeon'), Js('Age'), Js('Agent'), Js('Angel'), Js('Armies'), Js('Ashes'), Js('Aura'), Js('Blade'), Js('Book'), Js('Burden'), Js('Case'), Js('Century'), Js('Challenges'), Js('Champions'), Js('Children'), Js('Chronicles'), Js('Circle'), Js('City'), Js('Clans'), Js('Core'), Js('Corruption'), Js('Creatures'), Js('Crypt'), Js('Cult'), Js('Curse'), Js('Dawn'), Js('Death'), Js('Demons'), Js('Destiny'), Js('Dimension'), Js('Division'), Js('Dominion'), Js('Doom'), Js('Dreams'), Js('Dungeons'), Js('Edge'), Js('Empire'), Js('Enemy'), Js('Era'), Js('Evil'), Js('Fables'), Js('Face'), Js('Faith'), Js('Fall'), Js('Fate'), Js('Fire'), Js('Forest'), Js('Game'), Js('God'), Js('Gods'), Js('Guardians'), Js('Guilds'), Js('Heart'), Js('Heroes'), Js('Immortals'), Js('Invasion'), Js('Journey'), Js('Kingdom'), Js('Kings'), Js('Knights'), Js('Lair'), Js('Land'), Js('Legacy'), Js('Legend'), Js('Legends'), Js('Lords'), Js('Masters'), Js('Monsters'), Js('Mortals'), Js('Mysteries'), Js('Myths'), Js('Oracles'), Js('Origin'), Js('Path'), Js('Planet'), Js('Quests'), Js('Realm'), Js('Revelations'), Js('Rise'), Js('Saga'), Js('Saints'), Js('School'), Js('Search'), Js('Secret'), Js('Seed'), Js('Shadows'), Js('Souls'), Js('Swords'), Js('Tale'), Js('Tales'), Js('Throne'), Js('Time'), Js('Titans'), Js('Tombs'), Js('Tribes'), Js('Voice'), Js('Voices'), Js('Whispers'), Js('Winds'), Js('World')]))
            PyJs_LONG_12_()
            def PyJs_LONG_13_(var=var):
                return var.put('names6', Js([Js('Alchemy'), Js('Aliens'), Js('Anarchy'), Js('Ancestors'), Js('Angels'), Js('Autumn'), Js('Blood'), Js('Chaos'), Js('Crimson'), Js('Crisis'), Js('Darkness'), Js('Death'), Js('Destruction'), Js('Discovery'), Js('Dominion'), Js('Doom'), Js('Dragons'), Js('Dreams'), Js('Dust'), Js('Dystopia'), Js('Earth'), Js('Echoes'), Js('Eden'), Js('Elements'), Js('Eternity'), Js('Euphoria'), Js('Evil'), Js('Evolution'), Js('Exiles'), Js('Exploration'), Js('Fate'), Js('Fear'), Js('Fire'), Js('Fortune'), Js('Fury'), Js('Gods'), Js('Gold'), Js('Greed'), Js('Grimoires'), Js('Guilds'), Js('Heaven'), Js('History'), Js('Honesty'), Js('Honor'), Js('Hope'), Js('Infernals'), Js('Infinity'), Js('Iron'), Js('Judgement'), Js('Kings'), Js('Knights'), Js('Labyrinths'), Js('Legions'), Js('Light'), Js('Lore'), Js('Love'), Js('Magic'), Js('Malice'), Js('Mankind'), Js('Might'), Js('Money'), Js('Moonlight'), Js('Mystery'), Js('Necromancy'), Js('New Earth'), Js('Nightmares'), Js('Power'), Js('Prophecies'), Js('Rage'), Js('Realms'), Js('Rebirth'), Js('Reckoning'), Js('Retribution'), Js('Romance'), Js('Ruins'), Js('Runes'), Js('Savagery'), Js('Science'), Js('Sin'), Js('Sorcery'), Js('Souls'), Js('Spring'), Js('Stars'), Js('Steel'), Js('Summer'), Js('Thieves'), Js('Thunder'), Js('Time'), Js('Trials'), Js('Truth'), Js('Twilight'), Js('Undeath'), Js('Utopia'), Js('Valor'), Js('Vampires'), Js('Vengeance'), Js('Virtue'), Js('War'), Js('Werewolves'), Js('Winter')]))
            PyJs_LONG_13_()
            def PyJs_LONG_14_(var=var):
                return var.put('names7', Js([Js('Arcane'), Js('Arche'), Js('Astro'), Js('Battle'), Js('Bio'), Js('Blood'), Js('Brutal'), Js('Castle'), Js('Chrono'), Js('Dark'), Js('Dead'), Js('Demon'), Js('Dragon'), Js('Dream'), Js('Ember'), Js('Ever'), Js('Far'), Js('Fire'), Js('Ghost'), Js('Grim'), Js('Heaven'), Js('Hell'), Js('Hero'), Js('Iron'), Js('Knight'), Js('Light'), Js('Mage'), Js('Magic'), Js('Master'), Js('Mortal'), Js('Night'), Js('Phantom'), Js('Quest'), Js('Raid'), Js('Rune'), Js('Sacred'), Js('Scarlet'), Js('Shadow'), Js('Shard'), Js('Siege'), Js('Sky'), Js('Soul'), Js('Space'), Js('Spell'), Js('Star'), Js('Storm'), Js('Strong'), Js('Thunder'), Js('Trade'), Js('War')]))
            PyJs_LONG_14_()
            def PyJs_LONG_15_(var=var):
                return var.put('names8', Js([Js('age'), Js('band'), Js('blade'), Js('borne'), Js('child'), Js('craft'), Js('crest'), Js('cry'), Js('doom'), Js('fight'), Js('fire'), Js('flight'), Js('force'), Js('gate'), Js('guard'), Js('guild'), Js('heart'), Js('hunt'), Js('kin'), Js('land'), Js('line'), Js('mare'), Js('master'), Js('mind'), Js('more'), Js('night'), Js('path'), Js('phase'), Js('realm'), Js('reign'), Js('rite'), Js('run'), Js('scape'), Js('shift'), Js('side'), Js('slayer'), Js('space'), Js('sphere'), Js('star'), Js('stone'), Js('storm'), Js('tale'), Js('tide'), Js('time'), Js('trail'), Js('vale'), Js('view'), Js('ville'), Js('watch'), Js('way')]))
            PyJs_LONG_15_()
            break
        if SWITCHED or PyJsStrictEq(CONDITION, Js('simulation')):
            SWITCHED = True
            def PyJs_LONG_16_(var=var):
                return var.put('names1', Js([Js('Bow'), Js('Gun'), Js('Crossbow'), Js('Rifle'), Js('Blade'), Js('Sword'), Js('Cannon'), Js('Agriculture'), Js('Airport'), Js('Alien'), Js('Android'), Js('Apocalypse'), Js('Armored'), Js('Assault'), Js('Base'), Js('Battle'), Js('Battlecruiser'), Js('Beach'), Js('Boat'), Js('Business'), Js('Car'), Js('Chaos'), Js('City'), Js('Colony'), Js('Combat'), Js('Conflict'), Js('Construction'), Js('Cooking'), Js('Corporation'), Js('Crime'), Js('Crisis'), Js('Damage'), Js('Demolition'), Js('Destruction'), Js('Disaster'), Js('Disease'), Js('Drive'), Js('Driving'), Js('Droid'), Js('Empire'), Js('Evolution'), Js('Exploration'), Js('Family'), Js('Farm'), Js('Fishing'), Js('Flight'), Js('Future'), Js('Galactic'), Js('Galaxy'), Js('God'), Js('Helicopter'), Js('History'), Js('Hospital'), Js('House'), Js('Hunter'), Js('Jet'), Js('Jetfighter'), Js('Kingdom'), Js('Knight'), Js('Lightspeed'), Js('Lunar'), Js('Mech'), Js('Medieval'), Js('Mining'), Js('Nation'), Js('Nuclear'), Js('Panzer'), Js('Party'), Js('Patrol'), Js('Pilot'), Js('Plane'), Js('Police'), Js('President'), Js('Rail'), Js('Railroad'), Js('Robot'), Js('Rollercoaster'), Js('Sail'), Js('Science'), Js('Ship'), Js('Space'), Js('Spacebase'), Js('Spaceflight'), Js('Squadron'), Js('Star'), Js('Sub'), Js('Submarine'), Js('Subway'), Js('Surgeon'), Js('Tank'), Js('Town'), Js('Traffic'), Js('Train'), Js('Transit'), Js('Tribe'), Js('Universe'), Js('Vampire'), Js('Vehicle'), Js('Village'), Js('War'), Js('Weather'), Js('Werewolf'), Js('Wildlife'), Js('Wing'), Js('World'), Js('Zombie'), Js('Zoo')]))
            PyJs_LONG_16_()
            def PyJs_LONG_17_(var=var):
                return var.put('names2', Js([Js('Aces'), Js('Adventure'), Js('Alliance'), Js('Assassin'), Js('Battle'), Js('Builder'), Js('Captain'), Js('Challenge'), Js('Challenger'), Js('Champion'), Js('Chronicles'), Js('Collection'), Js('Combat'), Js('Command'), Js('Commander'), Js('Company'), Js('Conflict'), Js('Control'), Js('Corp'), Js('Creator'), Js('Days'), Js('Defender'), Js('Deluxe'), Js('Design'), Js('Designer'), Js('Driver'), Js('Dynasty'), Js('Edge'), Js('Elite'), Js('Engineer'), Js('Expedition'), Js('Express'), Js('Fighter'), Js('Force'), Js('Horizon'), Js('Initiative'), Js('Kingdom'), Js('Legacy'), Js('Legend'), Js('Machines'), Js('Manager'), Js('Mania'), Js('Memories'), Js('Mercenary'), Js('Operation'), Js('Pilot'), Js('Playground'), Js('Program'), Js('Project'), Js('Race'), Js('Realm'), Js('Renegade'), Js('Rescue'), Js('Revelation'), Js('School'), Js('Service'), Js('Sim'), Js('Simulator'), Js('Tales'), Js('Tycoon'), Js('Typhoon'), Js('Universe'), Js('Unlimited'), Js('Venture'), Js('War'), Js('World')]))
            PyJs_LONG_17_()
            def PyJs_LONG_18_(var=var):
                return var.put('names3', Js([Js('Airplanes'), Js('Aliens'), Js('Androids'), Js('Assassins'), Js('Beasts'), Js('Clans'), Js('Creatures'), Js('Disasters'), Js('Diseases'), Js('Doctors'), Js('Dragons'), Js('Droids'), Js('Empires'), Js('Engineers'), Js('Gods'), Js('Helicopters'), Js('Hunters'), Js('Kingdoms'), Js('Knights'), Js('Magic'), Js('Mercenaries'), Js('Monsters'), Js('Mutants'), Js('Nations'), Js('Nature'), Js('Pilots'), Js('Planes'), Js('Realms'), Js('Robots'), Js('Sails'), Js('Science'), Js('Ships'), Js('Skeletons'), Js('Soldiers'), Js('Space'), Js('Spells'), Js('Stars'), Js('Tanks'), Js('Titans'), Js('Towns'), Js('Tribes'), Js('Vampires'), Js('Villages'), Js('Viruses'), Js('Warships'), Js('Weather'), Js('Werewolves'), Js('Wildlife'), Js('Wings'), Js('Zombies')]))
            PyJs_LONG_18_()
            def PyJs_LONG_19_(var=var):
                return var.put('names4', Js([Js('Adventures'), Js('Alliances'), Js('Assassins'), Js('Battles'), Js('Builders'), Js('Captains'), Js('Challengers'), Js('Challenges'), Js('Champions'), Js('Chronicles'), Js('Civilizations'), Js('Commanders'), Js('Companies'), Js('Conflicts'), Js('Constructions'), Js('Creators'), Js('Defenders'), Js('Designers'), Js('Discoveries'), Js('Drivers'), Js('Dynasties'), Js('Explorations'), Js('Flights'), Js('Formations'), Js('Guns'), Js('Kingdoms'), Js('Legacies'), Js('Legends'), Js('Machines'), Js('Madness'), Js('Managers'), Js('Memories'), Js('Mercenaries'), Js('Motions'), Js('Operations'), Js('Pilots'), Js('Programs'), Js('Projects'), Js('Races'), Js('Realms'), Js('Renegades'), Js('Revelations'), Js('Risks'), Js('Simulations'), Js('Tactics'), Js('Tales'), Js('Universes'), Js('Victory'), Js('Warriors'), Js('Worlds')]))
            PyJs_LONG_19_()
            def PyJs_LONG_20_(var=var):
                return var.put('names5', Js([Js('Aces'), Js('Adventures'), Js('Age'), Js('Art'), Js('Battles'), Js('Beasts'), Js('Builders'), Js('Castle'), Js('Champions'), Js('Chronicles'), Js('City'), Js('Clans'), Js('Company'), Js('Conflict'), Js('Contracts'), Js('Creation'), Js('Creators'), Js('Creatures'), Js('Crew'), Js('Dawn'), Js('Days'), Js('Defenders'), Js('Designers'), Js('Drivers'), Js('Empire'), Js('Engineers'), Js('Era'), Js('Family'), Js('Force'), Js('Fortress'), Js('Galaxy'), Js('Gods'), Js('Heroes'), Js('History'), Js('Kingdom'), Js('Kings'), Js('Legacy'), Js('Legend'), Js('Legends'), Js('Machines'), Js('Manager'), Js('Monsters'), Js('Motions'), Js('Operation'), Js('Pilots'), Js('Projects'), Js('Realm'), Js('Rise'), Js('Rulers'), Js('School'), Js('Tales'), Js('Titans'), Js('Towns'), Js('Tribes'), Js('Universe'), Js('Ventures'), Js('Village'), Js('World')]))
            PyJs_LONG_20_()
            def PyJs_LONG_21_(var=var):
                return var.put('names6', Js([Js('Alliances'), Js('Androids'), Js('Animals'), Js('Cargo'), Js('Cars'), Js('Chemicals'), Js('Cities'), Js('Co-Op'), Js('Colonies'), Js('Combat'), Js('Construction'), Js('Creation'), Js('Demolition'), Js('Destiny'), Js('Discovery'), Js('Droids'), Js('Emergency'), Js('Empires'), Js('Evolution'), Js('Farming'), Js('Farms'), Js('Fire'), Js('Flight'), Js('Food'), Js('Freedom'), Js('Glory'), Js('Guns'), Js('Honor'), Js('Iron'), Js('Knights'), Js('Mining'), Js('Minions'), Js('Mutation'), Js('Nations'), Js('Nature'), Js('Oceans'), Js('Planets'), Js('Power'), Js('Racing'), Js('Rails'), Js('Roads'), Js('Shadows'), Js('Skies'), Js('Space'), Js('Spaceflight'), Js('Stars'), Js('Steel'), Js('Tanks'), Js('Time'), Js('Timetravel'), Js('Transport'), Js('Vengeance'), Js('War'), Js('Wildlife'), Js('Worlds')]))
            PyJs_LONG_21_()
            def PyJs_LONG_22_(var=var):
                return var.put('names7', Js([Js('Agri'), Js('Air'), Js('Arcane'), Js('Arche'), Js('Astro'), Js('Battle'), Js('Bio'), Js('Bow'), Js('Build'), Js('Castle'), Js('City'), Js('Combat'), Js('Demo'), Js('Family'), Js('Farm'), Js('Fight'), Js('Flight'), Js('Food'), Js('Gun'), Js('Heli'), Js('Hero'), Js('Hunt'), Js('Iron'), Js('Jet'), Js('Knight'), Js('Life'), Js('Mage'), Js('Magic'), Js('Mecha'), Js('Mining'), Js('Mortal'), Js('Phantom'), Js('Plane'), Js('Police'), Js('Race'), Js('Rail'), Js('Robot'), Js('Shadow'), Js('Sky'), Js('Soul'), Js('Space'), Js('Spell'), Js('Star'), Js('Stealth'), Js('Storm'), Js('Tank'), Js('Trade'), Js('Train'), Js('Truck'), Js('War')]))
            PyJs_LONG_22_()
            def PyJs_LONG_23_(var=var):
                return var.put('names8', Js([Js('base'), Js('blade'), Js('block'), Js('bots'), Js('clad'), Js('command'), Js('corp'), Js('craft'), Js('fighter'), Js('force'), Js('front'), Js('gear'), Js('hero'), Js('life'), Js('light'), Js('line'), Js('lite'), Js('mania'), Js('master'), Js('path'), Js('plan'), Js('pro'), Js('raid'), Js('realm'), Js('rise'), Js('scape'), Js('sim'), Js('space'), Js('speed'), Js('state'), Js('strike'), Js('tech'), Js('ville'), Js('ways'), Js('works')]))
            PyJs_LONG_23_()
            break
        if SWITCHED or PyJsStrictEq(CONDITION, Js('sports')):
            SWITCHED = True
            def PyJs_LONG_24_(var=var):
                return var.put('names1', Js([Js('Angler'), Js('Bar Games'), Js('World Class'), Js('Baseball'), Js('Basket'), Js('Basketball'), Js('Beach'), Js('Biathlon'), Js('Big Game'), Js('Big Match'), Js('Bow'), Js('Bowling'), Js('Boxing'), Js('Bullrider'), Js('College Games'), Js('Cricket'), Js('Crossbow'), Js('Cycling'), Js('Dart'), Js('Decathlon'), Js('Deep Sea'), Js('Dirt Race'), Js('Dodgeball'), Js('Downhill'), Js('Extreme Sports'), Js('Fantasy Sports'), Js('Field'), Js('Fighting'), Js('Fishing'), Js('Football'), Js('Formula One'), Js('Freestyle'), Js('Freshwater'), Js('Golf'), Js('Grandslam'), Js('Gun'), Js('Gym'), Js('Gymnast'), Js('Handball'), Js('Heavyweight'), Js('Hockey'), Js('Horse Race'), Js('Hunting'), Js('Ice Hockey'), Js('Karate'), Js('Marathon'), Js('Martial Arts'), Js('Master League'), Js('Mountain Bike'), Js('Olympic'), Js('Open Ice'), Js('Outdoor'), Js('Pro Fighter'), Js('Racing'), Js('Rifle'), Js('Rock Climbing'), Js('Rodeo'), Js('Rugby'), Js('Safari'), Js('Ski'), Js('Skydive'), Js('Snooker'), Js('Snow Sports'), Js('Soccer'), Js('Sports'), Js('Street Racing'), Js('Strongest Man'), Js('Summer Sports'), Js('Tennis'), Js('Touchdown'), Js('Volleyball'), Js('Water Sports'), Js('Whitewater'), Js('Winter Sports'), Js('Wrestling')]))
            PyJs_LONG_24_()
            def PyJs_LONG_25_(var=var):
                return var.put('names2', Js([Js('Challenger'), Js('Champions'), Js('Championship'), Js('Coach'), Js('Deluxe'), Js('Evolution'), Js('Experience'), Js('Extreme'), Js('Games'), Js('Generation'), Js('Heroes'), Js('Icons'), Js('League'), Js('Legends'), Js('Manager'), Js('Master Challenge'), Js('Master Series'), Js('Masters'), Js('Meta Game'), Js('Online'), Js('Paradise'), Js('Pro'), Js('Pro Tournament'), Js('Professionals'), Js('Revolution'), Js('Simulator'), Js('Stars'), Js('Street Edition'), Js('Super Challenge'), Js('Super Stars'), Js('Titans'), Js('Top Shots'), Js('Tournament'), Js('Training Manager'), Js('Tycoons'), Js('Unleashed'), Js('Unlimited'), Js('World Championship'), Js('World Cup')]))
            PyJs_LONG_25_()
            def PyJs_LONG_26_(var=var):
                return var.put('names3', Js([Js('All-Stars'), Js('Heavyweights'), Js('Rising Stars'), Js('Amateurs'), Js('Athletes'), Js('Avengers'), Js('Challengers'), Js('Champions'), Js('Champs'), Js('Clubs'), Js('Coaches'), Js('Competitors'), Js('Crews'), Js('Failures'), Js('Heroes'), Js('Hunters'), Js('Jocks'), Js('Legends'), Js('Losers'), Js('Managers'), Js('Masters'), Js('Medalists'), Js('Mentors'), Js('Newcomers'), Js('Opponents'), Js('Participants'), Js('Players'), Js('Professionals'), Js('Pros'), Js('Rookies'), Js('Squads'), Js('Teams'), Js('Trainees'), Js('Trainers'), Js('Underdogs'), Js('Victors'), Js('Winners')]))
            PyJs_LONG_26_()
            def PyJs_LONG_27_(var=var):
                return var.put('names4', Js([Js('Adrenaline'), Js('Boot Camp'), Js('Challenges'), Js('Championships'), Js('Defeats'), Js('Face Offs'), Js('Fame'), Js('Front Pages'), Js('Games'), Js('Infamy'), Js('Leagues'), Js('Major Leagues'), Js('Management'), Js('Medals'), Js('Meta Games'), Js('Olympic Games'), Js('Playoffs'), Js('Power Plays'), Js('Premier League'), Js('Premierships'), Js('Prizes'), Js('Seasons'), Js('Signatures'), Js('Tournaments'), Js('Trainings'), Js('Trophies'), Js('Trophy Hunting'), Js('Victories'), Js('World Cups'), Js('World Tours')]))
            PyJs_LONG_27_()
            def PyJs_LONG_28_(var=var):
                return var.put('names5', Js([Js('Athletes'), Js('Challenges'), Js('Championships'), Js('Champs'), Js('Clubs'), Js('Coach'), Js('Crews'), Js('Day'), Js('Drive'), Js('Games'), Js('Generation'), Js('Gladiators'), Js('Heroes'), Js('Hunts'), Js('Kicks'), Js('Kings'), Js('Leagues'), Js('Legends'), Js('Lords'), Js('Managers'), Js('Masters'), Js('Medals'), Js('Plays'), Js('Pros'), Js('Rush'), Js('Season'), Js('Shots'), Js('Speed'), Js('Sports'), Js('Stars'), Js('Teams'), Js('Times'), Js('Tournaments'), Js('Trainers'), Js('Trophies'), Js('Uniforms'), Js('World'), Js('World Cup'), Js('World Tour')]))
            PyJs_LONG_28_()
            def PyJs_LONG_29_(var=var):
                return var.put('names6', Js([Js('Adrenaline'), Js('Archery'), Js('Baseball'), Js('Basket'), Js('Basketball'), Js('Big Game'), Js('Boot Camp'), Js('Boxing'), Js('Cricket'), Js('Cycling'), Js('Dirt Racing'), Js('Dodgeball'), Js('Extra Time'), Js('Extreme'), Js('Fight'), Js('Fighting'), Js('Fishing'), Js('Football'), Js('Formula One'), Js('Freestyle'), Js('Golf'), Js('Grand Slams'), Js('Guns'), Js('Handball'), Js('Hockey'), Js('Ice Hockey'), Js('Karate'), Js('Martial Arts'), Js('Perfection'), Js('Pro Fighting'), Js('Race'), Js('Rock Climbing'), Js('Rugby'), Js('Snow Sports'), Js('Soccer'), Js('Sport'), Js('Street Racing'), Js('Strength'), Js('Summer'), Js('Tennis'), Js('Touchdown'), Js('Volleyball'), Js('Water Sports'), Js('Whitewater'), Js('Winter'), Js('Winter Sports'), Js('World Class'), Js('Wrestling'), Js('the Field'), Js('the Gym'), Js('the Hunt')]))
            PyJs_LONG_29_()
            def PyJs_LONG_30_(var=var):
                return var.put('names7', Js([Js('Baseball'), Js('Basket'), Js('Basketball'), Js('Bat'), Js('Boxing'), Js('Cricket'), Js('Dodgeball'), Js('Field'), Js('Fight'), Js('Fighting'), Js('Football'), Js('Freestyle'), Js('Game'), Js('Golf'), Js('Handball'), Js('Hockey'), Js('Hunt'), Js('Hunting'), Js('Karate'), Js('Kick'), Js('Martial'), Js('Puck'), Js('Punch'), Js('Race'), Js('Racket'), Js('Riding'), Js('Rugby'), Js('Snow'), Js('Soccer'), Js('Speed'), Js('Sport'), Js('Street'), Js('Strength'), Js('Summer'), Js('Tennis'), Js('Volleyball'), Js('Water'), Js('Winter'), Js('Wrestling')]))
            PyJs_LONG_30_()
            var.put('names8', Js([Js('X'), Js('ace'), Js('art'), Js('champ'), Js('life'), Js('master'), Js('max'), Js('pro'), Js('pros'), Js('sim'), Js('slam'), Js('star'), Js('style'), Js('time'), Js('world')]))
            break
        if SWITCHED or PyJsStrictEq(CONDITION, Js('strategy')):
            SWITCHED = True
            def PyJs_LONG_31_(var=var):
                return var.put('names1', Js([Js('Air'), Js('Airborne'), Js('Alien'), Js('Ancient'), Js('Android'), Js('Angel'), Js('Arcane'), Js('Armored'), Js('Asteroid'), Js('Barbarian'), Js('Battlefield'), Js('Battlefront'), Js('Battleground'), Js('Blood'), Js('Border'), Js('Boundless'), Js('Brave'), Js('Cannon'), Js('Castle'), Js('Celtic'), Js('Champion'), Js('Chaos'), Js('City'), Js('Civil'), Js('Clan'), Js('Colonial'), Js('Covert'), Js('Creature'), Js('Crown'), Js('Crusader'), Js('Cultural'), Js('Dark'), Js('Demon'), Js('Destiny'), Js('Dragon'), Js('Dread'), Js('Drone'), Js('Dungeon'), Js('Elemental'), Js('Emergency'), Js('Empire'), Js('Enemy'), Js('Fantasy'), Js('Fire'), Js('Frontier'), Js('Frontline'), Js('Future'), Js('Galactic'), Js('Galaxy'), Js('Gladiator'), Js('Global'), Js('God'), Js('Grand'), Js('Guardian'), Js('Guild'), Js('Hacker'), Js('Hero'), Js('History'), Js('Honorbound'), Js('Immortal'), Js('Infinite'), Js('Iron'), Js('Kingdom'), Js('Knight'), Js('Liberty'), Js('Magic'), Js('Medieval'), Js('Metal'), Js('Midnight'), Js('Military'), Js('Monster'), Js('Mortal'), Js('Mutant'), Js('Mythic'), Js('Nation'), Js('Nature'), Js('Naval'), Js('Nightmare'), Js('Ninja'), Js('Nuclear'), Js('Ocean'), Js('Pirate'), Js('Planet'), Js('Revolution'), Js('Rune'), Js('Samurai'), Js('Sanguine'), Js('Settler'), Js('Silent'), Js('Solar'), Js('Space'), Js('Star'), Js('Syndicate'), Js('Titan'), Js('Toxic'), Js('Trade'), Js('Tribal'), Js('Undead'), Js('Vampire'), Js('Wonder')]))
            PyJs_LONG_31_()
            def PyJs_LONG_32_(var=var):
                return var.put('names2', Js([Js('Academy'), Js('Aftermath'), Js('Age'), Js('Alert'), Js('Allegiance'), Js('Alliances'), Js('Ambition'), Js('Apocalypse'), Js('Armageddon'), Js('Armies'), Js('Ascension'), Js('Assault'), Js('Awakening'), Js('Battalion'), Js('Brigade'), Js('Campaign'), Js('Cataclysm'), Js('Chronicles'), Js('Civilization'), Js('Combat'), Js('Command'), Js('Commander'), Js('Conflict'), Js('Conquest'), Js('Conspiracy'), Js('Counterstrike'), Js('Crisis'), Js('Defence'), Js('Defender'), Js('Destination'), Js('Destruction'), Js('Diplomacy'), Js('Discovery'), Js('Domination'), Js('Dominion'), Js('Dynasty'), Js('Earth'), Js('Empire'), Js('Enterprise'), Js('Evolution'), Js('Expansion'), Js('Exploration'), Js('Frenzy'), Js('Genesis'), Js('Glory'), Js('Heritage'), Js('Infestation'), Js('Intelligence'), Js('Invasion'), Js('Kingdoms'), Js('Laws'), Js('League'), Js('Legacy'), Js('Legends'), Js('Legion'), Js('Liberation'), Js('Masters'), Js('Mayhem'), Js('Mogul'), Js('Nation'), Js('Nemesis'), Js('Offensive'), Js('Operation'), Js('Outbreak'), Js('Outcasts'), Js('Overlord'), Js('Project'), Js('Prophecy'), Js('Realm'), Js('Redemption'), Js('Renaissance'), Js('Resistance'), Js('Resurrection'), Js('Retaliation'), Js('Revolution'), Js('Rising'), Js('Siege'), Js('Strategies'), Js('Strategy'), Js('Strike Force'), Js('Survival'), Js('Tactics'), Js('Termination'), Js('Tournament'), Js('Tribulation'), Js('Twilight'), Js('Tycoon'), Js('Union'), Js('Universe'), Js('Unrest'), Js('Uprising'), Js('Vendetta'), Js('Vengeance'), Js('Warcraft'), Js('Warfare'), Js('Warlords'), Js('Warriors'), Js('World'), Js('Wrath'), Js('Zone')]))
            PyJs_LONG_32_()
            def PyJs_LONG_33_(var=var):
                return var.put('names3', Js([Js('Act'), Js('Acts'), Js('Age'), Js('Creatures'), Js('Angels'), Js('Arena'), Js('Armies'), Js('Army'), Js('Art'), Js('Ascension'), Js('Awakening'), Js('Balance'), Js('Band'), Js('Beasts'), Js('Blood'), Js('Bombs'), Js('Bullets'), Js('Cannons'), Js('Champions'), Js('Chariots'), Js('Clans'), Js('Clash'), Js('Colonies'), Js('Company'), Js('Cost'), Js('Crown'), Js('Curse'), Js('Dawn'), Js('Defender'), Js('Demons'), Js('Dungeons'), Js('Elements'), Js('Empire'), Js('End'), Js('Faces'), Js('Fall'), Js('Fields'), Js('Fires'), Js('Flames'), Js('Force'), Js('Galaxy'), Js('Game'), Js('Gates'), Js('God'), Js('Gods'), Js('Guardians'), Js('Guns'), Js('Hearts'), Js('Heritage'), Js('Hero'), Js('Heroes'), Js('Hordes'), Js('King'), Js('Kingdom'), Js('Kingdoms'), Js('Kings'), Js('Knights'), Js('Land'), Js('Legacies'), Js('Legacy'), Js('Legends'), Js('Legions'), Js('Light'), Js('Lord'), Js('Lords'), Js('Machines'), Js('Magic'), Js('March'), Js('Master'), Js('Mastermind'), Js('Masters'), Js('Memories'), Js('Mercenaries'), Js('Monsters'), Js('Monuments'), Js('Planet'), Js('Price'), Js('Realm'), Js('Realms'), Js('Rise'), Js('Siege'), Js('Soldier'), Js('Songs'), Js('Space'), Js('Spells'), Js('Spirit'), Js('Spirits'), Js('Swords'), Js('Tales'), Js('Titans'), Js('Towers'), Js('Treasures'), Js('Tribes'), Js('Vampires'), Js('Virtues'), Js('Warlords'), Js('Werewolves'), Js('Whispers'), Js('World'), Js('Worlds')]))
            PyJs_LONG_33_()
            def PyJs_LONG_34_(var=var):
                return var.put('names4', Js([Js('Adventure'), Js('Agony'), Js('Anarchy'), Js('Annihilation'), Js('Ashes'), Js('Assault'), Js('Battle'), Js('Betrayal'), Js('Blood'), Js('Carnage'), Js('Chaos'), Js('Civilization'), Js('Combat'), Js('Conflict'), Js('Conquest'), Js('Control'), Js('Corruption'), Js('Courage'), Js('Danger'), Js('Death'), Js('Defeat'), Js('Destiny'), Js('Destruction'), Js('Disaster'), Js('Discipline'), Js('Domination'), Js('Dominion'), Js('Doom'), Js('Dust'), Js('Elysium'), Js('Embers'), Js('Empires'), Js('Eternity'), Js('Evil'), Js('Expansion'), Js('Faith'), Js('Fate'), Js('Fire'), Js('Flames'), Js('Fortune'), Js('Generations'), Js('Glory'), Js('Gore'), Js('Havoc'), Js('Hazard'), Js('Heaven'), Js('Honor'), Js('Infamy'), Js('Invasion'), Js('Iron'), Js('Law'), Js('Liberation'), Js('Liberty'), Js('Life'), Js('Light'), Js('Limbo'), Js('Magic'), Js('Malice'), Js('Mayhem'), Js('Might'), Js('Misery'), Js('Mutiny'), Js('Myths'), Js('Nowhere'), Js('Oblivion'), Js('Pain'), Js('Peace'), Js('Peril'), Js('Power'), Js('Prestige'), Js('Retaliation'), Js('Retribution'), Js('Ruins'), Js('Shadows'), Js('Siege'), Js('Souls'), Js('Spite'), Js('Steel'), Js('Strategy'), Js('Strife'), Js('Supremacy'), Js('Tactics'), Js('Terror'), Js('Thunder'), Js('Tomorrow'), Js('Tragedy'), Js('Treason'), Js('Turmoil'), Js('Twilight'), Js('Undoing'), Js('Valor'), Js('Vengeance'), Js('Victory'), Js('Violence'), Js('War'), Js('Warfare'), Js('Woe'), Js('Wonder'), Js('Wrath'), Js('Zion')]))
            PyJs_LONG_34_()
            def PyJs_LONG_35_(var=var):
                return var.put('names5', Js([Js('Ancestors'), Js('Ancients'), Js('Androids'), Js('Angels'), Js('Armies'), Js('Assassins'), Js('Barbarians'), Js('Bombs'), Js('Cannons'), Js('Castles'), Js('Champions'), Js('Chariots'), Js('Clans'), Js('Creatures'), Js('Crowns'), Js('Demons'), Js('Dragons'), Js('Dungeons'), Js('Empires'), Js('Ghosts'), Js('Giants'), Js('Gladiators'), Js('Gods'), Js('Guardians'), Js('Guilds'), Js('Heroes'), Js('Immortals'), Js('Kingdoms'), Js('Kings'), Js('Knights'), Js('Leaders'), Js('Legions'), Js('Lords'), Js('Machines'), Js('Magic'), Js('Masters'), Js('Mercenaries'), Js('Monsters'), Js('Mortals'), Js('Settlers'), Js('Soldiers'), Js('Spells'), Js('Spirits'), Js('Tibes'), Js('Titans'), Js('Traitors'), Js('Vampires'), Js('Villains'), Js('Warlords'), Js('Weapons'), Js('Werewolves')]))
            PyJs_LONG_35_()
            def PyJs_LONG_36_(var=var):
                return var.put('names6', Js([Js('Adventure'), Js('Alliances'), Js('Anarchy'), Js('Annihilation'), Js('Assault'), Js('Betrayal'), Js('Blood'), Js('Carnage'), Js('Chaos'), Js('Combat'), Js('Command'), Js('Conflict'), Js('Conquest'), Js('Control'), Js('Corruption'), Js('Courage'), Js('Death'), Js('Defeat'), Js('Destiny'), Js('Destruction'), Js('Domination'), Js('Fame'), Js('Flames'), Js('Fortune'), Js('Glory'), Js('Havoc'), Js('Honor'), Js('Infamy'), Js('Law'), Js('Liberation'), Js('Life'), Js('Malice'), Js('Mayhem'), Js('Might'), Js('Misery'), Js('Mutiny'), Js('Mystery'), Js('Pain'), Js('Peril'), Js('Power'), Js('Retaliation'), Js('Retribution'), Js('Strategy'), Js('Strife'), Js('Supremacy'), Js('Tactics'), Js('Terror'), Js('Tragedy'), Js('Treason'), Js('Turmoil'), Js('Valor'), Js('Vengeance'), Js('Victory'), Js('Violence'), Js('War'), Js('Warfare'), Js('Woe'), Js('Wonder'), Js('Wrath')]))
            PyJs_LONG_36_()
            def PyJs_LONG_37_(var=var):
                return var.put('names7', Js([Js('Air'), Js('Angel'), Js('Anti'), Js('Arche'), Js('Ash'), Js('Astro'), Js('Battle'), Js('Bio'), Js('Blade'), Js('Blood'), Js('Bullet'), Js('Castle'), Js('Clan'), Js('Combat'), Js('Cyber'), Js('Data'), Js('Dead'), Js('Demon'), Js('Dragon'), Js('Dread'), Js('Dream'), Js('Evo'), Js('Fight'), Js('Fleet'), Js('Front'), Js('Game'), Js('Gear'), Js('Grim'), Js('Gun'), Js('Heaven'), Js('Hell'), Js('Iron'), Js('Jet'), Js('Knight'), Js('Mage'), Js('Magic'), Js('Nether'), Js('Phantom'), Js('Shadow'), Js('Siege'), Js('Sky'), Js('Soul'), Js('Space'), Js('Spell'), Js('Star'), Js('Tank'), Js('Trade'), Js('Tribe'), Js('War'), Js('Witch')]))
            PyJs_LONG_37_()
            def PyJs_LONG_38_(var=var):
                return var.put('names8', Js([Js('age'), Js('base'), Js('blade'), Js('borne'), Js('bot'), Js('cast'), Js('clad'), Js('command'), Js('craft'), Js('crest'), Js('cry'), Js('fight'), Js('fire'), Js('flight'), Js('force'), Js('front'), Js('guard'), Js('guild'), Js('heart'), Js('hunt'), Js('kin'), Js('land'), Js('life'), Js('line'), Js('mania'), Js('master'), Js('mind'), Js('more'), Js('night'), Js('path'), Js('phase'), Js('plan'), Js('pro'), Js('rage'), Js('realm'), Js('reign'), Js('rise'), Js('rush'), Js('scape'), Js('side'), Js('slayer'), Js('space'), Js('speed'), Js('star'), Js('state'), Js('strike'), Js('tale'), Js('tide'), Js('watch'), Js('way')]))
            PyJs_LONG_38_()
            break
        SWITCHED = True
        break
    var.put('result', Js([]))
    #for JS loop
    var.put('i', Js(0.0))
    while (var.get('i')<Js(10.0)):
        try:
            if (var.get('i')<Js(2.0)):
                var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names1').get('length'))))
                var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names2').get('length'))))
                var.put('names', ((var.get('names1').get(var.get('rnd'))+Js(' '))+var.get('names2').get(var.get('rnd2'))))
            else:
                if (var.get('i')<Js(4.0)):
                    var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names3').get('length'))))
                    var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names4').get('length'))))
                    var.put('names', ((var.get('names3').get(var.get('rnd'))+Js(' of '))+var.get('names4').get(var.get('rnd2'))))
                else:
                    if (var.get('i')<Js(5.0)):
                        var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length'))))
                        var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length'))))
                        while PyJsStrictEq(var.get('rnd2'),var.get('rnd')):
                            var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names5').get('length'))))
                        var.put('names', ((var.get('names5').get(var.get('rnd'))+Js(' and '))+var.get('names5').get(var.get('rnd2'))))
                    else:
                        if (var.get('i')<Js(6.0)):
                            var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length'))))
                            var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length'))))
                            while PyJsStrictEq(var.get('rnd2'),var.get('rnd')):
                                var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names6').get('length'))))
                            var.put('names', ((var.get('names6').get(var.get('rnd'))+Js(' and '))+var.get('names6').get(var.get('rnd2'))))
                        else:
                            var.put('rnd', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names7').get('length'))))
                            var.put('rnd2', var.get('Math').callprop('floor', (var.get('Math').callprop('random')*var.get('names8').get('length'))))
                            var.put('names', (var.get('names7').get(var.get('rnd'))+var.get('names8').get(var.get('rnd2'))))
            var.get('result').callprop('push', var.get('names'))
        finally:
                (var.put('i',Js(var.get('i').to_number())+Js(1))-Js(1))
    pass
    return var.get('result')
PyJsHoisted_nameGen_.func_name = 'nameGen'
var.put('nameGen', PyJsHoisted_nameGen_)
pass
pass


# Add lib to the module scope
videoGames = var.to_python()